import { z } from 'zod'

export const settingsUpdateSchema = z.object({
  labName: z.string().optional(),
  phone: z.string().optional(),
  address: z.string().optional(),
  email: z.string().optional(),
  reportFooter: z.string().optional(),
  logoDataUrl: z.string().optional(),
  department: z.string().optional(),
  reportTemplate: z.enum(['classic','tealGradient','modern','adl','skmch','receiptStyle','clinicalPro','minimalist','royalBlue']).optional(),
  slipTemplate: z.enum(['thermal','a4Bill']).optional(),
  consultantName: z.string().optional(),
  consultantDegrees: z.string().optional(),
  consultantTitle: z.string().optional(),
  consultants: z.array(z.object({
    name: z.string().optional(),
    degrees: z.string().optional(),
    title: z.string().optional(),
  })).max(3).optional(),
  qrUrl: z.string().optional(),
  // Image-2 fields
  parentLab: z.string().optional(),
  slogan: z.string().optional(),
  addressLine1: z.string().optional(),
  addressLine2: z.string().optional(),
  addressLine3: z.string().optional(),
  landlineNumber: z.string().optional(),
  mobileNumber: z.string().optional(),
  whatsappNumber: z.string().optional(),
  website: z.string().optional(),
  countryCode: z.string().optional(),
  code: z.string().optional(),
  dateFormat: z.string().optional(),
  currency: z.string().optional(),
  restrictEmployeesToChangeCollectionDate: z.boolean().optional(),
  paymentReceiveOnTestInstanceLevel: z.boolean().optional(),
  validateStock: z.boolean().optional(),
  smsActive: z.boolean().optional(),
  labHijriDateOffset: z.coerce.number().optional(),
  watermark: z.string().optional(),
  watermarkOpacity: z.coerce.number().min(0).max(1).optional(),
  watermarkAngle: z.coerce.number().optional(),
  reportFont: z.enum(['poppins','helvetica','times','courier']).optional(),
  useCustomHeaderFooter: z.boolean().optional(),
  headerImageUrl: z.string().optional(),
  footerImageUrl: z.string().optional(),
  chatgptPrompts: z.record(z.string()).optional(),
}).passthrough()

export type SettingsUpdate = z.infer<typeof settingsUpdateSchema>
