import { Schema, models, model } from 'mongoose'

// ─── Sub-schemas for each system type ───────────────────────────────────────

const CardiovascularSubSchema = new Schema({
  chestTenderness: { type: Boolean },
  palpitations: { type: Boolean },
  dyspnoea: {
    rest: { type: Boolean },
    exertion: { type: Boolean },
  },
  orthopnoea: { type: Boolean },
  radialPulse: {
    rate: { type: String },
    regular: { type: Boolean },
    irregular: { type: Boolean },
    normal: { type: Boolean },
    weak: { type: Boolean },
    bounding: { type: Boolean },
  },
  character: {
    radial: { type: Boolean },
    radioRadialDelay: { type: Boolean },
    radioFemoralDelay: { type: Boolean },
  },
  bloodPressure: {
    supineSitting: { type: String },
    systolicDiastolic: { type: String },
    standingSystolicDiastolic: { type: String },
    posturalHypotension: { type: Boolean },
  },
  apexBeat: {
    location: { type: String },
    tapping: { type: Boolean },
    thrill: { type: Boolean },
    leftParasternalHeave: { type: Boolean },
  },
  venousPulsations: {
    neckVeins: { type: Boolean },
    pericardialFrictionRub: { type: Boolean },
    exocardialSounds: { type: Boolean },
    bruit: { type: Boolean },
    varicoseVeins: { type: Boolean },
    capillaryPulsation: { type: Boolean },
    intermittentClaudication: { type: Boolean },
  },
  auscultation: {
    midEjection: { type: Boolean },
    early: { type: Boolean },
    pan: { type: Boolean },
    mid: { type: Boolean },
    late: { type: Boolean },
    diastolicLate: { type: Boolean },
    s1: { type: Boolean },
    s2: { type: Boolean },
    s3: { type: Boolean },
    s4: { type: Boolean },
    others: {
      conditionOfVesselWall: { type: String },
    },
    peripheralPulses: {
      carotid: { right: { type: Boolean }, left: { type: Boolean } },
      femoral: { right: { type: Boolean }, left: { type: Boolean } },
      popliteal: { right: { type: Boolean }, left: { type: Boolean } },
      dorsalisPedis: { right: { type: Boolean }, left: { type: Boolean } },
    },
  },
  others: { type: String },
}, { _id: false })

const RespiratorySubSchema = new Schema({
  dyspnoea: { type: Boolean },
  tachypnoea: { type: Boolean },
  useOfAccessoryMuscles: { type: Boolean },
  orthopnoea: { type: Boolean },
  runningNose: { type: Boolean },
  cough: {
    dry: { type: Boolean },
    productive: { type: Boolean },
    colour: { type: Boolean },
    white: { type: Boolean },
    yellow: { type: Boolean },
    green: { type: Boolean },
    ifYes: { type: String },
    central: { type: String },
    peripheral: { type: String },
  },
  inspection: {
    symmetrical: { type: Boolean },
    asymmetrical: { type: Boolean },
  },
  expansion: {
    pigeon: { type: Boolean },
    flat: { type: Boolean },
    dumBell: { type: Boolean },
    kyphosis: { type: Boolean },
    funnel: { type: Boolean },
    barrel: { type: Boolean },
    other: { type: Boolean },
  },
  transverseDiameter: {
    rr: { type: String },
    breathsPerMin: { type: String },
  },
  intotrusionOfChest: {
    unilateral: { type: Boolean },
    bilateral: { type: Boolean },
    hollowingOfChest: { type: String },
  },
  breathingPattern: {
    abdominoThoracic: { type: Boolean },
    thoracoAbdominal: { type: Boolean },
    mediastinalShift: { type: String },
    central: { type: Boolean },
    left: { type: Boolean },
    right: { type: Boolean },
  },
  palpation: {
    tenderSpot: { type: String },
    swelling: { type: String },
    trachea: {
      vocalFremitus: { type: Boolean },
    },
  },
  percussion: {
    normal: { type: Boolean },
    dull: { type: Boolean },
    stonyDull: { type: Boolean },
    resonant: { type: Boolean },
    hyperResonant: { type: Boolean },
  },
  auscultation: {
    breathing: { type: String },
    vesicular: { type: Boolean },
    bronchial: { type: Boolean },
    additionalSounds: { type: String },
    wheezeOrStridor: { type: Boolean },
    pleuralRub: { type: Boolean },
  },
  others: { type: String },
}, { _id: false })

const CnsSubSchema = new Schema({
  headaches: { type: Boolean },
  dizziness: { type: Boolean },
  faintingOrLossOfConsciousness: { type: Boolean },
  numbnessOrTingling: { type: Boolean },
  memoryLoss: { type: Boolean },
  orientation: {
    oriented: { yes: { type: Boolean }, no: { type: Boolean } },
    disorientedTo: { type: String },
    time: { type: Boolean },
    place: { type: Boolean },
    person: { type: Boolean },
    other: { type: String },
  },
  behavior: {
    appropriateCooperative: { type: Boolean },
    anxious: { type: Boolean },
    agitated: { type: Boolean },
    violent: { type: Boolean },
    withdrawnQuite: { type: Boolean },
    other: { type: String },
  },
  speech: {
    normal: { type: Boolean },
    slurred: { type: Boolean },
    aphasic: { type: Boolean },
    stammering: { type: Boolean },
    withArtificialAirway: { type: Boolean },
    dysarthria: { type: Boolean },
    spastic: { type: Boolean },
    other: { type: String },
  },
  levelOfConsciousness: {
    alert: { type: Boolean },
    respondsToVoice: { type: Boolean },
    respondsToPain: { type: Boolean },
    unconscious: { type: Boolean },
    drowsy: { type: Boolean },
    lethargy: { type: Boolean },
  },
  glasgowComaScale: {
    eyeResponse: { type: Boolean },
    verbalResponse: { type: Boolean },
    motorResponse: { type: Boolean },
    total: { type: String },
  },
  cranialNerves: {
    olfactory: { right: { type: String }, left: { type: String } },
    optic: {
      visualAcuity: { right: { type: String }, left: { type: String } },
      visualFields: { right: { type: String }, left: { type: String } },
      fundus: { right: { type: String }, left: { type: String } },
    },
    oculomotor: { right: { type: String }, left: { type: String } },
    trigeminal: { right: { type: String }, left: { type: String } },
    facial: { right: { type: String }, left: { type: String } },
    vestibulocochlear: { right: { type: String }, left: { type: String } },
    glossopharyngeal: { right: { type: String }, left: { type: String } },
    vagus: { right: { type: String }, left: { type: String } },
    accessory: { right: { type: String }, left: { type: String } },
    hypoglossal: { right: { type: String }, left: { type: String } },
  },
  gait: {
    normal: { type: Boolean },
    sensory: { type: Boolean },
    neuropathicHighStepping: { type: Boolean },
    hemiplegic: { type: Boolean },
    choreiform: { type: Boolean },
    diplegicSpastic: { type: Boolean },
    myopathicWaddling: { type: Boolean },
    parkinsonianFestinant: { type: Boolean },
    drunken: { type: Boolean },
  },
  others: { type: String },
}, { _id: false })

const CnsBSubSchema = new Schema({
  sensoryFunction: {
    fineTouch: { intact: { type: Boolean }, notIntact: { type: Boolean } },
    crudeTouch: { intact: { type: Boolean }, notIntact: { type: Boolean } },
    temperature: { intact: { type: Boolean }, notIntact: { type: Boolean } },
    position: { intact: { type: Boolean }, notIntact: { type: Boolean } },
    vibration: { intact: { type: Boolean }, notIntact: { type: Boolean } },
    pain: { intact: { type: Boolean }, notIntact: { type: Boolean } },
  },
  motorFunction: {
    normal: { type: Boolean },
    involuntaryMovement: { type: Boolean },
    neckStiffness: { type: Boolean },
    kerningSign: { type: Boolean },
    straightLegRaising: { type: Boolean },
    brudzinskiSign: { type: Boolean },
    others: { type: String },
  },
  reflexes: {
    biceps: { right: { type: String }, left: { type: String } },
    triceps: { right: { type: String }, left: { type: String } },
    supinator: { right: { type: String }, left: { type: String } },
    abdominal: { right: { type: String }, left: { type: String } },
    knee: { right: { type: String }, left: { type: String } },
    ankle: { right: { type: String }, left: { type: String } },
    plantar: { right: { type: String }, left: { type: String } },
    babinski: { right: { type: String }, left: { type: String } },
    clonus: { right: { type: String }, left: { type: String } },
  },
  limbs: {
    bulkUpperRight: { type: String },
    bulkUpperLeft: { type: String },
    bulkLowerRight: { type: String },
    bulkLowerLeft: { type: String },
    toneUpperRight: { type: String },
    toneUpperLeft: { type: String },
    toneLowerRight: { type: String },
    toneLowerLeft: { type: String },
    powerUpperRight: { type: String },
    powerUpperLeft: { type: String },
    powerLowerRight: { type: String },
    powerLowerLeft: { type: String },
  },
}, { _id: false })

const GastrointestinalSubSchema = new Schema({
  alternativeRoute: {
    gastrostomy: { type: Boolean },
    jejunostomy: { type: Boolean },
    nasoGastric: { type: Boolean },
    urogastric: { type: Boolean },
    ivh: { type: Boolean },
    other: { type: String },
  },
  heartBurnEpigastricPain: { type: Boolean },
  abdPain: { type: Boolean },
  nausea: { type: Boolean },
  vomiting: { type: Boolean },
  chronicConstipation: { type: Boolean },
  diarrhoea: { type: Boolean },
  dyspepsia: { type: Boolean },
  dysphagia: { type: Boolean },
  bowelContent: {
    formed: { type: Boolean },
    watery: { type: Boolean },
    hard: { type: Boolean },
    mucus: { type: Boolean },
    blood: { type: Boolean },
  },
  bowelFrequency: { type: String },
  inspection: {
    normal: { type: Boolean },
    distorted: { type: Boolean },
    scaphoid: { type: Boolean },
    sunken: { type: Boolean },
    synus: { type: Boolean },
    pigmentation: { type: Boolean },
    dilatedVeins: { type: Boolean },
    other: { type: Boolean },
  },
  palpation: {
    soft: { type: Boolean },
    rigid: { type: Boolean },
    tender: { type: Boolean },
    reboundTenderness: { type: Boolean },
    palpableMasses: { type: Boolean },
    organomegaly: { type: Boolean },
    fluidThrill: { type: Boolean },
  },
  percussion: {
    tympanic: { type: Boolean },
    shiftingDullness: { type: Boolean },
    absent: { type: Boolean },
  },
  auscultation: {
    bowelSounds: { type: Boolean },
    normoactive: { type: Boolean },
    hyperPeristalsis: { type: Boolean },
    hypoPeristalsis: { type: Boolean },
    liverBruit: { type: Boolean },
    renalBruit: { type: Boolean },
  },
  others: { type: String },
}, { _id: false })

const HerniaRectalSubSchema = new Schema({
  hernia: {
    inguinal: {
      type: { direct: { type: Boolean }, indirect: { type: Boolean } },
      location: { bilateral: { type: Boolean }, unilateral: { type: Boolean }, l: { type: Boolean }, r: { type: Boolean } },
      reducibility: { reducible: { type: Boolean }, irreducible: { type: Boolean }, strangulated: { type: Boolean } },
      coughImpulse: { positive: { type: Boolean }, negative: { type: Boolean } },
      other: { type: String },
    },
    femoral: {
      present: { type: Boolean },
      location: { bilateral: { type: Boolean }, unilateral: { type: Boolean }, l: { type: Boolean }, r: { type: Boolean } },
      reducibility: { reducible: { type: Boolean }, irreducible: { type: Boolean }, strangulated: { type: Boolean } },
      coughImpulse: { positive: { type: Boolean }, negative: { type: Boolean } },
      other: { type: String },
    },
    umbilical: {
      present: { type: Boolean },
      location: { bilateral: { type: Boolean }, unilateral: { type: Boolean }, l: { type: Boolean }, r: { type: Boolean } },
      reducibility: { reducible: { type: Boolean }, irreducible: { type: Boolean }, strangulated: { type: Boolean } },
      coughImpulse: { positive: { type: Boolean }, negative: { type: Boolean } },
      other: { type: String },
    },
    surgical: {
      present: { type: Boolean },
      location: { bilateral: { type: Boolean }, unilateral: { type: Boolean }, l: { type: Boolean }, r: { type: Boolean } },
      reducibility: { reducible: { type: Boolean }, irreducible: { type: Boolean }, strangulated: { type: Boolean } },
      coughImpulse: { positive: { type: Boolean }, negative: { type: Boolean } },
      other: { type: String },
    },
  },
  rectal: {
    fissures: { type: Boolean },
    hemorrhoids: { type: Boolean },
    prolapse: { type: Boolean },
    perinalAbscess: { type: Boolean },
    abnormalMasses: { type: Boolean },
    analWarts: { type: Boolean },
    analTags: { type: Boolean },
    others: { type: String },
    digitalExam: {
      performed: { type: Boolean },
      notPerformed: { type: Boolean },
      findings: { type: String },
    },
  },
  others: { type: String },
}, { _id: false })

const UrogenitalMusculoskeletalSubSchema = new Schema({
  urogenital: {
    unableToVoid: { type: Boolean },
    continent: { type: Boolean },
    incontinent: { type: Boolean },
    bedWetting: { type: Boolean },
    urine: { type: Boolean },
    clear: { type: Boolean },
    colour: { type: Boolean },
    cloudy: { type: Boolean },
    sediment: { type: Boolean },
    voidingAmount: { type: String },
    sufficient: { type: Boolean },
    notSufficient: { type: Boolean },
    voidingAid: {
      diapers: { type: Boolean },
      sanitaryPads: { type: Boolean },
      urisheath: { type: Boolean },
      supraPubicCatheter: { type: Boolean },
      other: { type: String },
    },
    bladder: {
      distendedBladder: { type: Boolean },
      empty: { type: Boolean },
      urinal: { type: Boolean },
      foleyCatheterSize: { type: String },
      dateInserted: { type: String },
      others: { type: String },
    },
    genitalAnomaly: { type: String },
    male: {
      normal: { type: Boolean },
      hydrocele: { type: Boolean },
      varicocele: { type: Boolean },
      undescended: { type: Boolean },
      signOfInflammation: { type: Boolean },
      clear: { type: String },
    },
    female: {
      vulvalHygiene: { type: Boolean },
      colporrhagy: { type: Boolean },
      urethralOpt: { type: Boolean },
      cystocele: { type: Boolean },
      vaginalBleeding: { type: Boolean },
      vaginalDischarge: { type: Boolean },
      dischargeDetails: { type: String },
    },
    others: { type: String },
  },
  musculoskeletal: {
    rangeType: { passive: { type: Boolean }, restricted: { type: Boolean } },
    rangeOfMovement: { location: { type: String } },
    weaknessParalysis: { location: { type: String } },
    contractures: { location: { type: String } },
    deformities: { location: { type: String } },
    fracture: { new: { type: Boolean }, splint: { type: Boolean } },
    ambulatoryDevices: { withPatient: { type: Boolean }, atHome: { type: Boolean } },
    limb: { cast: { type: String }, other: { type: String } },
    back: { sacralDimple: { type: Boolean }, kyphosis: { type: Boolean }, lordosis: { type: Boolean }, scoliosis: { type: Boolean }, other: { type: String } },
    joints: { mobile: { type: Boolean }, swelling: { type: Boolean }, tenderOrInflamedJoints: { type: Boolean } },
    spine: { inTowing: { type: Boolean }, notTowing: { type: Boolean }, bowType: { type: Boolean }, knockKnee: { type: Boolean }, limp: { type: Boolean }, knee: { type: Boolean } },
    others: { type: String },
  },
  others: { type: String },
}, { _id: false })

const MusculoskeletalSubSchema = new Schema({
  sensory: {
    fineTouch: { intact: { type: Boolean }, notIntact: { type: Boolean } },
    crudeTouch: { intact: { type: Boolean }, notIntact: { type: Boolean } },
    temperature: { intact: { type: Boolean }, notIntact: { type: Boolean } },
    position: { intact: { type: Boolean }, notIntact: { type: Boolean } },
    vibration: { intact: { type: Boolean }, notIntact: { type: Boolean } },
    pain: { intact: { type: Boolean }, notIntact: { type: Boolean } },
  },
  bulk: {
    upperR: { type: String },
    upperL: { type: String },
    lowerR: { type: String },
    lowerL: { type: String },
  },
  tone: {
    upperR: { type: String },
    upperL: { type: String },
    lowerR: { type: String },
    lowerL: { type: String },
  },
  power: {
    upperR: { type: String },
    upperL: { type: String },
    lowerR: { type: String },
    lowerL: { type: String },
  },
  reflexes: {
    biceps: { right: { type: String }, left: { type: String } },
    triceps: { right: { type: String }, left: { type: String } },
    supinator: { right: { type: String }, left: { type: String } },
    abdominal: { right: { type: String }, left: { type: String } },
    knee: { right: { type: String }, left: { type: String } },
    ankle: { right: { type: String }, left: { type: String } },
    plantar: { right: { type: String }, left: { type: String } },
    babinski: { right: { type: String }, left: { type: String } },
    clonus: { right: { type: String }, left: { type: String } },
  },
  motorFunction: {
    normal: { type: Boolean },
    involuntaryMovement: { type: Boolean },
    neckStiffness: { type: Boolean },
    kernigSign: { type: Boolean },
    brudzinskiSign: { type: Boolean },
    straightLegRaising: { type: Boolean },
    others: { type: String },
  },
  jointExamination: {
    swelling: { type: Boolean },
    tenderness: { type: Boolean },
    deformity: { type: Boolean },
    rangeOfMotion: { type: Boolean },
    crepitus: { type: Boolean },
    instability: { type: Boolean },
    details: { type: String },
  },
  spineExamination: {
    normalCurvature: { type: Boolean },
    kyphosis: { type: Boolean },
    lordosis: { type: Boolean },
    scoliosis: { type: Boolean },
    tenderness: { type: Boolean },
    rangeOfMotion: { type: Boolean },
    details: { type: String },
  },
  gait: {
    normal: { type: Boolean },
    antalgic: { type: Boolean },
    trendelenburg: { type: Boolean },
    ataxic: { type: Boolean },
    waddling: { type: Boolean },
    steppage: { type: Boolean },
  },
  others: { type: String },
}, { _id: false })

const GynecologicalObstetricSubSchema = new Schema({
  menstruating: {
    no: { type: Boolean },
    yes: { type: Boolean },
    ageAtMenarche: { type: String },
    lastMenstrualPeriod: { type: String },
  },
  menstrualCycle: {
    regular: { type: Boolean },
    irregular: { type: Boolean },
    duration: { type: String },
    contraceptiveNo: { type: Boolean },
    contraceptiveYes: { type: Boolean },
    contraceptiveType: { type: String },
  },
  menstrualLoss: {
    scanty: { type: Boolean },
    moderate: { type: Boolean },
    excessive: { type: Boolean },
    padsUsed: { type: String },
    papSmearFindings: { type: String },
  },
  dysmenorrhea: {
    beforeOnset: { type: Boolean },
    zeroToTwoDays: { type: Boolean },
    afterMenses: { type: Boolean },
  },
  dyspareunia: {
    superficial: { type: Boolean },
    deep: { type: Boolean },
  },
  gpa: {
    gravida: { type: String },
    para: { type: String },
    abortions: { type: String },
    lastBornChild: { type: String },
    livingChildren: { type: String },
    complications: { type: String },
  },
  menopause: {
    no: { type: Boolean },
    yes: { type: Boolean },
    age: { type: String },
  },
  skin: {
    rash: { type: Boolean },
    scar: { type: Boolean },
    diaphoretic: { type: Boolean },
    petechiae: { type: Boolean },
    ecchymosed: { type: Boolean },
    bruises: { type: Boolean },
    pressureSores: { type: Boolean },
    incisionsDrains: { type: Boolean },
    others: { type: String },
  },
  skinColor: {
    normal: { type: Boolean },
    pale: { type: Boolean },
    flushed: { type: Boolean },
    cyanotic: { type: Boolean },
    jaundiced: { type: Boolean },
    mottled: { type: Boolean },
    other: { type: String },
  },
  skinTurgor: {
    adequate: { type: Boolean },
    poor: { type: Boolean },
    good: { type: Boolean },
    moist: { type: Boolean },
    taut: { type: Boolean },
    other: { type: String },
  },
  hairScalp: {
    clean: { type: Boolean },
    lice: { type: Boolean },
    flakes: { type: Boolean },
    wound: { type: Boolean },
    lesion: { type: Boolean },
    ulcers: { type: Boolean },
    other: { type: String },
  },
  others: { type: String },
}, { _id: false })

// ─── Main Schema ────────────────────────────────────────────────────────────

const SYSTEM_TYPES = [
  'cardiovascular',
  'respiratory',
  'cns',
  'cns-b',
  'gastrointestinal',
  'hernia-rectal',
  'urogenital-musculoskeletal',
  'musculoskeletal',
  'gynecological-obstetric',
] as const

export type SystemType = (typeof SYSTEM_TYPES)[number]

const IpdSystemicExamSchema = new Schema({
  patientId: { type: Schema.Types.ObjectId, ref: 'Lab_Patient', required: true, index: true },
  encounterId: { type: Schema.Types.ObjectId, ref: 'Hospital_Encounter', required: true, index: true },

  systemType: {
    type: String,
    enum: SYSTEM_TYPES,
    required: true,
    index: true,
  },

  // Each system gets its OWN typed sub-schema
  // Mongoose minimize:true (default) strips empty objects, so only the active sub-schema is stored
  cardiovascular: { type: CardiovascularSubSchema },
  respiratory: { type: RespiratorySubSchema },
  cns: { type: CnsSubSchema },
  cnsB: { type: CnsBSubSchema },
  gastrointestinal: { type: GastrointestinalSubSchema },
  herniaRectal: { type: HerniaRectalSubSchema },
  urogenitalMusculoskeletal: { type: UrogenitalMusculoskeletalSubSchema },
  musculoskeletal: { type: MusculoskeletalSubSchema },
  gynecologicalObstetric: { type: GynecologicalObstetricSubSchema },

  notes: { type: String },
  doctorId: { type: Schema.Types.ObjectId, ref: 'Hospital_Doctor' },
  doctorName: { type: String },
  recordedAt: { type: Date, default: Date.now, index: true },
  recordedBy: { type: String },
  signed: { type: Boolean, default: false },
  signedAt: { type: Date },
  signature: { type: String },
}, { timestamps: true })

// Compound index for the most common query pattern
IpdSystemicExamSchema.index({ encounterId: 1, systemType: 1, recordedAt: -1 })

export const HospitalIpdSystemicExam = models.Hospital_IpdSystemicExam || model('Hospital_IpdSystemicExam', IpdSystemicExamSchema)

// ─── systemType → sub-schema field mapping ───────────────────────────────────
// Used by the controller to enforce that only the matching sub-schema is populated

export const SYSTEM_TYPE_TO_FIELD: Record<SystemType, string> = {
  'cardiovascular': 'cardiovascular',
  'respiratory': 'respiratory',
  'cns': 'cns',
  'cns-b': 'cnsB',
  'gastrointestinal': 'gastrointestinal',
  'hernia-rectal': 'herniaRectal',
  'urogenital-musculoskeletal': 'urogenitalMusculoskeletal',
  'musculoskeletal': 'musculoskeletal',
  'gynecological-obstetric': 'gynecologicalObstetric',
}

export const ALL_SYSTEM_FIELDS = Object.values(SYSTEM_TYPE_TO_FIELD)
