import { LabTest } from '../modules/lab/models/Test'
import { connectDB } from '../config/db'

export const hematologyTests = [
  // Complete Blood Count (CBC) Panel
  {
    name: 'Complete Blood Count (CBC)',
    price: 350,
    parameters: [
      {
        name: 'Hemoglobin (Hb)',
        unit: 'g/dL',
        normalRangeMale: '13.5-17.5',
        normalRangeFemale: '12.0-15.5',
        normalRangePediatric: '11.0-16.0 (varies by age)',
        criticalMin: 5.0,
        criticalMax: 20.0,
      },
      {
        name: 'Hematocrit (Hct)',
        unit: '%',
        normalRangeMale: '38.8-50.0',
        normalRangeFemale: '34.9-44.5',
        normalRangePediatric: '33-42 (varies by age)',
        criticalMin: 15.0,
        criticalMax: 60.0,
      },
      {
        name: 'Red Blood Cell Count (RBC)',
        unit: 'million/µL',
        normalRangeMale: '4.7-6.1',
        normalRangeFemale: '4.2-5.4',
        normalRangePediatric: '3.5-5.5 (varies by age)',
      },
      {
        name: 'White Blood Cell Count (WBC)',
        unit: '×10³/µL',
        normalRangeMale: '4.5-11.0',
        normalRangeFemale: '4.5-11.0',
        normalRangePediatric: '5.0-15.0 (varies by age)',
        criticalMin: 2.0,
        criticalMax: 30.0,
      },
      {
        name: 'Platelet Count',
        unit: '×10³/µL',
        normalRangeMale: '150-400',
        normalRangeFemale: '150-400',
        normalRangePediatric: '150-450',
        criticalMin: 50,
        criticalMax: 1000,
      },
      {
        name: 'Mean Corpuscular Volume (MCV)',
        unit: 'fL',
        normalRangeMale: '80-100',
        normalRangeFemale: '80-100',
        normalRangePediatric: '70-90 (varies by age)',
      },
      {
        name: 'Mean Corpuscular Hemoglobin (MCH)',
        unit: 'pg',
        normalRangeMale: '27-33',
        normalRangeFemale: '27-33',
        normalRangePediatric: '23-31 (varies by age)',
      },
      {
        name: 'Mean Corpuscular Hemoglobin Concentration (MCHC)',
        unit: 'g/dL',
        normalRangeMale: '32-36',
        normalRangeFemale: '32-36',
        normalRangePediatric: '32-36',
      },
      {
        name: 'Red Cell Distribution Width (RDW)',
        unit: '%',
        normalRangeMale: '11.5-14.5',
        normalRangeFemale: '11.5-14.5',
        normalRangePediatric: '11.5-14.5',
      },
      {
        name: 'Mean Platelet Volume (MPV)',
        unit: 'fL',
        normalRangeMale: '7.5-12.5',
        normalRangeFemale: '7.5-12.5',
        normalRangePediatric: '7.5-12.5',
      },
    ],
  },
  {
    name: 'CBC with Differential',
    price: 500,
    parameters: [
      {
        name: 'Hemoglobin (Hb)',
        unit: 'g/dL',
        normalRangeMale: '13.5-17.5',
        normalRangeFemale: '12.0-15.5',
        normalRangePediatric: '11.0-16.0 (varies by age)',
        criticalMin: 5.0,
        criticalMax: 20.0,
      },
      {
        name: 'Hematocrit (Hct)',
        unit: '%',
        normalRangeMale: '38.8-50.0',
        normalRangeFemale: '34.9-44.5',
        normalRangePediatric: '33-42 (varies by age)',
        criticalMin: 15.0,
        criticalMax: 60.0,
      },
      {
        name: 'Red Blood Cell Count (RBC)',
        unit: 'million/µL',
        normalRangeMale: '4.7-6.1',
        normalRangeFemale: '4.2-5.4',
        normalRangePediatric: '3.5-5.5 (varies by age)',
      },
      {
        name: 'White Blood Cell Count (WBC)',
        unit: '×10³/µL',
        normalRangeMale: '4.5-11.0',
        normalRangeFemale: '4.5-11.0',
        normalRangePediatric: '5.0-15.0 (varies by age)',
        criticalMin: 2.0,
        criticalMax: 30.0,
      },
      {
        name: 'Neutrophils',
        unit: '%',
        normalRangeMale: '40-70',
        normalRangeFemale: '40-70',
        normalRangePediatric: '30-60',
      },
      {
        name: 'Lymphocytes',
        unit: '%',
        normalRangeMale: '20-40',
        normalRangeFemale: '20-40',
        normalRangePediatric: '30-60',
      },
      {
        name: 'Monocytes',
        unit: '%',
        normalRangeMale: '2-10',
        normalRangeFemale: '2-10',
        normalRangePediatric: '2-10',
      },
      {
        name: 'Eosinophils',
        unit: '%',
        normalRangeMale: '0-6',
        normalRangeFemale: '0-6',
        normalRangePediatric: '0-6',
      },
      {
        name: 'Basophils',
        unit: '%',
        normalRangeMale: '0-2',
        normalRangeFemale: '0-2',
        normalRangePediatric: '0-2',
      },
      {
        name: 'Platelet Count',
        unit: '×10³/µL',
        normalRangeMale: '150-400',
        normalRangeFemale: '150-400',
        normalRangePediatric: '150-450',
        criticalMin: 50,
        criticalMax: 1000,
      },
      {
        name: 'Mean Corpuscular Volume (MCV)',
        unit: 'fL',
        normalRangeMale: '80-100',
        normalRangeFemale: '80-100',
        normalRangePediatric: '70-90 (varies by age)',
      },
      {
        name: 'Mean Corpuscular Hemoglobin (MCH)',
        unit: 'pg',
        normalRangeMale: '27-33',
        normalRangeFemale: '27-33',
        normalRangePediatric: '23-31 (varies by age)',
      },
      {
        name: 'Mean Corpuscular Hemoglobin Concentration (MCHC)',
        unit: 'g/dL',
        normalRangeMale: '32-36',
        normalRangeFemale: '32-36',
        normalRangePediatric: '32-36',
      },
      {
        name: 'Red Cell Distribution Width (RDW)',
        unit: '%',
        normalRangeMale: '11.5-14.5',
        normalRangeFemale: '11.5-14.5',
        normalRangePediatric: '11.5-14.5',
      },
    ],
  },
  // Individual Hematology Tests
  {
    name: 'Hemoglobin (Hb)',
    price: 100,
    parameter: 'Hemoglobin',
    unit: 'g/dL',
    normalRangeMale: '13.5-17.5',
    normalRangeFemale: '12.0-15.5',
    normalRangePediatric: '11.0-16.0 (varies by age)',
    criticalMin: 5.0,
    criticalMax: 20.0,
  },
  {
    name: 'Hematocrit (Hct)',
    price: 100,
    parameter: 'Hematocrit',
    unit: '%',
    normalRangeMale: '38.8-50.0',
    normalRangeFemale: '34.9-44.5',
    normalRangePediatric: '33-42 (varies by age)',
    criticalMin: 15.0,
    criticalMax: 60.0,
  },
  {
    name: 'Red Blood Cell Count',
    price: 100,
    parameter: 'RBC Count',
    unit: 'million/µL',
    normalRangeMale: '4.7-6.1',
    normalRangeFemale: '4.2-5.4',
    normalRangePediatric: '3.5-5.5 (varies by age)',
  },
  {
    name: 'White Blood Cell Count',
    price: 100,
    parameter: 'WBC Count',
    unit: '×10³/µL',
    normalRangeMale: '4.5-11.0',
    normalRangeFemale: '4.5-11.0',
    normalRangePediatric: '5.0-15.0 (varies by age)',
    criticalMin: 2.0,
    criticalMax: 30.0,
  },
  {
    name: 'Platelet Count',
    price: 150,
    parameter: 'Platelet Count',
    unit: '×10³/µL',
    normalRangeMale: '150-400',
    normalRangeFemale: '150-400',
    normalRangePediatric: '150-450',
    criticalMin: 50,
    criticalMax: 1000,
  },
  {
    name: 'Peripheral Blood Smear',
    price: 200,
    parameters: [
      {
        name: 'RBC Morphology',
        unit: 'Report',
        normalRangeMale: 'Normocytic, Normochromic',
        normalRangeFemale: 'Normocytic, Normochromic',
        normalRangePediatric: 'Normocytic, Normochromic',
      },
      {
        name: 'WBC Morphology',
        unit: 'Report',
        normalRangeMale: 'Normal morphology',
        normalRangeFemale: 'Normal morphology',
        normalRangePediatric: 'Normal morphology',
      },
      {
        name: 'Platelet Morphology',
        unit: 'Report',
        normalRangeMale: 'Adequate, normal morphology',
        normalRangeFemale: 'Adequate, normal morphology',
        normalRangePediatric: 'Adequate, normal morphology',
      },
    ],
  },
  {
    name: 'Reticulocyte Count',
    price: 200,
    parameter: 'Reticulocyte Count',
    unit: '%',
    normalRangeMale: '0.5-2.5',
    normalRangeFemale: '0.5-2.5',
    normalRangePediatric: '0.5-2.0',
  },
  {
    name: 'Erythrocyte Sedimentation Rate (ESR)',
    price: 150,
    parameter: 'ESR',
    unit: 'mm/hr',
    normalRangeMale: '0-15',
    normalRangeFemale: '0-20',
    normalRangePediatric: '0-10',
  },
  {
    name: 'ESR (Westergren Method)',
    price: 150,
    parameter: 'ESR',
    unit: 'mm/hr',
    normalRangeMale: '0-15',
    normalRangeFemale: '0-20',
    normalRangePediatric: '0-10',
  },
  // Coagulation Studies
  {
    name: 'Bleeding Time',
    price: 150,
    parameter: 'Bleeding Time',
    unit: 'minutes',
    normalRangeMale: '1-7',
    normalRangeFemale: '1-7',
    normalRangePediatric: '1-7',
  },
  {
    name: 'Clotting Time',
    price: 150,
    parameter: 'Clotting Time',
    unit: 'minutes',
    normalRangeMale: '4-10',
    normalRangeFemale: '4-10',
    normalRangePediatric: '4-10',
  },
  {
    name: 'Prothrombin Time (PT)',
    price: 250,
    parameter: 'PT',
    unit: 'seconds',
    normalRangeMale: '11-15',
    normalRangeFemale: '11-15',
    normalRangePediatric: '11-15',
  },
  {
    name: 'PT/INR',
    price: 300,
    parameters: [
      {
        name: 'Prothrombin Time (PT)',
        unit: 'seconds',
        normalRangeMale: '11-15',
        normalRangeFemale: '11-15',
        normalRangePediatric: '11-15',
      },
      {
        name: 'International Normalized Ratio (INR)',
        unit: 'ratio',
        normalRangeMale: '0.9-1.3',
        normalRangeFemale: '0.9-1.3',
        normalRangePediatric: '0.9-1.3',
        criticalMax: 5.0,
      },
    ],
  },
  {
    name: 'Activated Partial Thromboplastin Time (APTT)',
    price: 300,
    parameter: 'APTT',
    unit: 'seconds',
    normalRangeMale: '25-35',
    normalRangeFemale: '25-35',
    normalRangePediatric: '25-35',
  },
  {
    name: 'Thrombin Time (TT)',
    price: 300,
    parameter: 'Thrombin Time',
    unit: 'seconds',
    normalRangeMale: '14-21',
    normalRangeFemale: '14-21',
    normalRangePediatric: '14-21',
  },
  {
    name: 'Fibrinogen Level',
    price: 400,
    parameter: 'Fibrinogen',
    unit: 'mg/dL',
    normalRangeMale: '200-400',
    normalRangeFemale: '200-400',
    normalRangePediatric: '200-400',
    criticalMin: 100,
  },
  {
    name: 'D-Dimer',
    price: 600,
    parameter: 'D-Dimer',
    unit: 'ng/mL FEU',
    normalRangeMale: '<500',
    normalRangeFemale: '<500',
    normalRangePediatric: '<500',
  },
  {
    name: 'Fibrin Degradation Products (FDP)',
    price: 500,
    parameter: 'FDP',
    unit: 'µg/mL',
    normalRangeMale: '<5',
    normalRangeFemale: '<5',
    normalRangePediatric: '<5',
  },
  // Hemoglobin Variants and Hemoglobinopathy
  {
    name: 'Hemoglobin Electrophoresis',
    price: 800,
    parameters: [
      {
        name: 'Hemoglobin A (HbA)',
        unit: '%',
        normalRangeMale: '95-98',
        normalRangeFemale: '95-98',
        normalRangePediatric: '95-98',
      },
      {
        name: 'Hemoglobin A2 (HbA2)',
        unit: '%',
        normalRangeMale: '1.5-3.5',
        normalRangeFemale: '1.5-3.5',
        normalRangePediatric: '1.5-3.5',
      },
      {
        name: 'Hemoglobin F (HbF)',
        unit: '%',
        normalRangeMale: '<2',
        normalRangeFemale: '<2',
        normalRangePediatric: '<2 (adults); higher in infants',
      },
    ],
  },
  {
    name: 'HbA1c (Glycated Hemoglobin)',
    price: 400,
    parameter: 'HbA1c',
    unit: '%',
    normalRangeMale: '4.0-5.6',
    normalRangeFemale: '4.0-5.6',
    normalRangePediatric: '4.0-5.6',
  },
  {
    name: 'HbA1c with eAG',
    price: 500,
    parameters: [
      {
        name: 'HbA1c',
        unit: '%',
        normalRangeMale: '4.0-5.6',
        normalRangeFemale: '4.0-5.6',
        normalRangePediatric: '4.0-5.6',
      },
      {
        name: 'Estimated Average Glucose (eAG)',
        unit: 'mg/dL',
        normalRangeMale: '70-126',
        normalRangeFemale: '70-126',
        normalRangePediatric: '70-126',
        formula: 'eAG = (28.7 × HbA1c) - 46.7',
        dependsOn: ['HbA1c'],
      },
    ],
  },
  {
    name: 'Sickle Cell Test',
    price: 300,
    parameter: 'Sickle Cell Screen',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'G6PD Deficiency Test',
    price: 500,
    parameter: 'G6PD Activity',
    unit: 'U/g Hb',
    normalRangeMale: '4.6-13.5',
    normalRangeFemale: '4.6-13.5',
    normalRangePediatric: '4.6-13.5',
  },
  // Iron Studies
  {
    name: 'Serum Iron',
    price: 300,
    parameter: 'Iron',
    unit: 'µg/dL',
    normalRangeMale: '60-170',
    normalRangeFemale: '50-150',
    normalRangePediatric: '50-150',
  },
  {
    name: 'Total Iron Binding Capacity (TIBC)',
    price: 350,
    parameter: 'TIBC',
    unit: 'µg/dL',
    normalRangeMale: '250-370',
    normalRangeFemale: '250-370',
    normalRangePediatric: '250-400',
  },
  {
    name: 'Serum Ferritin',
    price: 400,
    parameter: 'Ferritin',
    unit: 'ng/mL',
    normalRangeMale: '30-400',
    normalRangeFemale: '13-150',
    normalRangePediatric: '7-140',
  },
  {
    name: 'Iron Studies Panel',
    price: 900,
    parameters: [
      {
        name: 'Serum Iron',
        unit: 'µg/dL',
        normalRangeMale: '60-170',
        normalRangeFemale: '50-150',
        normalRangePediatric: '50-150',
      },
      {
        name: 'Total Iron Binding Capacity (TIBC)',
        unit: 'µg/dL',
        normalRangeMale: '250-370',
        normalRangeFemale: '250-370',
        normalRangePediatric: '250-400',
      },
      {
        name: 'Transferrin Saturation',
        unit: '%',
        normalRangeMale: '20-50',
        normalRangeFemale: '15-50',
        normalRangePediatric: '20-50',
        formula: 'Transferrin Saturation = (Serum Iron / TIBC) × 100',
        dependsOn: ['Serum Iron', 'Total Iron Binding Capacity (TIBC)'],
      },
      {
        name: 'Serum Ferritin',
        unit: 'ng/mL',
        normalRangeMale: '30-400',
        normalRangeFemale: '13-150',
        normalRangePediatric: '7-140',
      },
    ],
  },
  {
    name: 'Transferrin Saturation',
    price: 500,
    parameter: 'Transferrin Saturation',
    unit: '%',
    normalRangeMale: '20-50',
    normalRangeFemale: '15-50',
    normalRangePediatric: '20-50',
  },
  // Vitamin B12 and Folate
  {
    name: 'Vitamin B12',
    price: 500,
    parameter: 'Vitamin B12',
    unit: 'pg/mL',
    normalRangeMale: '200-900',
    normalRangeFemale: '200-900',
    normalRangePediatric: '200-900',
  },
  {
    name: 'Serum Folate',
    price: 400,
    parameter: 'Folate',
    unit: 'ng/mL',
    normalRangeMale: '3.1-20.5',
    normalRangeFemale: '3.1-20.5',
    normalRangePediatric: '3.1-20.5',
  },
  {
    name: 'RBC Folate',
    price: 500,
    parameter: 'RBC Folate',
    unit: 'ng/mL RBC',
    normalRangeMale: '140-628',
    normalRangeFemale: '140-628',
    normalRangePediatric: '140-628',
  },
  {
    name: 'Methylmalonic Acid (MMA)',
    price: 800,
    parameter: 'MMA',
    unit: 'nmol/L',
    normalRangeMale: '70-270',
    normalRangeFemale: '70-270',
    normalRangePediatric: '70-270',
  },
  // Bone Marrow and Special Hematology
  {
    name: 'Bone Marrow Aspiration',
    price: 1500,
    parameters: [
      {
        name: 'Cellularity',
        unit: '%',
        normalRangeMale: '40-60',
        normalRangeFemale: '40-60',
        normalRangePediatric: '70-80',
      },
      {
        name: 'Myeloid:Erythroid Ratio',
        unit: 'ratio',
        normalRangeMale: '2:1 to 4:1',
        normalRangeFemale: '2:1 to 4:1',
        normalRangePediatric: '2:1 to 4:1',
      },
      {
        name: 'Megakaryocytes',
        unit: 'Report',
        normalRangeMale: 'Adequate',
        normalRangeFemale: 'Adequate',
        normalRangePediatric: 'Adequate',
      },
    ],
  },
  {
    name: 'Bone Marrow Biopsy',
    price: 2000,
    parameter: 'Bone Marrow Biopsy',
    unit: 'Report',
    normalRangeMale: 'Normal cellularity and architecture',
    normalRangeFemale: 'Normal cellularity and architecture',
    normalRangePediatric: 'Normal cellularity and architecture',
  },
  // Blood Grouping
  {
    name: 'Blood Group (ABO & Rh)',
    price: 200,
    parameters: [
      {
        name: 'ABO Group',
        unit: 'Report',
        normalRangeMale: 'A, B, AB, or O',
        normalRangeFemale: 'A, B, AB, or O',
        normalRangePediatric: 'A, B, AB, or O',
      },
      {
        name: 'Rh Factor',
        unit: 'Report',
        normalRangeMale: 'Positive or Negative',
        normalRangeFemale: 'Positive or Negative',
        normalRangePediatric: 'Positive or Negative',
      },
    ],
  },
  {
    name: 'Rh Antibody Titre',
    price: 400,
    parameter: 'Anti-D Antibody Titre',
    unit: 'Titre',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Direct Coombs Test',
    price: 400,
    parameter: 'Direct Coombs Test',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Indirect Coombs Test',
    price: 400,
    parameter: 'Indirect Coombs Test',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Cross Match (Major)',
    price: 300,
    parameter: 'Cross Match',
    unit: 'Report',
    normalRangeMale: 'Compatible',
    normalRangeFemale: 'Compatible',
    normalRangePediatric: 'Compatible',
  },
  {
    name: 'Cross Match (Minor)',
    price: 300,
    parameter: 'Cross Match',
    unit: 'Report',
    normalRangeMale: 'Compatible',
    normalRangeFemale: 'Compatible',
    normalRangePediatric: 'Compatible',
  },
  // Osmotic Fragility
  {
    name: 'Osmotic Fragility Test',
    price: 500,
    parameter: 'Osmotic Fragility',
    unit: '% hemolysis',
    normalRangeMale: 'Normal at 0.45-0.35% NaCl',
    normalRangeFemale: 'Normal at 0.45-0.35% NaCl',
    normalRangePediatric: 'Normal at 0.45-0.35% NaCl',
  },
  // Special Hematology Tests
  {
    name: 'Ham\'s Test (Acidified Serum Lysis Test)',
    price: 600,
    parameter: 'Ham\'s Test',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Sucrose Hemolysis Test',
    price: 500,
    parameter: 'Sucrose Hemolysis',
    unit: '%',
    normalRangeMale: '<5',
    normalRangeFemale: '<5',
    normalRangePediatric: '<5',
  },
  {
    name: 'Cold Agglutinins',
    price: 500,
    parameter: 'Cold Agglutinins Titre',
    unit: 'Titre',
    normalRangeMale: '<1:32',
    normalRangeFemale: '<1:32',
    normalRangePediatric: '<1:32',
  },
  {
    name: 'Haptoglobin',
    price: 600,
    parameter: 'Haptoglobin',
    unit: 'mg/dL',
    normalRangeMale: '30-200',
    normalRangeFemale: '30-200',
    normalRangePediatric: '30-200',
  },
  {
    name: 'Plasma Hemoglobin',
    price: 400,
    parameter: 'Plasma Hemoglobin',
    unit: 'mg/dL',
    normalRangeMale: '<5',
    normalRangeFemale: '<5',
    normalRangePediatric: '<5',
  },
  {
    name: 'Serum Transferrin',
    price: 400,
    parameter: 'Transferrin',
    unit: 'mg/dL',
    normalRangeMale: '200-360',
    normalRangeFemale: '200-360',
    normalRangePediatric: '200-360',
  },
  // More Coagulation Tests
  {
    name: 'Protein C Activity',
    price: 800,
    parameter: 'Protein C',
    unit: '%',
    normalRangeMale: '70-140',
    normalRangeFemale: '70-140',
    normalRangePediatric: '70-140',
  },
  {
    name: 'Protein S Activity',
    price: 800,
    parameter: 'Protein S',
    unit: '%',
    normalRangeMale: '65-140',
    normalRangeFemale: '50-140',
    normalRangePediatric: '50-140',
  },
  {
    name: 'Antithrombin III Activity',
    price: 800,
    parameter: 'Antithrombin III',
    unit: '%',
    normalRangeMale: '80-120',
    normalRangeFemale: '80-120',
    normalRangePediatric: '80-120',
  },
  {
    name: 'Lupus Anticoagulant Screen',
    price: 1000,
    parameter: 'Lupus Anticoagulant',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Factor VIII Activity',
    price: 1200,
    parameter: 'Factor VIII',
    unit: '%',
    normalRangeMale: '50-150',
    normalRangeFemale: '50-150',
    normalRangePediatric: '50-150',
  },
  {
    name: 'Factor IX Activity',
    price: 1200,
    parameter: 'Factor IX',
    unit: '%',
    normalRangeMale: '50-150',
    normalRangeFemale: '50-150',
    normalRangePediatric: '50-150',
  },
  {
    name: 'Factor V Activity',
    price: 1200,
    parameter: 'Factor V',
    unit: '%',
    normalRangeMale: '50-150',
    normalRangeFemale: '50-150',
    normalRangePediatric: '50-150',
  },
  {
    name: 'Factor VII Activity',
    price: 1200,
    parameter: 'Factor VII',
    unit: '%',
    normalRangeMale: '50-150',
    normalRangeFemale: '50-150',
    normalRangePediatric: '50-150',
  },
  {
    name: 'Factor X Activity',
    price: 1200,
    parameter: 'Factor X',
    unit: '%',
    normalRangeMale: '50-150',
    normalRangeFemale: '50-150',
    normalRangePediatric: '50-150',
  },
  {
    name: 'Factor XI Activity',
    price: 1200,
    parameter: 'Factor XI',
    unit: '%',
    normalRangeMale: '50-150',
    normalRangeFemale: '50-150',
    normalRangePediatric: '50-150',
  },
  {
    name: 'Factor XII Activity',
    price: 1200,
    parameter: 'Factor XII',
    unit: '%',
    normalRangeMale: '50-150',
    normalRangeFemale: '50-150',
    normalRangePediatric: '50-150',
  },
  {
    name: 'Factor XIII Activity',
    price: 1200,
    parameter: 'Factor XIII',
    unit: '%',
    normalRangeMale: '50-150',
    normalRangeFemale: '50-150',
    normalRangePediatric: '50-150',
  },
  {
    name: 'Activated Protein C Resistance (APCR)',
    price: 800,
    parameter: 'APCR Ratio',
    unit: 'ratio',
    normalRangeMale: '>2.0',
    normalRangeFemale: '>2.0',
    normalRangePediatric: '>2.0',
  },
  // Additional CBC Parameters
  {
    name: 'Nucleated RBC Count (NRBC)',
    price: 200,
    parameter: 'NRBC',
    unit: '/100 WBC',
    normalRangeMale: '0',
    normalRangeFemale: '0',
    normalRangePediatric: '0',
  },
  {
    name: 'Absolute Neutrophil Count (ANC)',
    price: 200,
    parameter: 'ANC',
    unit: '×10³/µL',
    normalRangeMale: '1.5-8.0',
    normalRangeFemale: '1.5-8.0',
    normalRangePediatric: '1.5-8.0',
    criticalMin: 0.5,
  },
  {
    name: 'Absolute Lymphocyte Count (ALC)',
    price: 200,
    parameter: 'ALC',
    unit: '×10³/µL',
    normalRangeMale: '1.0-4.0',
    normalRangeFemale: '1.0-4.0',
    normalRangePediatric: '1.5-5.0',
  },
  {
    name: 'Absolute Eosinophil Count',
    price: 200,
    parameter: 'AEC',
    unit: '×10³/µL',
    normalRangeMale: '0.0-0.5',
    normalRangeFemale: '0.0-0.5',
    normalRangePediatric: '0.0-0.5',
  },
  {
    name: 'Absolute Monocyte Count',
    price: 200,
    parameter: 'AMC',
    unit: '×10³/µL',
    normalRangeMale: '0.2-0.8',
    normalRangeFemale: '0.2-0.8',
    normalRangePediatric: '0.2-0.8',
  },
  {
    name: 'Absolute Basophil Count',
    price: 200,
    parameter: 'ABC',
    unit: '×10³/µL',
    normalRangeMale: '0.0-0.2',
    normalRangeFemale: '0.0-0.2',
    normalRangePediatric: '0.0-0.2',
  },
  // More Special Tests
  {
    name: 'Heinz Body Preparation',
    price: 300,
    parameter: 'Heinz Bodies',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Splenectomy Effect Test',
    price: 400,
    parameter: 'Howell-Jolly Bodies',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Plasma Viscosity',
    price: 300,
    parameter: 'Plasma Viscosity',
    unit: 'mPa.s',
    normalRangeMale: '1.50-1.72',
    normalRangeFemale: '1.50-1.72',
    normalRangePediatric: '1.50-1.72',
  },
  {
    name: 'Beta Thalassemia Screening',
    price: 600,
    parameters: [
      {
        name: 'HbA2 Level',
        unit: '%',
        normalRangeMale: '1.5-3.5',
        normalRangeFemale: '1.5-3.5',
        normalRangePediatric: '1.5-3.5',
      },
      {
        name: 'HbF Level',
        unit: '%',
        normalRangeMale: '<2',
        normalRangeFemale: '<2',
        normalRangePediatric: '<2',
      },
      {
        name: 'MCV',
        unit: 'fL',
        normalRangeMale: '80-100',
        normalRangeFemale: '80-100',
        normalRangePediatric: '70-90',
      },
      {
        name: 'Mentzer Index',
        unit: 'ratio',
        normalRangeMale: '>13',
        normalRangeFemale: '>13',
        normalRangePediatric: '>13',
        formula: 'Mentzer Index = MCV / RBC Count',
        dependsOn: ['MCV', 'RBC Count'],
      },
    ],
  },
  {
    name: 'Alpha Thalassemia Screening',
    price: 800,
    parameters: [
      {
        name: 'HbH Inclusion Bodies',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'MCV',
        unit: 'fL',
        normalRangeMale: '80-100',
        normalRangeFemale: '80-100',
        normalRangePediatric: '70-90',
      },
    ],
  },
]

export async function seedHematologyTests() {
  let created = 0
  let updated = 0
  
  for (const test of hematologyTests) {
    const res = await LabTest.updateOne(
      { name: test.name },
      { $set: test },
      { upsert: true }
    )
    if ((res as any).upsertedId || (res as any).upsertedCount) created++
    else if ((res as any).modifiedCount) updated++
  }
  
  return { total: hematologyTests.length, created, updated }
}
