import { LabTest } from '../modules/lab/models/Test'

export const chemistryTests = [
  // Kidney Function Tests (Renal Profile)
  {
    name: 'Renal Function Test (RFT)',
    price: 600,
    parameters: [
      {
        name: 'Blood Urea',
        unit: 'mg/dL',
        normalRangeMale: '7-20',
        normalRangeFemale: '7-20',
        normalRangePediatric: '5-18',
        criticalMax: 100,
      },
      {
        name: 'Serum Creatinine',
        unit: 'mg/dL',
        normalRangeMale: '0.7-1.3',
        normalRangeFemale: '0.6-1.1',
        normalRangePediatric: '0.3-0.7',
        criticalMax: 10.0,
      },
      {
        name: 'Blood Urea Nitrogen (BUN)',
        unit: 'mg/dL',
        normalRangeMale: '7-20',
        normalRangeFemale: '7-20',
        normalRangePediatric: '5-18',
        criticalMax: 100,
      },
      {
        name: 'Uric Acid',
        unit: 'mg/dL',
        normalRangeMale: '3.4-7.0',
        normalRangeFemale: '2.4-6.0',
        normalRangePediatric: '2.0-5.5',
        criticalMax: 12.0,
      },
    ],
  },
  {
    name: 'Kidney Function Test (KFT) Comprehensive',
    price: 800,
    parameters: [
      {
        name: 'Blood Urea',
        unit: 'mg/dL',
        normalRangeMale: '7-20',
        normalRangeFemale: '7-20',
        normalRangePediatric: '5-18',
        criticalMax: 100,
      },
      {
        name: 'Serum Creatinine',
        unit: 'mg/dL',
        normalRangeMale: '0.7-1.3',
        normalRangeFemale: '0.6-1.1',
        normalRangePediatric: '0.3-0.7',
        criticalMax: 10.0,
      },
      {
        name: 'BUN/Creatinine Ratio',
        unit: 'ratio',
        normalRangeMale: '10:1 to 20:1',
        normalRangeFemale: '10:1 to 20:1',
        normalRangePediatric: '10:1 to 20:1',
        formula: 'BUN/Creatinine Ratio = BUN / Creatinine',
        dependsOn: ['Blood Urea Nitrogen (BUN)', 'Serum Creatinine'],
      },
      {
        name: 'Uric Acid',
        unit: 'mg/dL',
        normalRangeMale: '3.4-7.0',
        normalRangeFemale: '2.4-6.0',
        normalRangePediatric: '2.0-5.5',
        criticalMax: 12.0,
      },
      {
        name: 'eGFR (Estimated Glomerular Filtration Rate)',
        unit: 'mL/min/1.73m²',
        normalRangeMale: '>90',
        normalRangeFemale: '>90',
        normalRangePediatric: '>90',
        formula: 'eGFR = 186 × (Creatinine)^-1.154 × (Age)^-0.203 × (0.742 if female)',
        dependsOn: ['Serum Creatinine'],
      },
      {
        name: 'Sodium (Na)',
        unit: 'mmol/L',
        normalRangeMale: '136-145',
        normalRangeFemale: '136-145',
        normalRangePediatric: '135-145',
        criticalMin: 120,
        criticalMax: 160,
      },
      {
        name: 'Potassium (K)',
        unit: 'mmol/L',
        normalRangeMale: '3.5-5.0',
        normalRangeFemale: '3.5-5.0',
        normalRangePediatric: '3.5-5.5',
        criticalMin: 2.5,
        criticalMax: 6.0,
      },
      {
        name: 'Chloride (Cl)',
        unit: 'mmol/L',
        normalRangeMale: '98-107',
        normalRangeFemale: '98-107',
        normalRangePediatric: '98-107',
      },
    ],
  },
  {
    name: 'Serum Creatinine',
    price: 150,
    parameter: 'Creatinine',
    unit: 'mg/dL',
    normalRangeMale: '0.7-1.3',
    normalRangeFemale: '0.6-1.1',
    normalRangePediatric: '0.3-0.7',
    criticalMax: 10.0,
  },
  {
    name: 'Blood Urea',
    price: 150,
    parameter: 'Urea',
    unit: 'mg/dL',
    normalRangeMale: '7-20',
    normalRangeFemale: '7-20',
    normalRangePediatric: '5-18',
    criticalMax: 100,
  },
  {
    name: 'Blood Urea Nitrogen (BUN)',
    price: 150,
    parameter: 'BUN',
    unit: 'mg/dL',
    normalRangeMale: '7-20',
    normalRangeFemale: '7-20',
    normalRangePediatric: '5-18',
  },
  {
    name: 'Serum Uric Acid',
    price: 200,
    parameter: 'Uric Acid',
    unit: 'mg/dL',
    normalRangeMale: '3.4-7.0',
    normalRangeFemale: '2.4-6.0',
    normalRangePediatric: '2.0-5.5',
  },
  {
    name: '24-Hour Urine Protein',
    price: 300,
    parameter: 'Total Protein',
    unit: 'mg/24hr',
    normalRangeMale: '<150',
    normalRangeFemale: '<150',
    normalRangePediatric: '<150',
  },
  {
    name: 'Creatinine Clearance',
    price: 400,
    parameters: [
      {
        name: 'Urine Creatinine',
        unit: 'mg/dL',
        normalRangeMale: 'Varies',
        normalRangeFemale: 'Varies',
        normalRangePediatric: 'Varies',
      },
      {
        name: 'Serum Creatinine',
        unit: 'mg/dL',
        normalRangeMale: '0.7-1.3',
        normalRangeFemale: '0.6-1.1',
        normalRangePediatric: '0.3-0.7',
      },
      {
        name: 'Creatinine Clearance',
        unit: 'mL/min',
        normalRangeMale: '97-137',
        normalRangeFemale: '88-128',
        normalRangePediatric: '90-140',
        formula: 'Ccr = (Urine Cr × Urine Volume) / (Serum Cr × 1440)',
        dependsOn: ['Urine Creatinine', 'Serum Creatinine'],
      },
    ],
  },
  {
    name: 'Microalbumin/Creatinine Ratio',
    price: 400,
    parameters: [
      {
        name: 'Microalbumin',
        unit: 'mg/L',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
      {
        name: 'Urine Creatinine',
        unit: 'mg/dL',
        normalRangeMale: 'Varies',
        normalRangeFemale: 'Varies',
        normalRangePediatric: 'Varies',
      },
      {
        name: 'Albumin/Creatinine Ratio (ACR)',
        unit: 'mg/g',
        normalRangeMale: '<30',
        normalRangeFemale: '<30',
        normalRangePediatric: '<30',
        formula: 'ACR = (Microalbumin in mg/L) / (Creatinine in mg/dL) × 1000',
        dependsOn: ['Microalbumin', 'Urine Creatinine'],
      },
    ],
  },
  {
    name: 'Cystatin C',
    price: 600,
    parameter: 'Cystatin C',
    unit: 'mg/L',
    normalRangeMale: '0.51-1.09',
    normalRangeFemale: '0.51-1.09',
    normalRangePediatric: '0.51-1.09',
  },
  // Liver Function Tests
  {
    name: 'Liver Function Test (LFT)',
    price: 600,
    parameters: [
      {
        name: 'Total Bilirubin',
        unit: 'mg/dL',
        normalRangeMale: '0.3-1.2',
        normalRangeFemale: '0.3-1.2',
        normalRangePediatric: '0.3-1.2',
        criticalMax: 15.0,
      },
      {
        name: 'Direct Bilirubin (Conjugated)',
        unit: 'mg/dL',
        normalRangeMale: '0.0-0.3',
        normalRangeFemale: '0.0-0.3',
        normalRangePediatric: '0.0-0.3',
      },
      {
        name: 'Indirect Bilirubin (Unconjugated)',
        unit: 'mg/dL',
        normalRangeMale: '0.2-0.8',
        normalRangeFemale: '0.2-0.8',
        normalRangePediatric: '0.2-0.8',
        formula: 'Indirect Bilirubin = Total Bilirubin - Direct Bilirubin',
        dependsOn: ['Total Bilirubin', 'Direct Bilirubin (Conjugated)'],
      },
      {
        name: 'SGPT (ALT)',
        unit: 'U/L',
        normalRangeMale: '7-56',
        normalRangeFemale: '7-56',
        normalRangePediatric: '10-40',
      },
      {
        name: 'SGOT (AST)',
        unit: 'U/L',
        normalRangeMale: '10-40',
        normalRangeFemale: '10-40',
        normalRangePediatric: '15-55',
      },
      {
        name: 'Alkaline Phosphatase (ALP)',
        unit: 'U/L',
        normalRangeMale: '44-147',
        normalRangeFemale: '44-147',
        normalRangePediatric: '100-400',
      },
      {
        name: 'Gamma Glutamyl Transferase (GGT)',
        unit: 'U/L',
        normalRangeMale: '9-50',
        normalRangeFemale: '9-50',
        normalRangePediatric: '5-25',
      },
      {
        name: 'Total Protein',
        unit: 'g/dL',
        normalRangeMale: '6.0-8.3',
        normalRangeFemale: '6.0-8.3',
        normalRangePediatric: '6.0-8.0',
      },
      {
        name: 'Albumin',
        unit: 'g/dL',
        normalRangeMale: '3.5-5.5',
        normalRangeFemale: '3.5-5.5',
        normalRangePediatric: '3.5-5.5',
      },
      {
        name: 'Globulin',
        unit: 'g/dL',
        normalRangeMale: '2.0-3.5',
        normalRangeFemale: '2.0-3.5',
        normalRangePediatric: '2.0-3.5',
        formula: 'Globulin = Total Protein - Albumin',
        dependsOn: ['Total Protein', 'Albumin'],
      },
      {
        name: 'A/G Ratio',
        unit: 'ratio',
        normalRangeMale: '1.0-2.2',
        normalRangeFemale: '1.0-2.2',
        normalRangePediatric: '1.0-2.2',
        formula: 'A/G Ratio = Albumin / Globulin',
        dependsOn: ['Albumin', 'Globulin'],
      },
    ],
  },
  {
    name: 'Serum Bilirubin (Total)',
    price: 150,
    parameter: 'Total Bilirubin',
    unit: 'mg/dL',
    normalRangeMale: '0.3-1.2',
    normalRangeFemale: '0.3-1.2',
    normalRangePediatric: '0.3-1.2',
    criticalMax: 15.0,
  },
  {
    name: 'Serum Bilirubin (Direct)',
    price: 150,
    parameter: 'Direct Bilirubin',
    unit: 'mg/dL',
    normalRangeMale: '0.0-0.3',
    normalRangeFemale: '0.0-0.3',
    normalRangePediatric: '0.0-0.3',
  },
  {
    name: 'SGPT (ALT)',
    price: 150,
    parameter: 'ALT',
    unit: 'U/L',
    normalRangeMale: '7-56',
    normalRangeFemale: '7-56',
    normalRangePediatric: '10-40',
  },
  {
    name: 'SGOT (AST)',
    price: 150,
    parameter: 'AST',
    unit: 'U/L',
    normalRangeMale: '10-40',
    normalRangeFemale: '10-40',
    normalRangePediatric: '15-55',
  },
  {
    name: 'Alkaline Phosphatase (ALP)',
    price: 150,
    parameter: 'ALP',
    unit: 'U/L',
    normalRangeMale: '44-147',
    normalRangeFemale: '44-147',
    normalRangePediatric: '100-400',
  },
  {
    name: 'Gamma Glutamyl Transferase (GGT)',
    price: 200,
    parameter: 'GGT',
    unit: 'U/L',
    normalRangeMale: '9-50',
    normalRangeFemale: '9-50',
    normalRangePediatric: '5-25',
  },
  {
    name: 'Serum Total Protein',
    price: 150,
    parameter: 'Total Protein',
    unit: 'g/dL',
    normalRangeMale: '6.0-8.3',
    normalRangeFemale: '6.0-8.3',
    normalRangePediatric: '6.0-8.0',
  },
  {
    name: 'Serum Albumin',
    price: 150,
    parameter: 'Albumin',
    unit: 'g/dL',
    normalRangeMale: '3.5-5.5',
    normalRangeFemale: '3.5-5.5',
    normalRangePediatric: '3.5-5.5',
  },
  {
    name: 'Protein Electrophoresis (Serum)',
    price: 800,
    parameters: [
      {
        name: 'Albumin',
        unit: 'g/dL',
        normalRangeMale: '3.5-5.5',
        normalRangeFemale: '3.5-5.5',
        normalRangePediatric: '3.5-5.5',
      },
      {
        name: 'Alpha-1 Globulin',
        unit: 'g/dL',
        normalRangeMale: '0.1-0.4',
        normalRangeFemale: '0.1-0.4',
        normalRangePediatric: '0.1-0.4',
      },
      {
        name: 'Alpha-2 Globulin',
        unit: 'g/dL',
        normalRangeMale: '0.5-1.0',
        normalRangeFemale: '0.5-1.0',
        normalRangePediatric: '0.5-1.0',
      },
      {
        name: 'Beta Globulin',
        unit: 'g/dL',
        normalRangeMale: '0.6-1.2',
        normalRangeFemale: '0.6-1.2',
        normalRangePediatric: '0.6-1.2',
      },
      {
        name: 'Gamma Globulin',
        unit: 'g/dL',
        normalRangeMale: '0.7-1.6',
        normalRangeFemale: '0.7-1.6',
        normalRangePediatric: '0.7-1.6',
      },
    ],
  },
  // Lipid Profile
  {
    name: 'Lipid Profile',
    price: 500,
    parameters: [
      {
        name: 'Total Cholesterol',
        unit: 'mg/dL',
        normalRangeMale: '<200',
        normalRangeFemale: '<200',
        normalRangePediatric: '<170',
      },
      {
        name: 'Triglycerides',
        unit: 'mg/dL',
        normalRangeMale: '<150',
        normalRangeFemale: '<150',
        normalRangePediatric: '<100',
      },
      {
        name: 'HDL Cholesterol',
        unit: 'mg/dL',
        normalRangeMale: '>40',
        normalRangeFemale: '>50',
        normalRangePediatric: '>45',
      },
      {
        name: 'LDL Cholesterol (Calculated)',
        unit: 'mg/dL',
        normalRangeMale: '<100',
        normalRangeFemale: '<100',
        normalRangePediatric: '<110',
        formula: 'LDL = Total Cholesterol - HDL - (Triglycerides / 5)',
        dependsOn: ['Total Cholesterol', 'HDL Cholesterol', 'Triglycerides'],
      },
      {
        name: 'VLDL Cholesterol',
        unit: 'mg/dL',
        normalRangeMale: '5-40',
        normalRangeFemale: '5-40',
        normalRangePediatric: '5-40',
        formula: 'VLDL = Triglycerides / 5',
        dependsOn: ['Triglycerides'],
      },
      {
        name: 'Total Cholesterol/HDL Ratio',
        unit: 'ratio',
        normalRangeMale: '<5.0',
        normalRangeFemale: '<4.5',
        normalRangePediatric: '<4.5',
        formula: 'TC/HDL Ratio = Total Cholesterol / HDL Cholesterol',
        dependsOn: ['Total Cholesterol', 'HDL Cholesterol'],
      },
      {
        name: 'Non-HDL Cholesterol',
        unit: 'mg/dL',
        normalRangeMale: '<130',
        normalRangeFemale: '<130',
        normalRangePediatric: '<120',
        formula: 'Non-HDL = Total Cholesterol - HDL Cholesterol',
        dependsOn: ['Total Cholesterol', 'HDL Cholesterol'],
      },
    ],
  },
  {
    name: 'Total Cholesterol',
    price: 150,
    parameter: 'Total Cholesterol',
    unit: 'mg/dL',
    normalRangeMale: '<200',
    normalRangeFemale: '<200',
    normalRangePediatric: '<170',
  },
  {
    name: 'Serum Triglycerides',
    price: 150,
    parameter: 'Triglycerides',
    unit: 'mg/dL',
    normalRangeMale: '<150',
    normalRangeFemale: '<150',
    normalRangePediatric: '<100',
  },
  {
    name: 'HDL Cholesterol',
    price: 200,
    parameter: 'HDL-C',
    unit: 'mg/dL',
    normalRangeMale: '>40',
    normalRangeFemale: '>50',
    normalRangePediatric: '>45',
  },
  {
    name: 'LDL Cholesterol (Direct)',
    price: 300,
    parameter: 'LDL-C (Direct)',
    unit: 'mg/dL',
    normalRangeMale: '<100',
    normalRangeFemale: '<100',
    normalRangePediatric: '<110',
  },
  {
    name: 'Apolipoprotein A1 (Apo A1)',
    price: 400,
    parameter: 'Apo A1',
    unit: 'mg/dL',
    normalRangeMale: '110-180',
    normalRangeFemale: '110-205',
    normalRangePediatric: '110-180',
  },
  {
    name: 'Apolipoprotein B (Apo B)',
    price: 400,
    parameter: 'Apo B',
    unit: 'mg/dL',
    normalRangeMale: '60-140',
    normalRangeFemale: '60-120',
    normalRangePediatric: '50-120',
  },
  {
    name: 'Apo B/Apo A1 Ratio',
    price: 600,
    parameters: [
      {
        name: 'Apo A1',
        unit: 'mg/dL',
        normalRangeMale: '110-180',
        normalRangeFemale: '110-205',
        normalRangePediatric: '110-180',
      },
      {
        name: 'Apo B',
        unit: 'mg/dL',
        normalRangeMale: '60-140',
        normalRangeFemale: '60-120',
        normalRangePediatric: '50-120',
      },
      {
        name: 'Apo B/Apo A1 Ratio',
        unit: 'ratio',
        normalRangeMale: '<0.9',
        normalRangeFemale: '<0.9',
        normalRangePediatric: '<0.9',
        formula: 'Apo B/Apo A1 Ratio = Apo B / Apo A1',
        dependsOn: ['Apo B', 'Apo A1'],
      },
    ],
  },
  {
    name: 'Lipoprotein (a) [Lp(a)]',
    price: 500,
    parameter: 'Lp(a)',
    unit: 'mg/dL',
    normalRangeMale: '<30',
    normalRangeFemale: '<30',
    normalRangePediatric: '<30',
  },
  {
    name: 'Homocysteine',
    price: 600,
    parameter: 'Homocysteine',
    unit: 'µmol/L',
    normalRangeMale: '5-15',
    normalRangeFemale: '5-15',
    normalRangePediatric: '5-15',
  },
  {
    name: 'hs-CRP (High Sensitivity C-Reactive Protein)',
    price: 400,
    parameter: 'hs-CRP',
    unit: 'mg/L',
    normalRangeMale: '<1.0',
    normalRangeFemale: '<1.0',
    normalRangePediatric: '<1.0',
  },
  // Cardiac Markers
  {
    name: 'Cardiac Profile',
    price: 1500,
    parameters: [
      {
        name: 'Troponin I',
        unit: 'ng/mL',
        normalRangeMale: '<0.04',
        normalRangeFemale: '<0.04',
        normalRangePediatric: '<0.04',
        criticalMax: 0.1,
      },
      {
        name: 'Troponin T',
        unit: 'ng/mL',
        normalRangeMale: '<0.01',
        normalRangeFemale: '<0.01',
        normalRangePediatric: '<0.01',
        criticalMax: 0.03,
      },
      {
        name: 'CK-MB',
        unit: 'U/L',
        normalRangeMale: '0-25',
        normalRangeFemale: '0-25',
        normalRangePediatric: '0-25',
      },
      {
        name: 'CK Total',
        unit: 'U/L',
        normalRangeMale: '30-200',
        normalRangeFemale: '30-180',
        normalRangePediatric: '30-200',
      },
      {
        name: 'LDH',
        unit: 'U/L',
        normalRangeMale: '140-280',
        normalRangeFemale: '140-280',
        normalRangePediatric: '140-280',
      },
      {
        name: 'AST (SGOT)',
        unit: 'U/L',
        normalRangeMale: '10-40',
        normalRangeFemale: '10-40',
        normalRangePediatric: '15-55',
      },
      {
        name: 'Myoglobin',
        unit: 'ng/mL',
        normalRangeMale: '25-72',
        normalRangeFemale: '25-72',
        normalRangePediatric: '25-72',
      },
    ],
  },
  {
    name: 'Troponin I',
    price: 500,
    parameter: 'Troponin I',
    unit: 'ng/mL',
    normalRangeMale: '<0.04',
    normalRangeFemale: '<0.04',
    normalRangePediatric: '<0.04',
    criticalMax: 0.1,
  },
  {
    name: 'Troponin T',
    price: 500,
    parameter: 'Troponin T',
    unit: 'ng/mL',
    normalRangeMale: '<0.01',
    normalRangeFemale: '<0.01',
    normalRangePediatric: '<0.01',
    criticalMax: 0.03,
  },
  {
    name: 'CK-MB',
    price: 300,
    parameter: 'CK-MB',
    unit: 'U/L',
    normalRangeMale: '0-25',
    normalRangeFemale: '0-25',
    normalRangePediatric: '0-25',
  },
  {
    name: 'Creatine Kinase (CK Total)',
    price: 200,
    parameter: 'CK Total',
    unit: 'U/L',
    normalRangeMale: '30-200',
    normalRangeFemale: '30-180',
    normalRangePediatric: '30-200',
  },
  {
    name: 'CK Isoenzymes',
    price: 400,
    parameters: [
      {
        name: 'CK-MM',
        unit: '%',
        normalRangeMale: '95-100',
        normalRangeFemale: '95-100',
        normalRangePediatric: '95-100',
      },
      {
        name: 'CK-MB',
        unit: '%',
        normalRangeMale: '0-5',
        normalRangeFemale: '0-5',
        normalRangePediatric: '0-5',
      },
      {
        name: 'CK-BB',
        unit: '%',
        normalRangeMale: '0-1',
        normalRangeFemale: '0-1',
        normalRangePediatric: '0-1',
      },
    ],
  },
  {
    name: 'Lactate Dehydrogenase (LDH)',
    price: 200,
    parameter: 'LDH',
    unit: 'U/L',
    normalRangeMale: '140-280',
    normalRangeFemale: '140-280',
    normalRangePediatric: '140-280',
  },
  {
    name: 'LDH Isoenzymes',
    price: 500,
    parameters: [
      {
        name: 'LDH-1',
        unit: '%',
        normalRangeMale: '17-27',
        normalRangeFemale: '17-27',
        normalRangePediatric: '17-27',
      },
      {
        name: 'LDH-2',
        unit: '%',
        normalRangeMale: '29-39',
        normalRangeFemale: '29-39',
        normalRangePediatric: '29-39',
      },
      {
        name: 'LDH-3',
        unit: '%',
        normalRangeMale: '19-27',
        normalRangeFemale: '19-27',
        normalRangePediatric: '19-27',
      },
      {
        name: 'LDH-4',
        unit: '%',
        normalRangeMale: '8-18',
        normalRangeFemale: '8-18',
        normalRangePediatric: '8-18',
      },
      {
        name: 'LDH-5',
        unit: '%',
        normalRangeMale: '6-16',
        normalRangeFemale: '6-16',
        normalRangePediatric: '6-16',
      },
    ],
  },
  {
    name: 'Myoglobin',
    price: 400,
    parameter: 'Myoglobin',
    unit: 'ng/mL',
    normalRangeMale: '25-72',
    normalRangeFemale: '25-72',
    normalRangePediatric: '25-72',
  },
  {
    name: 'BNP (B-type Natriuretic Peptide)',
    price: 800,
    parameter: 'BNP',
    unit: 'pg/mL',
    normalRangeMale: '<100',
    normalRangeFemale: '<100',
    normalRangePediatric: '<100',
  },
  {
    name: 'NT-proBNP',
    price: 800,
    parameter: 'NT-proBNP',
    unit: 'pg/mL',
    normalRangeMale: '<125',
    normalRangeFemale: '<125',
    normalRangePediatric: '<125',
  },
  // Glucose and Diabetes Tests
  {
    name: 'Fasting Blood Sugar (FBS)',
    price: 100,
    parameter: 'Glucose (Fasting)',
    unit: 'mg/dL',
    normalRangeMale: '70-100',
    normalRangeFemale: '70-100',
    normalRangePediatric: '70-100',
    criticalMin: 40,
    criticalMax: 500,
  },
  {
    name: 'Random Blood Sugar (RBS)',
    price: 100,
    parameter: 'Glucose (Random)',
    unit: 'mg/dL',
    normalRangeMale: '<140',
    normalRangeFemale: '<140',
    normalRangePediatric: '<140',
    criticalMin: 40,
    criticalMax: 500,
  },
  {
    name: 'Post Prandial Blood Sugar (PPBS)',
    price: 100,
    parameter: 'Glucose (2hr PP)',
    unit: 'mg/dL',
    normalRangeMale: '<140',
    normalRangeFemale: '<140',
    normalRangePediatric: '<140',
  },
  {
    name: 'Oral Glucose Tolerance Test (OGTT)',
    price: 400,
    parameters: [
      {
        name: 'Fasting Glucose',
        unit: 'mg/dL',
        normalRangeMale: '70-100',
        normalRangeFemale: '70-100',
        normalRangePediatric: '70-100',
      },
      {
        name: '30-min Glucose',
        unit: 'mg/dL',
        normalRangeMale: '<200',
        normalRangeFemale: '<200',
        normalRangePediatric: '<200',
      },
      {
        name: '1-hour Glucose',
        unit: 'mg/dL',
        normalRangeMale: '<200',
        normalRangeFemale: '<200',
        normalRangePediatric: '<200',
      },
      {
        name: '2-hour Glucose',
        unit: 'mg/dL',
        normalRangeMale: '<140',
        normalRangeFemale: '<140',
        normalRangePediatric: '<140',
      },
    ],
  },
  {
    name: 'GTT (3-Sample)',
    price: 300,
    parameters: [
      {
        name: 'Fasting Glucose',
        unit: 'mg/dL',
        normalRangeMale: '70-100',
        normalRangeFemale: '70-100',
        normalRangePediatric: '70-100',
      },
      {
        name: '1-hour Glucose',
        unit: 'mg/dL',
        normalRangeMale: '<200',
        normalRangeFemale: '<200',
        normalRangePediatric: '<200',
      },
      {
        name: '2-hour Glucose',
        unit: 'mg/dL',
        normalRangeMale: '<140',
        normalRangeFemale: '<140',
        normalRangePediatric: '<140',
      },
    ],
  },
  {
    name: 'GTT (Extended 5-Sample)',
    price: 500,
    parameters: [
      {
        name: 'Fasting Glucose',
        unit: 'mg/dL',
        normalRangeMale: '70-100',
        normalRangeFemale: '70-100',
        normalRangePediatric: '70-100',
      },
      {
        name: '30-min Glucose',
        unit: 'mg/dL',
        normalRangeMale: '<200',
        normalRangeFemale: '<200',
        normalRangePediatric: '<200',
      },
      {
        name: '1-hour Glucose',
        unit: 'mg/dL',
        normalRangeMale: '<200',
        normalRangeFemale: '<200',
        normalRangePediatric: '<200',
      },
      {
        name: '90-min Glucose',
        unit: 'mg/dL',
        normalRangeMale: '<180',
        normalRangeFemale: '<180',
        normalRangePediatric: '<180',
      },
      {
        name: '2-hour Glucose',
        unit: 'mg/dL',
        normalRangeMale: '<140',
        normalRangeFemale: '<140',
        normalRangePediatric: '<140',
      },
    ],
  },
  {
    name: 'Fructosamine',
    price: 400,
    parameter: 'Fructosamine',
    unit: 'µmol/L',
    normalRangeMale: '200-285',
    normalRangeFemale: '200-285',
    normalRangePediatric: '200-285',
  },
  {
    name: 'C-Peptide',
    price: 600,
    parameter: 'C-Peptide',
    unit: 'ng/mL',
    normalRangeMale: '0.8-3.1',
    normalRangeFemale: '0.8-3.1',
    normalRangePediatric: '0.8-3.1',
  },
  {
    name: 'Insulin (Fasting)',
    price: 600,
    parameter: 'Insulin',
    unit: 'µIU/mL',
    normalRangeMale: '2.6-24.9',
    normalRangeFemale: '2.6-24.9',
    normalRangePediatric: '2.6-24.9',
  },
  {
    name: 'Insulin Resistance (HOMA-IR)',
    price: 800,
    parameters: [
      {
        name: 'Fasting Glucose',
        unit: 'mg/dL',
        normalRangeMale: '70-100',
        normalRangeFemale: '70-100',
        normalRangePediatric: '70-100',
      },
      {
        name: 'Fasting Insulin',
        unit: 'µIU/mL',
        normalRangeMale: '2.6-24.9',
        normalRangeFemale: '2.6-24.9',
        normalRangePediatric: '2.6-24.9',
      },
      {
        name: 'HOMA-IR',
        unit: 'index',
        normalRangeMale: '<2.5',
        normalRangeFemale: '<2.5',
        normalRangePediatric: '<2.5',
        formula: 'HOMA-IR = (Fasting Glucose × Fasting Insulin) / 405',
        dependsOn: ['Fasting Glucose', 'Fasting Insulin'],
      },
    ],
  },
  // Electrolytes
  {
    name: 'Serum Electrolytes',
    price: 400,
    parameters: [
      {
        name: 'Sodium (Na)',
        unit: 'mmol/L',
        normalRangeMale: '136-145',
        normalRangeFemale: '136-145',
        normalRangePediatric: '135-145',
        criticalMin: 120,
        criticalMax: 160,
      },
      {
        name: 'Potassium (K)',
        unit: 'mmol/L',
        normalRangeMale: '3.5-5.0',
        normalRangeFemale: '3.5-5.0',
        normalRangePediatric: '3.5-5.5',
        criticalMin: 2.5,
        criticalMax: 6.0,
      },
      {
        name: 'Chloride (Cl)',
        unit: 'mmol/L',
        normalRangeMale: '98-107',
        normalRangeFemale: '98-107',
        normalRangePediatric: '98-107',
      },
    ],
  },
  {
    name: 'Serum Sodium',
    price: 150,
    parameter: 'Sodium',
    unit: 'mmol/L',
    normalRangeMale: '136-145',
    normalRangeFemale: '136-145',
    normalRangePediatric: '135-145',
    criticalMin: 120,
    criticalMax: 160,
  },
  {
    name: 'Serum Potassium',
    price: 150,
    parameter: 'Potassium',
    unit: 'mmol/L',
    normalRangeMale: '3.5-5.0',
    normalRangeFemale: '3.5-5.0',
    normalRangePediatric: '3.5-5.5',
    criticalMin: 2.5,
    criticalMax: 6.0,
  },
  {
    name: 'Serum Chloride',
    price: 150,
    parameter: 'Chloride',
    unit: 'mmol/L',
    normalRangeMale: '98-107',
    normalRangeFemale: '98-107',
    normalRangePediatric: '98-107',
  },
  {
    name: 'Serum Bicarbonate',
    price: 150,
    parameter: 'HCO3',
    unit: 'mmol/L',
    normalRangeMale: '22-28',
    normalRangeFemale: '22-28',
    normalRangePediatric: '22-28',
  },
  {
    name: 'Serum Calcium',
    price: 200,
    parameter: 'Calcium (Total)',
    unit: 'mg/dL',
    normalRangeMale: '8.5-10.5',
    normalRangeFemale: '8.5-10.5',
    normalRangePediatric: '8.5-10.5',
    criticalMin: 6.0,
    criticalMax: 13.0,
  },
  {
    name: 'Ionized Calcium',
    price: 300,
    parameter: 'Ionized Calcium',
    unit: 'mmol/L',
    normalRangeMale: '1.12-1.32',
    normalRangeFemale: '1.12-1.32',
    normalRangePediatric: '1.12-1.32',
  },
  {
    name: 'Serum Phosphorus',
    price: 200,
    parameter: 'Phosphorus',
    unit: 'mg/dL',
    normalRangeMale: '2.5-4.5',
    normalRangeFemale: '2.5-4.5',
    normalRangePediatric: '4.0-7.0',
  },
  {
    name: 'Serum Magnesium',
    price: 200,
    parameter: 'Magnesium',
    unit: 'mg/dL',
    normalRangeMale: '1.7-2.4',
    normalRangeFemale: '1.7-2.4',
    normalRangePediatric: '1.7-2.4',
  },
  {
    name: 'Anion Gap',
    price: 200,
    parameter: 'Anion Gap',
    unit: 'mmol/L',
    normalRangeMale: '8-16',
    normalRangeFemale: '8-16',
    normalRangePediatric: '8-16',
  },
  {
    name: 'Electrolyte Panel Comprehensive',
    price: 600,
    parameters: [
      {
        name: 'Sodium (Na)',
        unit: 'mmol/L',
        normalRangeMale: '136-145',
        normalRangeFemale: '136-145',
        normalRangePediatric: '135-145',
        criticalMin: 120,
        criticalMax: 160,
      },
      {
        name: 'Potassium (K)',
        unit: 'mmol/L',
        normalRangeMale: '3.5-5.0',
        normalRangeFemale: '3.5-5.0',
        normalRangePediatric: '3.5-5.5',
        criticalMin: 2.5,
        criticalMax: 6.0,
      },
      {
        name: 'Chloride (Cl)',
        unit: 'mmol/L',
        normalRangeMale: '98-107',
        normalRangeFemale: '98-107',
        normalRangePediatric: '98-107',
      },
      {
        name: 'Bicarbonate (HCO3)',
        unit: 'mmol/L',
        normalRangeMale: '22-28',
        normalRangeFemale: '22-28',
        normalRangePediatric: '22-28',
      },
      {
        name: 'Anion Gap',
        unit: 'mmol/L',
        normalRangeMale: '8-16',
        normalRangeFemale: '8-16',
        normalRangePediatric: '8-16',
        formula: 'Anion Gap = Na - (Cl + HCO3)',
        dependsOn: ['Sodium (Na)', 'Chloride (Cl)', 'Bicarbonate (HCO3)'],
      },
      {
        name: 'Calcium (Total)',
        unit: 'mg/dL',
        normalRangeMale: '8.5-10.5',
        normalRangeFemale: '8.5-10.5',
        normalRangePediatric: '8.5-10.5',
        criticalMin: 6.0,
        criticalMax: 13.0,
      },
      {
        name: 'Phosphorus',
        unit: 'mg/dL',
        normalRangeMale: '2.5-4.5',
        normalRangeFemale: '2.5-4.5',
        normalRangePediatric: '4.0-7.0',
      },
      {
        name: 'Magnesium',
        unit: 'mg/dL',
        normalRangeMale: '1.7-2.4',
        normalRangeFemale: '1.7-2.4',
        normalRangePediatric: '1.7-2.4',
      },
    ],
  },
  // Arterial Blood Gas
  {
    name: 'Arterial Blood Gas (ABG)',
    price: 600,
    parameters: [
      {
        name: 'pH',
        unit: 'pH units',
        normalRangeMale: '7.35-7.45',
        normalRangeFemale: '7.35-7.45',
        normalRangePediatric: '7.35-7.45',
        criticalMin: 7.20,
        criticalMax: 7.55,
      },
      {
        name: 'pCO2',
        unit: 'mmHg',
        normalRangeMale: '35-45',
        normalRangeFemale: '35-45',
        normalRangePediatric: '35-45',
        criticalMin: 20,
        criticalMax: 70,
      },
      {
        name: 'pO2',
        unit: 'mmHg',
        normalRangeMale: '75-100',
        normalRangeFemale: '75-100',
        normalRangePediatric: '75-100',
        criticalMin: 50,
      },
      {
        name: 'HCO3',
        unit: 'mmol/L',
        normalRangeMale: '22-26',
        normalRangeFemale: '22-26',
        normalRangePediatric: '22-26',
      },
      {
        name: 'Base Excess',
        unit: 'mmol/L',
        normalRangeMale: '-2 to +2',
        normalRangeFemale: '-2 to +2',
        normalRangePediatric: '-2 to +2',
      },
      {
        name: 'Oxygen Saturation (SpO2)',
        unit: '%',
        normalRangeMale: '95-100',
        normalRangeFemale: '95-100',
        normalRangePediatric: '95-100',
      },
    ],
  },
  {
    name: 'Venous Blood Gas (VBG)',
    price: 400,
    parameters: [
      {
        name: 'pH',
        unit: 'pH units',
        normalRangeMale: '7.31-7.41',
        normalRangeFemale: '7.31-7.41',
        normalRangePediatric: '7.31-7.41',
      },
      {
        name: 'pvCO2',
        unit: 'mmHg',
        normalRangeMale: '40-50',
        normalRangeFemale: '40-50',
        normalRangePediatric: '40-50',
      },
      {
        name: 'pvO2',
        unit: 'mmHg',
        normalRangeMale: '30-50',
        normalRangeFemale: '30-50',
        normalRangePediatric: '30-50',
      },
      {
        name: 'HCO3',
        unit: 'mmol/L',
        normalRangeMale: '22-26',
        normalRangeFemale: '22-26',
        normalRangePediatric: '22-26',
      },
    ],
  },
  // Pancreatic Function
  {
    name: 'Serum Amylase',
    price: 250,
    parameter: 'Amylase',
    unit: 'U/L',
    normalRangeMale: '30-110',
    normalRangeFemale: '30-110',
    normalRangePediatric: '30-110',
  },
  {
    name: 'Serum Lipase',
    price: 300,
    parameter: 'Lipase',
    unit: 'U/L',
    normalRangeMale: '10-140',
    normalRangeFemale: '10-140',
    normalRangePediatric: '10-140',
  },
  {
    name: 'Pancreatic Amylase',
    price: 350,
    parameter: 'Pancreatic Amylase',
    unit: 'U/L',
    normalRangeMale: '13-53',
    normalRangeFemale: '13-53',
    normalRangePediatric: '13-53',
  },
  // Thyroid Function Tests
  {
    name: 'Thyroid Profile (T3, T4, TSH)',
    price: 600,
    parameters: [
      {
        name: 'TSH',
        unit: 'mIU/L',
        normalRangeMale: '0.4-4.0',
        normalRangeFemale: '0.4-4.0',
        normalRangePediatric: '0.4-4.0',
      },
      {
        name: 'Total T3',
        unit: 'ng/dL',
        normalRangeMale: '80-200',
        normalRangeFemale: '80-200',
        normalRangePediatric: '80-200',
      },
      {
        name: 'Total T4',
        unit: 'µg/dL',
        normalRangeMale: '5.0-12.0',
        normalRangeFemale: '5.0-12.0',
        normalRangePediatric: '6.0-14.0',
      },
    ],
  },
  {
    name: 'Thyroid Profile Free (FT3, FT4, TSH)',
    price: 800,
    parameters: [
      {
        name: 'TSH',
        unit: 'mIU/L',
        normalRangeMale: '0.4-4.0',
        normalRangeFemale: '0.4-4.0',
        normalRangePediatric: '0.4-4.0',
      },
      {
        name: 'Free T3',
        unit: 'pg/mL',
        normalRangeMale: '2.0-4.4',
        normalRangeFemale: '2.0-4.4',
        normalRangePediatric: '2.0-4.4',
      },
      {
        name: 'Free T4',
        unit: 'ng/dL',
        normalRangeMale: '0.8-1.8',
        normalRangeFemale: '0.8-1.8',
        normalRangePediatric: '0.8-1.8',
      },
    ],
  },
  {
    name: 'TSH (Thyroid Stimulating Hormone)',
    price: 250,
    parameter: 'TSH',
    unit: 'mIU/L',
    normalRangeMale: '0.4-4.0',
    normalRangeFemale: '0.4-4.0',
    normalRangePediatric: '0.4-4.0',
  },
  {
    name: 'Total T3',
    price: 300,
    parameter: 'Total T3',
    unit: 'ng/dL',
    normalRangeMale: '80-200',
    normalRangeFemale: '80-200',
    normalRangePediatric: '80-200',
  },
  {
    name: 'Total T4',
    price: 300,
    parameter: 'Total T4',
    unit: 'µg/dL',
    normalRangeMale: '5.0-12.0',
    normalRangeFemale: '5.0-12.0',
    normalRangePediatric: '6.0-14.0',
  },
  {
    name: 'Free T3',
    price: 400,
    parameter: 'Free T3',
    unit: 'pg/mL',
    normalRangeMale: '2.0-4.4',
    normalRangeFemale: '2.0-4.4',
    normalRangePediatric: '2.0-4.4',
  },
  {
    name: 'Free T4',
    price: 400,
    parameter: 'Free T4',
    unit: 'ng/dL',
    normalRangeMale: '0.8-1.8',
    normalRangeFemale: '0.8-1.8',
    normalRangePediatric: '0.8-1.8',
  },
  {
    name: 'Reverse T3',
    price: 500,
    parameter: 'Reverse T3',
    unit: 'ng/dL',
    normalRangeMale: '10-24',
    normalRangeFemale: '10-24',
    normalRangePediatric: '10-24',
  },
  {
    name: 'Thyroglobulin',
    price: 500,
    parameter: 'Thyroglobulin',
    unit: 'ng/mL',
    normalRangeMale: '2.0-35',
    normalRangeFemale: '2.0-35',
    normalRangePediatric: '2.0-35',
  },
  {
    name: 'Anti-TPO (Thyroid Peroxidase Antibodies)',
    price: 500,
    parameter: 'Anti-TPO',
    unit: 'IU/mL',
    normalRangeMale: '<35',
    normalRangeFemale: '<35',
    normalRangePediatric: '<35',
  },
  {
    name: 'Anti-Thyroglobulin Antibodies',
    price: 500,
    parameter: 'Anti-Tg',
    unit: 'IU/mL',
    normalRangeMale: '<20',
    normalRangeFemale: '<20',
    normalRangePediatric: '<20',
  },
  {
    name: 'TSH Receptor Antibodies (TRAb)',
    price: 800,
    parameter: 'TRAb',
    unit: 'IU/L',
    normalRangeMale: '<1.75',
    normalRangeFemale: '<1.75',
    normalRangePediatric: '<1.75',
  },
  // Tumor Markers
  {
    name: 'Alpha Feto Protein (AFP)',
    price: 500,
    parameter: 'AFP',
    unit: 'ng/mL',
    normalRangeMale: '<10',
    normalRangeFemale: '<10',
    normalRangePediatric: '<10',
  },
  {
    name: 'CEA (Carcinoembryonic Antigen)',
    price: 500,
    parameter: 'CEA',
    unit: 'ng/mL',
    normalRangeMale: '<5',
    normalRangeFemale: '<5',
    normalRangePediatric: '<5',
  },
  {
    name: 'CA-125',
    price: 600,
    parameter: 'CA-125',
    unit: 'U/mL',
    normalRangeMale: '<35',
    normalRangeFemale: '<35',
    normalRangePediatric: '<35',
  },
  {
    name: 'CA 19-9',
    price: 600,
    parameter: 'CA 19-9',
    unit: 'U/mL',
    normalRangeMale: '<37',
    normalRangeFemale: '<37',
    normalRangePediatric: '<37',
  },
  {
    name: 'CA 15-3',
    price: 600,
    parameter: 'CA 15-3',
    unit: 'U/mL',
    normalRangeMale: '<30',
    normalRangeFemale: '<30',
    normalRangePediatric: '<30',
  },
  {
    name: 'PSA (Prostate Specific Antigen)',
    price: 500,
    parameter: 'Total PSA',
    unit: 'ng/mL',
    normalRangeMale: '<4.0',
    normalRangeFemale: 'N/A',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Free PSA',
    price: 500,
    parameter: 'Free PSA',
    unit: 'ng/mL',
    normalRangeMale: 'Varies',
    normalRangeFemale: 'N/A',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'PSA Ratio (Free/Total)',
    price: 800,
    parameters: [
      {
        name: 'Total PSA',
        unit: 'ng/mL',
        normalRangeMale: '<4.0',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Free PSA',
        unit: 'ng/mL',
        normalRangeMale: 'Varies',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Free/Total PSA Ratio',
        unit: '%',
        normalRangeMale: '>25%',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
        formula: 'PSA Ratio = (Free PSA / Total PSA) × 100',
        dependsOn: ['Total PSA', 'Free PSA'],
      },
    ],
  },
  {
    name: 'Beta HCG',
    price: 500,
    parameter: 'Beta HCG',
    unit: 'mIU/mL',
    normalRangeMale: '<5',
    normalRangeFemale: '<5 (non-pregnant)',
    normalRangePediatric: '<5',
  },
  {
    name: 'Serum Beta HCG (Pregnancy)',
    price: 500,
    parameter: 'Beta HCG',
    unit: 'mIU/mL',
    normalRangeMale: '<5',
    normalRangeFemale: 'Pregnancy dependent',
    normalRangePediatric: '<5',
  },
  {
    name: 'LDH (Lactate Dehydrogenase)',
    price: 200,
    parameter: 'LDH',
    unit: 'U/L',
    normalRangeMale: '140-280',
    normalRangeFemale: '140-280',
    normalRangePediatric: '140-280',
  },
  // Bone Metabolism
  {
    name: 'Serum Calcium (Total)',
    price: 200,
    parameter: 'Calcium',
    unit: 'mg/dL',
    normalRangeMale: '8.5-10.5',
    normalRangeFemale: '8.5-10.5',
    normalRangePediatric: '8.5-10.5',
  },
  {
    name: 'Serum Phosphorus',
    price: 200,
    parameter: 'Phosphorus',
    unit: 'mg/dL',
    normalRangeMale: '2.5-4.5',
    normalRangeFemale: '2.5-4.5',
    normalRangePediatric: '4.0-7.0',
  },
  {
    name: 'Alkaline Phosphatase (ALP)',
    price: 150,
    parameter: 'ALP',
    unit: 'U/L',
    normalRangeMale: '44-147',
    normalRangeFemale: '44-147',
    normalRangePediatric: '100-400',
  },
  {
    name: 'Parathyroid Hormone (PTH)',
    price: 600,
    parameter: 'PTH Intact',
    unit: 'pg/mL',
    normalRangeMale: '15-65',
    normalRangeFemale: '15-65',
    normalRangePediatric: '15-65',
  },
  {
    name: 'Vitamin D (25-OH)',
    price: 600,
    parameter: '25-OH Vitamin D',
    unit: 'ng/mL',
    normalRangeMale: '30-100',
    normalRangeFemale: '30-100',
    normalRangePediatric: '30-100',
  },
  {
    name: 'Vitamin D (1,25-Dihydroxy)',
    price: 800,
    parameter: '1,25-(OH)2 Vitamin D',
    unit: 'pg/mL',
    normalRangeMale: '18-64',
    normalRangeFemale: '18-64',
    normalRangePediatric: '18-64',
  },
  {
    name: 'Osteocalcin',
    price: 600,
    parameter: 'Osteocalcin',
    unit: 'ng/mL',
    normalRangeMale: '3-15',
    normalRangeFemale: '3-15',
    normalRangePediatric: '3-15',
  },
  {
    name: 'Beta CrossLaps (CTX)',
    price: 800,
    parameter: 'Beta-CTx',
    unit: 'ng/mL',
    normalRangeMale: '0.1-1.0',
    normalRangeFemale: '0.1-1.0',
    normalRangePediatric: '0.1-1.0',
  },
  {
    name: 'Bone Profile',
    price: 1200,
    parameters: [
      {
        name: 'Calcium (Total)',
        unit: 'mg/dL',
        normalRangeMale: '8.5-10.5',
        normalRangeFemale: '8.5-10.5',
        normalRangePediatric: '8.5-10.5',
      },
      {
        name: 'Phosphorus',
        unit: 'mg/dL',
        normalRangeMale: '2.5-4.5',
        normalRangeFemale: '2.5-4.5',
        normalRangePediatric: '4.0-7.0',
      },
      {
        name: 'Alkaline Phosphatase',
        unit: 'U/L',
        normalRangeMale: '44-147',
        normalRangeFemale: '44-147',
        normalRangePediatric: '100-400',
      },
      {
        name: 'PTH Intact',
        unit: 'pg/mL',
        normalRangeMale: '15-65',
        normalRangeFemale: '15-65',
        normalRangePediatric: '15-65',
      },
      {
        name: '25-OH Vitamin D',
        unit: 'ng/mL',
        normalRangeMale: '30-100',
        normalRangeFemale: '30-100',
        normalRangePediatric: '30-100',
      },
    ],
  },
  // Miscellaneous Chemistry Tests
  {
    name: 'Serum Ammonia',
    price: 400,
    parameter: 'Ammonia',
    unit: 'µmol/L',
    normalRangeMale: '15-45',
    normalRangeFemale: '15-45',
    normalRangePediatric: '15-45',
  },
  {
    name: 'Serum Lactate',
    price: 400,
    parameter: 'Lactate',
    unit: 'mmol/L',
    normalRangeMale: '0.5-2.0',
    normalRangeFemale: '0.5-2.0',
    normalRangePediatric: '0.5-2.0',
  },
  {
    name: 'Serum Copper',
    price: 400,
    parameter: 'Copper',
    unit: 'µg/dL',
    normalRangeMale: '70-140',
    normalRangeFemale: '80-155',
    normalRangePediatric: '80-140',
  },
  {
    name: 'Serum Zinc',
    price: 400,
    parameter: 'Zinc',
    unit: 'µg/dL',
    normalRangeMale: '70-120',
    normalRangeFemale: '70-120',
    normalRangePediatric: '70-120',
  },
  {
    name: 'Serum Selenium',
    price: 600,
    parameter: 'Selenium',
    unit: 'µg/L',
    normalRangeMale: '70-150',
    normalRangeFemale: '70-150',
    normalRangePediatric: '70-150',
  },
  {
    name: 'Ceruloplasmin',
    price: 500,
    parameter: 'Ceruloplasmin',
    unit: 'mg/dL',
    normalRangeMale: '20-40',
    normalRangeFemale: '20-40',
    normalRangePediatric: '20-40',
  },
  {
    name: 'Serum Chromium',
    price: 600,
    parameter: 'Chromium',
    unit: 'µg/L',
    normalRangeMale: '<0.5',
    normalRangeFemale: '<0.5',
    normalRangePediatric: '<0.5',
  },
  {
    name: 'Serum Lead',
    price: 600,
    parameter: 'Lead',
    unit: 'µg/dL',
    normalRangeMale: '<10',
    normalRangeFemale: '<10',
    normalRangePediatric: '<5',
  },
  {
    name: 'Serum Mercury',
    price: 600,
    parameter: 'Mercury',
    unit: 'µg/L',
    normalRangeMale: '<10',
    normalRangeFemale: '<10',
    normalRangePediatric: '<10',
  },
  {
    name: 'Serum Arsenic',
    price: 600,
    parameter: 'Arsenic',
    unit: 'µg/L',
    normalRangeMale: '<10',
    normalRangeFemale: '<10',
    normalRangePediatric: '<10',
  },
  {
    name: 'Serum Cadmium',
    price: 600,
    parameter: 'Cadmium',
    unit: 'µg/L',
    normalRangeMale: '<0.5',
    normalRangeFemale: '<0.5',
    normalRangePediatric: '<0.5',
  },
  {
    name: 'Serum Aluminum',
    price: 600,
    parameter: 'Aluminum',
    unit: 'µg/L',
    normalRangeMale: '<10',
    normalRangeFemale: '<10',
    normalRangePediatric: '<10',
  },
  {
    name: 'Serum Manganese',
    price: 600,
    parameter: 'Manganese',
    unit: 'µg/L',
    normalRangeMale: '0.4-1.1',
    normalRangeFemale: '0.4-1.1',
    normalRangePediatric: '0.4-1.1',
  },
  {
    name: 'Serum Molybdenum',
    price: 600,
    parameter: 'Molybdenum',
    unit: 'µg/L',
    normalRangeMale: '0.1-3.0',
    normalRangeFemale: '0.1-3.0',
    normalRangePediatric: '0.1-3.0',
  },
  {
    name: 'Serum Cobalt',
    price: 600,
    parameter: 'Cobalt',
    unit: 'µg/L',
    normalRangeMale: '<1.0',
    normalRangeFemale: '<1.0',
    normalRangePediatric: '<1.0',
  },
  {
    name: 'Serum Nickel',
    price: 600,
    parameter: 'Nickel',
    unit: 'µg/L',
    normalRangeMale: '<1.0',
    normalRangeFemale: '<1.0',
    normalRangePediatric: '<1.0',
  },
  {
    name: 'Serum Iron',
    price: 300,
    parameter: 'Iron',
    unit: 'µg/dL',
    normalRangeMale: '60-170',
    normalRangeFemale: '50-150',
    normalRangePediatric: '50-150',
  },
  {
    name: 'Serum Transferrin',
    price: 400,
    parameter: 'Transferrin',
    unit: 'mg/dL',
    normalRangeMale: '200-360',
    normalRangeFemale: '200-360',
    normalRangePediatric: '200-360',
  },
  {
    name: 'Serum Prealbumin',
    price: 400,
    parameter: 'Prealbumin',
    unit: 'mg/dL',
    normalRangeMale: '20-40',
    normalRangeFemale: '20-40',
    normalRangePediatric: '20-40',
  },
  {
    name: 'Serum Retinol Binding Protein',
    price: 500,
    parameter: 'RBP',
    unit: 'mg/dL',
    normalRangeMale: '3.0-6.0',
    normalRangeFemale: '3.0-6.0',
    normalRangePediatric: '3.0-6.0',
  },
  // Enzymes
  {
    name: 'Acid Phosphatase',
    price: 300,
    parameter: 'Acid Phosphatase',
    unit: 'U/L',
    normalRangeMale: '0.5-2.0',
    normalRangeFemale: '0.2-0.8',
    normalRangePediatric: '0.5-2.0',
  },
  {
    name: 'Prostatic Acid Phosphatase (PAP)',
    price: 400,
    parameter: 'PAP',
    unit: 'ng/mL',
    normalRangeMale: '<2.5',
    normalRangeFemale: 'N/A',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Cholinesterase (Serum)',
    price: 400,
    parameter: 'Cholinesterase',
    unit: 'U/L',
    normalRangeMale: '5000-13000',
    normalRangeFemale: '5000-13000',
    normalRangePediatric: '5000-13000',
  },
  {
    name: 'Pseudocholinesterase',
    price: 400,
    parameter: 'Pseudocholinesterase',
    unit: 'U/L',
    normalRangeMale: '3000-8000',
    normalRangeFemale: '3000-8000',
    normalRangePediatric: '3000-8000',
  },
  {
    name: '5\'-Nucleotidase',
    price: 400,
    parameter: '5\'-NT',
    unit: 'U/L',
    normalRangeMale: '2-15',
    normalRangeFemale: '2-15',
    normalRangePediatric: '2-15',
  },
  {
    name: 'Gamma Glutamyl Transferase (GGT)',
    price: 200,
    parameter: 'GGT',
    unit: 'U/L',
    normalRangeMale: '9-50',
    normalRangeFemale: '9-50',
    normalRangePediatric: '5-25',
  },
  {
    name: 'Angiotensin Converting Enzyme (ACE)',
    price: 600,
    parameter: 'ACE',
    unit: 'U/L',
    normalRangeMale: '8-52',
    normalRangeFemale: '8-52',
    normalRangePediatric: '8-52',
  },
  {
    name: 'Lipase',
    price: 300,
    parameter: 'Lipase',
    unit: 'U/L',
    normalRangeMale: '10-140',
    normalRangeFemale: '10-140',
    normalRangePediatric: '10-140',
  },
  {
    name: 'Amylase',
    price: 250,
    parameter: 'Amylase',
    unit: 'U/L',
    normalRangeMale: '30-110',
    normalRangeFemale: '30-110',
    normalRangePediatric: '30-110',
  },
  {
    name: 'Aldolase',
    price: 500,
    parameter: 'Aldolase',
    unit: 'U/L',
    normalRangeMale: '0-8',
    normalRangeFemale: '0-8',
    normalRangePediatric: '0-8',
  },
  {
    name: 'Glucose-6-Phosphate Dehydrogenase (G6PD)',
    price: 500,
    parameter: 'G6PD',
    unit: 'U/g Hb',
    normalRangeMale: '4.6-13.5',
    normalRangeFemale: '4.6-13.5',
    normalRangePediatric: '4.6-13.5',
  },
  {
    name: 'Pyruvate Kinase',
    price: 600,
    parameter: 'Pyruvate Kinase',
    unit: 'U/g Hb',
    normalRangeMale: '10-20',
    normalRangeFemale: '10-20',
    normalRangePediatric: '10-20',
  },
]

export async function seedChemistryTests() {
  let created = 0
  let updated = 0
  
  for (const test of chemistryTests) {
    const res = await LabTest.updateOne(
      { name: test.name },
      { $set: test },
      { upsert: true }
    )
    if ((res as any).upsertedId || (res as any).upsertedCount) created++
    else if ((res as any).modifiedCount) updated++
  }
  
  return { total: chemistryTests.length, created, updated }
}
