import { LabTest } from '../modules/lab/models/Test'

export const urineMicrobiologyTests = [
  // Urine Analysis
  {
    name: 'Complete Urine Examination',
    price: 200,
    parameters: [
      {
        name: 'Color',
        unit: 'Report',
        normalRangeMale: 'Pale Yellow',
        normalRangeFemale: 'Pale Yellow',
        normalRangePediatric: 'Pale Yellow',
      },
      {
        name: 'Appearance',
        unit: 'Report',
        normalRangeMale: 'Clear',
        normalRangeFemale: 'Clear',
        normalRangePediatric: 'Clear',
      },
      {
        name: 'pH',
        unit: 'pH units',
        normalRangeMale: '4.6-8.0',
        normalRangeFemale: '4.6-8.0',
        normalRangePediatric: '4.6-8.0',
      },
      {
        name: 'Specific Gravity',
        unit: 'ratio',
        normalRangeMale: '1.005-1.030',
        normalRangeFemale: '1.005-1.030',
        normalRangePediatric: '1.005-1.030',
      },
      {
        name: 'Protein',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Glucose',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Ketones',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Bilirubin',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Urobilinogen',
        unit: 'mg/dL',
        normalRangeMale: '0.1-1.0',
        normalRangeFemale: '0.1-1.0',
        normalRangePediatric: '0.1-1.0',
      },
      {
        name: 'Blood',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Leukocyte Esterase',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Nitrite',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'RBCs',
        unit: '/HPF',
        normalRangeMale: '0-2',
        normalRangeFemale: '0-2',
        normalRangePediatric: '0-2',
      },
      {
        name: 'WBCs',
        unit: '/HPF',
        normalRangeMale: '0-5',
        normalRangeFemale: '0-5',
        normalRangePediatric: '0-5',
      },
      {
        name: 'Epithelial Cells',
        unit: '/HPF',
        normalRangeMale: '0-2',
        normalRangeFemale: '0-2',
        normalRangePediatric: '0-2',
      },
      {
        name: 'Casts',
        unit: '/LPF',
        normalRangeMale: '0-1 Hyaline',
        normalRangeFemale: '0-1 Hyaline',
        normalRangePediatric: '0-1 Hyaline',
      },
      {
        name: 'Crystals',
        unit: 'Report',
        normalRangeMale: 'None',
        normalRangeFemale: 'None',
        normalRangePediatric: 'None',
      },
      {
        name: 'Bacteria',
        unit: 'Report',
        normalRangeMale: 'None',
        normalRangeFemale: 'None',
        normalRangePediatric: 'None',
      },
    ],
  },
  {
    name: 'Urine Routine Examination',
    price: 150,
    parameters: [
      {
        name: 'Color',
        unit: 'Report',
        normalRangeMale: 'Pale Yellow',
        normalRangeFemale: 'Pale Yellow',
        normalRangePediatric: 'Pale Yellow',
      },
      {
        name: 'Appearance',
        unit: 'Report',
        normalRangeMale: 'Clear',
        normalRangeFemale: 'Clear',
        normalRangePediatric: 'Clear',
      },
      {
        name: 'pH',
        unit: 'pH units',
        normalRangeMale: '4.6-8.0',
        normalRangeFemale: '4.6-8.0',
        normalRangePediatric: '4.6-8.0',
      },
      {
        name: 'Specific Gravity',
        unit: 'ratio',
        normalRangeMale: '1.005-1.030',
        normalRangeFemale: '1.005-1.030',
        normalRangePediatric: '1.005-1.030',
      },
      {
        name: 'Protein',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Glucose',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
    ],
  },
  {
    name: 'Urine Pregnancy Test',
    price: 100,
    parameter: 'HCG',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'Negative (Non-pregnant)',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Urine Pregnancy Test (Beta HCG)',
    price: 200,
    parameter: 'Urine Beta HCG',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'Negative (Non-pregnant)',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Urine Culture and Sensitivity',
    price: 500,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Colony Count',
        unit: 'CFU/mL',
        normalRangeMale: '<10,000',
        normalRangeFemale: '<10,000',
        normalRangePediatric: '<10,000',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: '24-Hour Urine Analysis',
    price: 600,
    parameters: [
      {
        name: 'Volume',
        unit: 'mL/24hr',
        normalRangeMale: '800-2000',
        normalRangeFemale: '800-2000',
        normalRangePediatric: '500-1500',
      },
      {
        name: 'Total Protein',
        unit: 'mg/24hr',
        normalRangeMale: '<150',
        normalRangeFemale: '<150',
        normalRangePediatric: '<150',
      },
      {
        name: 'Creatinine',
        unit: 'mg/24hr',
        normalRangeMale: '800-2000',
        normalRangeFemale: '600-1800',
        normalRangePediatric: '300-800',
      },
      {
        name: 'Urea',
        unit: 'g/24hr',
        normalRangeMale: '12-20',
        normalRangeFemale: '12-20',
        normalRangePediatric: '8-15',
      },
      {
        name: 'Sodium',
        unit: 'mmol/24hr',
        normalRangeMale: '40-220',
        normalRangeFemale: '40-220',
        normalRangePediatric: '40-150',
      },
      {
        name: 'Potassium',
        unit: 'mmol/24hr',
        normalRangeMale: '25-125',
        normalRangeFemale: '25-125',
        normalRangePediatric: '25-100',
      },
      {
        name: 'Chloride',
        unit: 'mmol/24hr',
        normalRangeMale: '110-250',
        normalRangeFemale: '110-250',
        normalRangePediatric: '80-200',
      },
    ],
  },
  {
    name: '24-Hour Urine Protein',
    price: 400,
    parameter: 'Total Protein',
    unit: 'mg/24hr',
    normalRangeMale: '<150',
    normalRangeFemale: '<150',
    normalRangePediatric: '<150',
  },
  {
    name: '24-Hour Urine Creatinine',
    price: 300,
    parameter: 'Creatinine',
    unit: 'mg/24hr',
    normalRangeMale: '800-2000',
    normalRangeFemale: '600-1800',
    normalRangePediatric: '300-800',
  },
  {
    name: '24-Hour Urine Uric Acid',
    price: 400,
    parameter: 'Uric Acid',
    unit: 'mg/24hr',
    normalRangeMale: '250-750',
    normalRangeFemale: '250-750',
    normalRangePediatric: '200-500',
  },
  {
    name: '24-Hour Urine Calcium',
    price: 400,
    parameter: 'Calcium',
    unit: 'mg/24hr',
    normalRangeMale: '100-300',
    normalRangeFemale: '100-300',
    normalRangePediatric: '50-150',
  },
  {
    name: '24-Hour Urine Phosphorus',
    price: 400,
    parameter: 'Phosphorus',
    unit: 'g/24hr',
    normalRangeMale: '0.4-1.3',
    normalRangeFemale: '0.4-1.3',
    normalRangePediatric: '0.3-0.8',
  },
  {
    name: '24-Hour Urine Oxalate',
    price: 500,
    parameter: 'Oxalate',
    unit: 'mg/24hr',
    normalRangeMale: '10-40',
    normalRangeFemale: '10-40',
    normalRangePediatric: '10-30',
  },
  {
    name: '24-Hour Urine Citrate',
    price: 500,
    parameter: 'Citrate',
    unit: 'mg/24hr',
    normalRangeMale: '300-900',
    normalRangeFemale: '300-900',
    normalRangePediatric: '200-600',
  },
  {
    name: '24-Hour Urine Magnesium',
    price: 400,
    parameter: 'Magnesium',
    unit: 'mg/24hr',
    normalRangeMale: '30-150',
    normalRangeFemale: '30-150',
    normalRangePediatric: '20-100',
  },
  {
    name: '24-Hour Urine Sodium',
    price: 400,
    parameter: 'Sodium',
    unit: 'mmol/24hr',
    normalRangeMale: '40-220',
    normalRangeFemale: '40-220',
    normalRangePediatric: '40-150',
  },
  {
    name: '24-Hour Urine Potassium',
    price: 400,
    parameter: 'Potassium',
    unit: 'mmol/24hr',
    normalRangeMale: '25-125',
    normalRangeFemale: '25-125',
    normalRangePediatric: '25-100',
  },
  {
    name: '24-Hour Urine VMA (Vanillylmandelic Acid)',
    price: 800,
    parameter: 'VMA',
    unit: 'mg/24hr',
    normalRangeMale: '<8',
    normalRangeFemale: '<8',
    normalRangePediatric: '<6',
  },
  {
    name: '24-Hour Urine Metanephrines',
    price: 1000,
    parameter: 'Metanephrines',
    unit: 'µg/24hr',
    normalRangeMale: '<350',
    normalRangeFemale: '<350',
    normalRangePediatric: '<200',
  },
  {
    name: '24-Hour Urine Catecholamines',
    price: 1000,
    parameter: 'Catecholamines',
    unit: 'µg/24hr',
    normalRangeMale: '<100',
    normalRangeFemale: '<100',
    normalRangePediatric: '<50',
  },
  {
    name: '24-Hour Urine 5-HIAA (5-Hydroxyindoleacetic Acid)',
    price: 800,
    parameter: '5-HIAA',
    unit: 'mg/24hr',
    normalRangeMale: '2-8',
    normalRangeFemale: '2-8',
    normalRangePediatric: '2-6',
  },
  {
    name: '24-Hour Urine Copper',
    price: 600,
    parameter: 'Copper',
    unit: 'µg/24hr',
    normalRangeMale: '15-60',
    normalRangeFemale: '15-60',
    normalRangePediatric: '10-40',
  },
  {
    name: '24-Hour Urine Lead',
    price: 600,
    parameter: 'Lead',
    unit: 'µg/24hr',
    normalRangeMale: '<80',
    normalRangeFemale: '<80',
    normalRangePediatric: '<50',
  },
  {
    name: '24-Hour Urine Mercury',
    price: 600,
    parameter: 'Mercury',
    unit: 'µg/24hr',
    normalRangeMale: '<20',
    normalRangeFemale: '<20',
    normalRangePediatric: '<10',
  },
  {
    name: '24-Hour Urine Arsenic',
    price: 600,
    parameter: 'Arsenic',
    unit: 'µg/24hr',
    normalRangeMale: '<50',
    normalRangeFemale: '<50',
    normalRangePediatric: '<30',
  },
  {
    name: '24-Hour Urine Cadmium',
    price: 600,
    parameter: 'Cadmium',
    unit: 'µg/24hr',
    normalRangeMale: '<2',
    normalRangeFemale: '<2',
    normalRangePediatric: '<1',
  },
  {
    name: 'Urine Protein Electrophoresis',
    price: 800,
    parameters: [
      {
        name: 'Albumin',
        unit: '%',
        normalRangeMale: 'Varies',
        normalRangeFemale: 'Varies',
        normalRangePediatric: 'Varies',
      },
      {
        name: 'Alpha-1 Globulin',
        unit: '%',
        normalRangeMale: 'Varies',
        normalRangeFemale: 'Varies',
        normalRangePediatric: 'Varies',
      },
      {
        name: 'Alpha-2 Globulin',
        unit: '%',
        normalRangeMale: 'Varies',
        normalRangeFemale: 'Varies',
        normalRangePediatric: 'Varies',
      },
      {
        name: 'Beta Globulin',
        unit: '%',
        normalRangeMale: 'Varies',
        normalRangeFemale: 'Varies',
        normalRangePediatric: 'Varies',
      },
      {
        name: 'Gamma Globulin',
        unit: '%',
        normalRangeMale: 'Varies',
        normalRangeFemale: 'Varies',
        normalRangePediatric: 'Varies',
      },
    ],
  },
  {
    name: 'Urine Bence Jones Protein',
    price: 500,
    parameter: 'Bence Jones Protein',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Urine Immunofixation',
    price: 800,
    parameter: 'Immunofixation',
    unit: 'Report',
    normalRangeMale: 'No monoclonal band',
    normalRangeFemale: 'No monoclonal band',
    normalRangePediatric: 'No monoclonal band',
  },
  {
    name: 'Urine Beta-2 Microglobulin',
    price: 600,
    parameter: 'Beta-2 Microglobulin',
    unit: 'µg/L',
    normalRangeMale: '<300',
    normalRangeFemale: '<300',
    normalRangePediatric: '<300',
  },
  {
    name: 'Urine NAG (N-Acetylglucosaminidase)',
    price: 500,
    parameter: 'NAG',
    unit: 'U/g Creatinine',
    normalRangeMale: '<5',
    normalRangeFemale: '<5',
    normalRangePediatric: '<5',
  },
  {
    name: 'Urine ACR (Albumin/Creatinine Ratio)',
    price: 400,
    parameters: [
      {
        name: 'Urine Albumin',
        unit: 'mg/L',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
      {
        name: 'Urine Creatinine',
        unit: 'mg/dL',
        normalRangeMale: 'Varies',
        normalRangeFemale: 'Varies',
        normalRangePediatric: 'Varies',
      },
      {
        name: 'Albumin/Creatinine Ratio',
        unit: 'mg/g',
        normalRangeMale: '<30',
        normalRangeFemale: '<30',
        normalRangePediatric: '<30',
        formula: 'ACR = (Albumin in mg/L) / (Creatinine in mg/dL) × 1000',
        dependsOn: ['Urine Albumin', 'Urine Creatinine'],
      },
    ],
  },
  {
    name: 'Urine Myoglobin',
    price: 500,
    parameter: 'Myoglobin',
    unit: 'ng/mL',
    normalRangeMale: '<5',
    normalRangeFemale: '<5',
    normalRangePediatric: '<5',
  },
  {
    name: 'Urine Hemoglobin',
    price: 300,
    parameter: 'Hemoglobin',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Urine Porphobilinogen',
    price: 600,
    parameter: 'Porphobilinogen',
    unit: 'mg/24hr',
    normalRangeMale: '<2',
    normalRangeFemale: '<2',
    normalRangePediatric: '<1',
  },
  {
    name: 'Urine Porphyrins',
    price: 800,
    parameters: [
      {
        name: 'Uroporphyrin',
        unit: 'µg/24hr',
        normalRangeMale: '<40',
        normalRangeFemale: '<40',
        normalRangePediatric: '<30',
      },
      {
        name: 'Coproporphyrin',
        unit: 'µg/24hr',
        normalRangeMale: '<200',
        normalRangeFemale: '<200',
        normalRangePediatric: '<150',
      },
    ],
  },
  {
    name: 'Urine Delta-Aminolevulinic Acid (ALA)',
    price: 600,
    parameter: 'ALA',
    unit: 'mg/24hr',
    normalRangeMale: '<7',
    normalRangeFemale: '<7',
    normalRangePediatric: '<5',
  },
  // Stool Analysis
  {
    name: 'Stool Routine Examination',
    price: 150,
    parameters: [
      {
        name: 'Color',
        unit: 'Report',
        normalRangeMale: 'Brown',
        normalRangeFemale: 'Brown',
        normalRangePediatric: 'Brown',
      },
      {
        name: 'Consistency',
        unit: 'Report',
        normalRangeMale: 'Formed',
        normalRangeFemale: 'Formed',
        normalRangePediatric: 'Formed',
      },
      {
        name: 'Mucus',
        unit: 'Report',
        normalRangeMale: 'Absent',
        normalRangeFemale: 'Absent',
        normalRangePediatric: 'Absent',
      },
      {
        name: 'Blood',
        unit: 'Report',
        normalRangeMale: 'Absent',
        normalRangeFemale: 'Absent',
        normalRangePediatric: 'Absent',
      },
      {
        name: 'Pus Cells',
        unit: '/HPF',
        normalRangeMale: '0-2',
        normalRangeFemale: '0-2',
        normalRangePediatric: '0-2',
      },
      {
        name: 'RBCs',
        unit: '/HPF',
        normalRangeMale: '0',
        normalRangeFemale: '0',
        normalRangePediatric: '0',
      },
      {
        name: 'Parasites',
        unit: 'Report',
        normalRangeMale: 'None seen',
        normalRangeFemale: 'None seen',
        normalRangePediatric: 'None seen',
      },
      {
        name: 'Ova/Cyst',
        unit: 'Report',
        normalRangeMale: 'None seen',
        normalRangeFemale: 'None seen',
        normalRangePediatric: 'None seen',
      },
    ],
  },
  {
    name: 'Stool Occult Blood',
    price: 150,
    parameter: 'Occult Blood',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Stool for Ova and Parasites',
    price: 200,
    parameter: 'Ova and Parasites',
    unit: 'Report',
    normalRangeMale: 'None seen',
    normalRangeFemale: 'None seen',
    normalRangePediatric: 'None seen',
  },
  {
    name: 'Stool Culture and Sensitivity',
    price: 500,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'Normal flora',
        normalRangeFemale: 'Normal flora',
        normalRangePediatric: 'Normal flora',
      },
      {
        name: 'Pathogens',
        unit: 'Report',
        normalRangeMale: 'None isolated',
        normalRangeFemale: 'None isolated',
        normalRangePediatric: 'None isolated',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Stool for Reducing Substances',
    price: 200,
    parameter: 'Reducing Substances',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Stool pH',
    price: 150,
    parameter: 'pH',
    unit: 'pH units',
    normalRangeMale: '7.0-7.5',
    normalRangeFemale: '7.0-7.5',
    normalRangePediatric: '7.0-7.5',
  },
  {
    name: 'Stool Fat (Qualitative)',
    price: 200,
    parameter: 'Fat',
    unit: 'Report',
    normalRangeMale: 'Negative to trace',
    normalRangeFemale: 'Negative to trace',
    normalRangePediatric: 'Negative to trace',
  },
  {
    name: 'Stool Fat (Quantitative - 72hr)',
    price: 500,
    parameter: 'Fat',
    unit: 'g/24hr',
    normalRangeMale: '<7',
    normalRangeFemale: '<7',
    normalRangePediatric: '<5',
  },
  {
    name: 'Stool Elastase',
    price: 600,
    parameter: 'Elastase',
    unit: 'µg/g',
    normalRangeMale: '>200',
    normalRangeFemale: '>200',
    normalRangePediatric: '>200',
  },
  {
    name: 'Stool Calprotectin',
    price: 800,
    parameter: 'Calprotectin',
    unit: 'µg/g',
    normalRangeMale: '<50',
    normalRangeFemale: '<50',
    normalRangePediatric: '<50',
  },
  {
    name: 'Stool Giardia Antigen',
    price: 500,
    parameter: 'Giardia Antigen',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Stool Rotavirus Antigen',
    price: 400,
    parameter: 'Rotavirus Antigen',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Stool Adenovirus Antigen',
    price: 400,
    parameter: 'Adenovirus Antigen',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Stool Clostridium difficile Toxin',
    price: 600,
    parameters: [
      {
        name: 'Toxin A',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Toxin B',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
    ],
  },
  {
    name: 'Stool C. difficile Glutamate Dehydrogenase (GDH)',
    price: 500,
    parameter: 'GDH Antigen',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  // Sputum Analysis
  {
    name: 'Sputum Routine Examination',
    price: 150,
    parameters: [
      {
        name: 'Color',
        unit: 'Report',
        normalRangeMale: 'Mucoid/Colorless',
        normalRangeFemale: 'Mucoid/Colorless',
        normalRangePediatric: 'Mucoid/Colorless',
      },
      {
        name: 'Consistency',
        unit: 'Report',
        normalRangeMale: 'Mucoid',
        normalRangeFemale: 'Mucoid',
        normalRangePediatric: 'Mucoid',
      },
      {
        name: 'Pus Cells',
        unit: '/HPF',
        normalRangeMale: '0-5',
        normalRangeFemale: '0-5',
        normalRangePediatric: '0-5',
      },
      {
        name: 'Epithelial Cells',
        unit: '/HPF',
        normalRangeMale: 'Few',
        normalRangeFemale: 'Few',
        normalRangePediatric: 'Few',
      },
      {
        name: 'RBCs',
        unit: '/HPF',
        normalRangeMale: '0',
        normalRangeFemale: '0',
        normalRangePediatric: '0',
      },
      {
        name: 'Bacteria',
        unit: 'Report',
        normalRangeMale: 'Few commensals',
        normalRangeFemale: 'Few commensals',
        normalRangePediatric: 'Few commensals',
      },
    ],
  },
  {
    name: 'Sputum Culture and Sensitivity',
    price: 500,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'Normal flora',
        normalRangeFemale: 'Normal flora',
        normalRangePediatric: 'Normal flora',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Sputum for AFB (Acid Fast Bacilli)',
    price: 200,
    parameter: 'AFB',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Sputum for AFB (3 Samples)',
    price: 500,
    parameters: [
      {
        name: 'Sample 1 (Early Morning)',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Sample 2 (Early Morning)',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Sample 3 (Early Morning)',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
    ],
  },
  {
    name: 'Sputum CBNAAT (GeneXpert MTB)',
    price: 1500,
    parameters: [
      {
        name: 'MTB Detected',
        unit: 'Report',
        normalRangeMale: 'Not Detected',
        normalRangeFemale: 'Not Detected',
        normalRangePediatric: 'Not Detected',
      },
      {
        name: 'Rifampicin Resistance',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Sputum TB Culture (Liquid)',
    price: 2000,
    parameter: 'Mycobacterium tuberculosis',
    unit: 'Report',
    normalRangeMale: 'No growth',
    normalRangeFemale: 'No growth',
    normalRangePediatric: 'No growth',
  },
  {
    name: 'Sputum TB Culture (LJ Medium)',
    price: 1500,
    parameter: 'Mycobacterium tuberculosis',
    unit: 'Report',
    normalRangeMale: 'No growth',
    normalRangeFemale: 'No growth',
    normalRangePediatric: 'No growth',
  },
  {
    name: 'Sputum Cytology',
    price: 500,
    parameter: 'Cytology',
    unit: 'Report',
    normalRangeMale: 'No malignant cells',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'No malignant cells',
  },
  // Blood Culture
  {
    name: 'Blood Culture (Aerobic)',
    price: 600,
    parameter: 'Aerobic Culture',
    unit: 'Report',
    normalRangeMale: 'No growth',
    normalRangeFemale: 'No growth',
    normalRangePediatric: 'No growth',
  },
  {
    name: 'Blood Culture (Anaerobic)',
    price: 600,
    parameter: 'Anaerobic Culture',
    unit: 'Report',
    normalRangeMale: 'No growth',
    normalRangeFemale: 'No growth',
    normalRangePediatric: 'No growth',
  },
  {
    name: 'Blood Culture (Aerobic + Anaerobic)',
    price: 1000,
    parameters: [
      {
        name: 'Aerobic Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Anaerobic Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Blood Culture (Paediatric Bottle)',
    price: 600,
    parameter: 'Culture',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'N/A',
    normalRangePediatric: 'No growth',
  },
  // Other Cultures
  {
    name: 'Throat Swab Culture and Sensitivity',
    price: 400,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'Normal flora',
        normalRangeFemale: 'Normal flora',
        normalRangePediatric: 'Normal flora',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Throat Swab for Diphtheria',
    price: 400,
    parameter: 'Corynebacterium diphtheriae',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Pus Swab Culture and Sensitivity',
    price: 400,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Wound Swab Culture and Sensitivity',
    price: 400,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Ear Swab Culture and Sensitivity',
    price: 400,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Nasal Swab Culture and Sensitivity',
    price: 400,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'Normal flora',
        normalRangeFemale: 'Normal flora',
        normalRangePediatric: 'Normal flora',
      },
      {
        name: 'MRSA Screen',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'MRSA Screen (Nasal)',
    price: 400,
    parameter: 'MRSA',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Eye Swab Culture and Sensitivity',
    price: 400,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Vaginal Swab Culture and Sensitivity',
    price: 400,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Normal flora',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'High Vaginal Swab (HVS) Culture',
    price: 400,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Normal flora',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Trichomonas',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Candida',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Gardnerella',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Urethral Swab Culture and Sensitivity',
    price: 400,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Gonococcus',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Chlamydia',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
    ],
  },
  {
    name: 'Cervical Swab Culture and Sensitivity',
    price: 400,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Normal flora',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Seminal Fluid Culture and Sensitivity',
    price: 500,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Prostatic Secretion Culture',
    price: 500,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'CSF Culture and Sensitivity',
    price: 600,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Pleural Fluid Culture and Sensitivity',
    price: 500,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Peritoneal Fluid Culture and Sensitivity',
    price: 500,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Synovial Fluid Culture and Sensitivity',
    price: 500,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Ascitic Fluid Culture and Sensitivity',
    price: 500,
    parameters: [
      {
        name: 'Culture',
        unit: 'Report',
        normalRangeMale: 'No growth',
        normalRangeFemale: 'No growth',
        normalRangePediatric: 'No growth',
      },
      {
        name: 'Organism Identified',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sensitivity Pattern',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  // Fungal Cultures
  {
    name: 'Fungal Culture (Skin/Nail)',
    price: 500,
    parameter: 'Fungal Culture',
    unit: 'Report',
    normalRangeMale: 'No growth',
    normalRangeFemale: 'No growth',
    normalRangePediatric: 'No growth',
  },
  {
    name: 'Fungal Culture (Hair)',
    price: 500,
    parameter: 'Fungal Culture',
    unit: 'Report',
    normalRangeMale: 'No growth',
    normalRangeFemale: 'No growth',
    normalRangePediatric: 'No growth',
  },
  {
    name: 'KOH Preparation (Skin Scraping)',
    price: 200,
    parameter: 'KOH Mount',
    unit: 'Report',
    normalRangeMale: 'No fungal elements',
    normalRangeFemale: 'No fungal elements',
    normalRangePediatric: 'No fungal elements',
  },
  {
    name: 'KOH Preparation (Nail)',
    price: 200,
    parameter: 'KOH Mount',
    unit: 'Report',
    normalRangeMale: 'No fungal elements',
    normalRangeFemale: 'No fungal elements',
    normalRangePediatric: 'No fungal elements',
  },
  {
    name: 'KOH Preparation (Hair)',
    price: 200,
    parameter: 'KOH Mount',
    unit: 'Report',
    normalRangeMale: 'No fungal elements',
    normalRangeFemale: 'No fungal elements',
    normalRangePediatric: 'No fungal elements',
  },
  // Body Fluid Analysis
  {
    name: 'CSF Routine Examination',
    price: 400,
    parameters: [
      {
        name: 'Color',
        unit: 'Report',
        normalRangeMale: 'Colorless',
        normalRangeFemale: 'Colorless',
        normalRangePediatric: 'Colorless',
      },
      {
        name: 'Appearance',
        unit: 'Report',
        normalRangeMale: 'Clear',
        normalRangeFemale: 'Clear',
        normalRangePediatric: 'Clear',
      },
      {
        name: 'Total Cell Count',
        unit: '/µL',
        normalRangeMale: '0-5',
        normalRangeFemale: '0-5',
        normalRangePediatric: '0-10',
      },
      {
        name: 'Differential Count',
        unit: 'Report',
        normalRangeMale: 'Lymphocytes predominant',
        normalRangeFemale: 'Lymphocytes predominant',
        normalRangePediatric: 'Lymphocytes predominant',
      },
      {
        name: 'Protein',
        unit: 'mg/dL',
        normalRangeMale: '15-45',
        normalRangeFemale: '15-45',
        normalRangePediatric: '15-45',
        criticalMax: 100,
      },
      {
        name: 'Glucose',
        unit: 'mg/dL',
        normalRangeMale: '40-80 (2/3 of blood glucose)',
        normalRangeFemale: '40-80 (2/3 of blood glucose)',
        normalRangePediatric: '40-80 (2/3 of blood glucose)',
        criticalMin: 20,
      },
      {
        name: 'CSF/Serum Glucose Ratio',
        unit: 'ratio',
        normalRangeMale: '0.5-0.7',
        normalRangeFemale: '0.5-0.7',
        normalRangePediatric: '0.5-0.7',
        formula: 'CSF/Serum Glucose Ratio = CSF Glucose / Serum Glucose',
        dependsOn: ['Glucose'],
      },
    ],
  },
  {
    name: 'Pleural Fluid Analysis',
    price: 400,
    parameters: [
      {
        name: 'Color',
        unit: 'Report',
        normalRangeMale: 'Pale yellow',
        normalRangeFemale: 'Pale yellow',
        normalRangePediatric: 'Pale yellow',
      },
      {
        name: 'Appearance',
        unit: 'Report',
        normalRangeMale: 'Clear',
        normalRangeFemale: 'Clear',
        normalRangePediatric: 'Clear',
      },
      {
        name: 'Total Cell Count',
        unit: '/µL',
        normalRangeMale: '<1000',
        normalRangeFemale: '<1000',
        normalRangePediatric: '<1000',
      },
      {
        name: 'Differential Count',
        unit: 'Report',
        normalRangeMale: 'Varies',
        normalRangeFemale: 'Varies',
        normalRangePediatric: 'Varies',
      },
      {
        name: 'Protein',
        unit: 'g/dL',
        normalRangeMale: '<3',
        normalRangeFemale: '<3',
        normalRangePediatric: '<3',
      },
      {
        name: 'LDH',
        unit: 'U/L',
        normalRangeMale: '<200',
        normalRangeFemale: '<200',
        normalRangePediatric: '<200',
      },
      {
        name: 'Glucose',
        unit: 'mg/dL',
        normalRangeMale: '70-110',
        normalRangeFemale: '70-110',
        normalRangePediatric: '70-110',
      },
      {
        name: 'ADA (Adenosine Deaminase)',
        unit: 'U/L',
        normalRangeMale: '<40',
        normalRangeFemale: '<40',
        normalRangePediatric: '<40',
      },
    ],
  },
  {
    name: 'Peritoneal Fluid Analysis',
    price: 400,
    parameters: [
      {
        name: 'Color',
        unit: 'Report',
        normalRangeMale: 'Pale yellow',
        normalRangeFemale: 'Pale yellow',
        normalRangePediatric: 'Pale yellow',
      },
      {
        name: 'Appearance',
        unit: 'Report',
        normalRangeMale: 'Clear',
        normalRangeFemale: 'Clear',
        normalRangePediatric: 'Clear',
      },
      {
        name: 'Total Cell Count',
        unit: '/µL',
        normalRangeMale: '<500',
        normalRangeFemale: '<500',
        normalRangePediatric: '<500',
      },
      {
        name: 'Protein',
        unit: 'g/dL',
        normalRangeMale: '<3',
        normalRangeFemale: '<3',
        normalRangePediatric: '<3',
      },
      {
        name: 'Albumin',
        unit: 'g/dL',
        normalRangeMale: 'Varies',
        normalRangeFemale: 'Varies',
        normalRangePediatric: 'Varies',
      },
      {
        name: 'SAAG (Serum-Ascites Albumin Gradient)',
        unit: 'g/dL',
        normalRangeMale: '<1.1',
        normalRangeFemale: '<1.1',
        normalRangePediatric: '<1.1',
        formula: 'SAAG = Serum Albumin - Ascitic Fluid Albumin',
        dependsOn: ['Albumin'],
      },
    ],
  },
  {
    name: 'Synovial Fluid Analysis',
    price: 400,
    parameters: [
      {
        name: 'Color',
        unit: 'Report',
        normalRangeMale: 'Pale yellow',
        normalRangeFemale: 'Pale yellow',
        normalRangePediatric: 'Pale yellow',
      },
      {
        name: 'Appearance',
        unit: 'Report',
        normalRangeMale: 'Clear',
        normalRangeFemale: 'Clear',
        normalRangePediatric: 'Clear',
      },
      {
        name: 'Viscosity',
        unit: 'Report',
        normalRangeMale: 'High (string test >4cm)',
        normalRangeFemale: 'High (string test >4cm)',
        normalRangePediatric: 'High (string test >4cm)',
      },
      {
        name: 'Total Cell Count',
        unit: '/µL',
        normalRangeMale: '<200',
        normalRangeFemale: '<200',
        normalRangePediatric: '<200',
      },
      {
        name: 'Differential Count',
        unit: 'Report',
        normalRangeMale: 'Monocytes predominant',
        normalRangeFemale: 'Monocytes predominant',
        normalRangePediatric: 'Monocytes predominant',
      },
      {
        name: 'Crystals',
        unit: 'Report',
        normalRangeMale: 'None',
        normalRangeFemale: 'None',
        normalRangePediatric: 'None',
      },
    ],
  },
  {
    name: 'Pericardial Fluid Analysis',
    price: 400,
    parameters: [
      {
        name: 'Color',
        unit: 'Report',
        normalRangeMale: 'Pale yellow',
        normalRangeFemale: 'Pale yellow',
        normalRangePediatric: 'Pale yellow',
      },
      {
        name: 'Appearance',
        unit: 'Report',
        normalRangeMale: 'Clear',
        normalRangeFemale: 'Clear',
        normalRangePediatric: 'Clear',
      },
      {
        name: 'Total Cell Count',
        unit: '/µL',
        normalRangeMale: '<1000',
        normalRangeFemale: '<1000',
        normalRangePediatric: '<1000',
      },
      {
        name: 'Protein',
        unit: 'g/dL',
        normalRangeMale: '1.5-3.5',
        normalRangeFemale: '1.5-3.5',
        normalRangePediatric: '1.5-3.5',
      },
      {
        name: 'LDH',
        unit: 'U/L',
        normalRangeMale: '<200',
        normalRangeFemale: '<200',
        normalRangePediatric: '<200',
      },
    ],
  },
  // Semen Analysis
  {
    name: 'Semen Analysis',
    price: 400,
    parameters: [
      {
        name: 'Volume',
        unit: 'mL',
        normalRangeMale: '1.5-6.0',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'pH',
        unit: 'pH units',
        normalRangeMale: '7.2-8.0',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sperm Concentration',
        unit: 'million/mL',
        normalRangeMale: '>=15',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Total Sperm Count',
        unit: 'million/ejaculate',
        normalRangeMale: '>=39',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
        formula: 'Total Sperm Count = Sperm Concentration × Volume',
        dependsOn: ['Sperm Concentration', 'Volume'],
      },
      {
        name: 'Motility (Progressive)',
        unit: '%',
        normalRangeMale: '>=32',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Motility (Total)',
        unit: '%',
        normalRangeMale: '>=40',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Vitality (Live Sperm)',
        unit: '%',
        normalRangeMale: '>=58',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Morphology (Normal Forms)',
        unit: '%',
        normalRangeMale: '>=4',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Pus Cells',
        unit: '/HPF',
        normalRangeMale: '<1',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'RBCs',
        unit: '/HPF',
        normalRangeMale: '0',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Liquefaction Time',
        unit: 'minutes',
        normalRangeMale: '<60',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Post-Coital Test',
    price: 400,
    parameters: [
      {
        name: 'Sperm Motility',
        unit: '%',
        normalRangeMale: 'N/A',
        normalRangeFemale: '>=50% with forward progression',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Sperm Count',
        unit: '/HPF',
        normalRangeMale: 'N/A',
        normalRangeFemale: '>10 motile sperm',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Semen Fructose',
    price: 300,
    parameter: 'Fructose',
    unit: 'mg/dL',
    normalRangeMale: '>=13',
    normalRangeFemale: 'N/A',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Sperm DNA Fragmentation Index (DFI)',
    price: 1500,
    parameter: 'DFI',
    unit: '%',
    normalRangeMale: '<25',
    normalRangeFemale: 'N/A',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Anti-Sperm Antibody (ASA)',
    price: 800,
    parameter: 'Anti-Sperm Antibody',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'N/A',
  },
]

export async function seedUrineMicrobiologyTests() {
  let created = 0
  let updated = 0
  
  for (const test of urineMicrobiologyTests) {
    const res = await LabTest.updateOne(
      { name: test.name },
      { $set: test },
      { upsert: true }
    )
    if ((res as any).upsertedId || (res as any).upsertedCount) created++
    else if ((res as any).modifiedCount) updated++
  }
  
  return { total: urineMicrobiologyTests.length, created, updated }
}
