import { LabTest } from '../modules/lab/models/Test'

export const endocrinologyTests = [
  // Adrenal Hormones
  {
    name: 'Serum Cortisol (Morning)',
    price: 500,
    parameter: 'Cortisol (8 AM)',
    unit: 'µg/dL',
    normalRangeMale: '6.2-19.4',
    normalRangeFemale: '6.2-19.4',
    normalRangePediatric: '5-25',
    criticalMin: 3.0,
    criticalMax: 60.0,
  },
  {
    name: 'Serum Cortisol (Evening)',
    price: 500,
    parameter: 'Cortisol (4 PM)',
    unit: 'µg/dL',
    normalRangeMale: '2.3-11.5',
    normalRangeFemale: '2.3-11.5',
    normalRangePediatric: '2-10',
  },
  {
    name: 'Midnight Cortisol',
    price: 600,
    parameter: 'Cortisol (Midnight)',
    unit: 'µg/dL',
    normalRangeMale: '<7.5',
    normalRangeFemale: '<7.5',
    normalRangePediatric: '<5',
  },
  {
    name: 'Salivary Cortisol',
    price: 600,
    parameter: 'Salivary Cortisol',
    unit: 'nmol/L',
    normalRangeMale: '0.5-9.6 (morning)',
    normalRangeFemale: '0.5-9.6 (morning)',
    normalRangePediatric: '0.5-9.6 (morning)',
  },
  {
    name: '24-Hour Urine Free Cortisol',
    price: 800,
    parameter: 'Urine Free Cortisol',
    unit: 'µg/24hr',
    normalRangeMale: '10-100',
    normalRangeFemale: '10-100',
    normalRangePediatric: '5-60',
  },
  {
    name: 'ACTH (Adrenocorticotropic Hormone)',
    price: 800,
    parameter: 'ACTH',
    unit: 'pg/mL',
    normalRangeMale: '7.2-63.3',
    normalRangeFemale: '7.2-63.3',
    normalRangePediatric: '7-60',
  },
  {
    name: 'DHEA-S (Dehydroepiandrosterone Sulfate)',
    price: 600,
    parameter: 'DHEA-S',
    unit: 'µg/dL',
    normalRangeMale: '80-560',
    normalRangeFemale: '35-430',
    normalRangePediatric: 'Varies by age',
  },
  {
    name: '17-Hydroxyprogesterone',
    price: 600,
    parameter: '17-OHP',
    unit: 'ng/dL',
    normalRangeMale: '<220',
    normalRangeFemale: '<220 (follicular); <290 (luteal)',
    normalRangePediatric: '<100',
  },
  {
    name: 'Androstenedione',
    price: 600,
    parameter: 'Androstenedione',
    unit: 'ng/dL',
    normalRangeMale: '50-250',
    normalRangeFemale: '30-250',
    normalRangePediatric: '20-100',
  },
  {
    name: 'Aldosterone (Serum)',
    price: 800,
    parameter: 'Aldosterone',
    unit: 'ng/dL',
    normalRangeMale: '3-16 (upright)',
    normalRangeFemale: '3-16 (upright)',
    normalRangePediatric: '5-50',
  },
  {
    name: 'Aldosterone (24-Hour Urine)',
    price: 800,
    parameter: 'Aldosterone',
    unit: 'µg/24hr',
    normalRangeMale: '3-19',
    normalRangeFemale: '3-19',
    normalRangePediatric: '1-8',
  },
  {
    name: 'Renin Activity',
    price: 800,
    parameter: 'Plasma Renin Activity',
    unit: 'ng/mL/hr',
    normalRangeMale: '0.25-5.82 (upright)',
    normalRangeFemale: '0.25-5.82 (upright)',
    normalRangePediatric: 'Varies',
  },
  {
    name: 'Aldosterone/Renin Ratio',
    price: 1200,
    parameters: [
      {
        name: 'Aldosterone',
        unit: 'ng/dL',
        normalRangeMale: '3-16',
        normalRangeFemale: '3-16',
        normalRangePediatric: '5-50',
      },
      {
        name: 'Plasma Renin Activity',
        unit: 'ng/mL/hr',
        normalRangeMale: '0.25-5.82',
        normalRangeFemale: '0.25-5.82',
        normalRangePediatric: 'Varies',
      },
      {
        name: 'Aldosterone/Renin Ratio',
        unit: 'ratio',
        normalRangeMale: '<30',
        normalRangeFemale: '<30',
        normalRangePediatric: '<30',
        formula: 'ARR = Aldosterone (ng/dL) / Renin (ng/mL/hr)',
        dependsOn: ['Aldosterone', 'Plasma Renin Activity'],
      },
    ],
  },
  // Sex Hormones - Male
  {
    name: 'Serum Testosterone (Total)',
    price: 500,
    parameter: 'Total Testosterone',
    unit: 'ng/dL',
    normalRangeMale: '270-1070',
    normalRangeFemale: '15-70',
    normalRangePediatric: 'Varies by age',
  },
  {
    name: 'Serum Testosterone (Free)',
    price: 600,
    parameter: 'Free Testosterone',
    unit: 'pg/mL',
    normalRangeMale: '50-210',
    normalRangeFemale: '1.0-8.5',
    normalRangePediatric: 'Varies by age',
  },
  {
    name: 'Testosterone (Bioavailable)',
    price: 700,
    parameter: 'Bioavailable Testosterone',
    unit: 'ng/dL',
    normalRangeMale: '110-430',
    normalRangeFemale: '2-25',
    normalRangePediatric: 'Varies by age',
  },
  {
    name: 'Free Androgen Index',
    price: 600,
    parameter: 'FAI',
    unit: 'ratio',
    normalRangeMale: '30-150',
    normalRangeFemale: '0.7-8',
    normalRangePediatric: 'Varies',
  },
  {
    name: 'SHBG (Sex Hormone Binding Globulin)',
    price: 500,
    parameter: 'SHBG',
    unit: 'nmol/L',
    normalRangeMale: '10-50',
    normalRangeFemale: '20-70',
    normalRangePediatric: 'Varies by age',
  },
  {
    name: 'Dihydrotestosterone (DHT)',
    price: 700,
    parameter: 'DHT',
    unit: 'pg/mL',
    normalRangeMale: '250-990',
    normalRangeFemale: '20-60',
    normalRangePediatric: 'Varies',
  },
  {
    name: 'FSH (Follicle Stimulating Hormone)',
    price: 400,
    parameter: 'FSH',
    unit: 'mIU/mL',
    normalRangeMale: '1.5-12.4',
    normalRangeFemale: 'Follicular: 3.5-12.5; Ovulatory: 4.7-21.5; Luteal: 1.7-7.7; Postmenopausal: 25.8-134.8',
    normalRangePediatric: 'Varies by age',
  },
  {
    name: 'LH (Luteinizing Hormone)',
    price: 400,
    parameter: 'LH',
    unit: 'mIU/mL',
    normalRangeMale: '1.7-8.6',
    normalRangeFemale: 'Follicular: 2.4-12.6; Ovulatory: 14-95.6; Luteal: 1-11.4; Postmenopausal: 7.7-58.5',
    normalRangePediatric: 'Varies by age',
  },
  {
    name: 'Prolactin',
    price: 400,
    parameter: 'Prolactin',
    unit: 'ng/mL',
    normalRangeMale: '3-15',
    normalRangeFemale: '4-23',
    normalRangePediatric: '3-20',
  },
  {
    name: 'Inhibin B',
    price: 700,
    parameter: 'Inhibin B',
    unit: 'pg/mL',
    normalRangeMale: '50-350',
    normalRangeFemale: 'Varies (cycle dependent)',
    normalRangePediatric: 'Varies',
  },
  {
    name: 'Anti-Mullerian Hormone (AMH)',
    price: 800,
    parameter: 'AMH',
    unit: 'ng/mL',
    normalRangeMale: '0.7-19',
    normalRangeFemale: '1.0-4.0 (fertile age)',
    normalRangePediatric: 'Varies',
  },
  // Sex Hormones - Female
  {
    name: 'Estradiol (E2)',
    price: 500,
    parameter: 'Estradiol',
    unit: 'pg/mL',
    normalRangeMale: '10-40',
    normalRangeFemale: 'Follicular: 19.5-144.3; Ovulatory: 63.9-356.7; Luteal: 55.8-214.2; Postmenopausal: <32.2',
    normalRangePediatric: 'Varies by age',
  },
  {
    name: 'Estriol (E3)',
    price: 500,
    parameter: 'Estriol',
    unit: 'ng/mL',
    normalRangeMale: '<0.1',
    normalRangeFemale: 'Pregnancy dependent',
    normalRangePediatric: '<0.1',
  },
  {
    name: 'Progesterone',
    price: 500,
    parameter: 'Progesterone',
    unit: 'ng/mL',
    normalRangeMale: '<0.5',
    normalRangeFemale: 'Follicular: <1.5; Luteal: 3-25; Postmenopausal: <0.5',
    normalRangePediatric: '<0.5',
  },
  {
    name: '17-Beta Estradiol',
    price: 500,
    parameter: '17-Beta Estradiol',
    unit: 'pg/mL',
    normalRangeMale: '10-40',
    normalRangeFemale: 'Follicular: 19.5-144.3; Ovulatory: 63.9-356.7; Luteal: 55.8-214.2',
    normalRangePediatric: 'Varies by age',
  },
  {
    name: 'Total Estrogens',
    price: 600,
    parameter: 'Total Estrogens',
    unit: 'pg/mL',
    normalRangeMale: '20-80',
    normalRangeFemale: 'Cycle dependent',
    normalRangePediatric: 'Varies',
  },
  // Fertility Profile
  {
    name: 'Male Fertility Profile',
    price: 2000,
    parameters: [
      {
        name: 'Total Testosterone',
        unit: 'ng/dL',
        normalRangeMale: '270-1070',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'FSH',
        unit: 'mIU/mL',
        normalRangeMale: '1.5-12.4',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'LH',
        unit: 'mIU/mL',
        normalRangeMale: '1.7-8.6',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Prolactin',
        unit: 'ng/mL',
        normalRangeMale: '3-15',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Estradiol',
        unit: 'pg/mL',
        normalRangeMale: '10-40',
        normalRangeFemale: 'N/A',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Female Fertility Profile',
    price: 2500,
    parameters: [
      {
        name: 'FSH',
        unit: 'mIU/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Day 3: 3.5-12.5',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'LH',
        unit: 'mIU/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Day 3: 2.4-12.6',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Estradiol',
        unit: 'pg/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Day 3: 19.5-144.3',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Progesterone',
        unit: 'ng/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Day 21: >10 (ovulatory)',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Prolactin',
        unit: 'ng/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: '4-23',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'TSH',
        unit: 'mIU/L',
        normalRangeMale: 'N/A',
        normalRangeFemale: '0.4-4.0',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'AMH',
        unit: 'ng/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: '1.0-4.0',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  // PCOS Profile
  {
    name: 'PCOS Profile',
    price: 2000,
    parameters: [
      {
        name: 'Total Testosterone',
        unit: 'ng/dL',
        normalRangeMale: 'N/A',
        normalRangeFemale: '15-70',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Free Testosterone',
        unit: 'pg/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: '1.0-8.5',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'DHEA-S',
        unit: 'µg/dL',
        normalRangeMale: 'N/A',
        normalRangeFemale: '35-430',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Androstenedione',
        unit: 'ng/dL',
        normalRangeMale: 'N/A',
        normalRangeFemale: '30-250',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'FSH',
        unit: 'mIU/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: '3.5-12.5',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'LH',
        unit: 'mIU/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: '2.4-12.6',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'LH/FSH Ratio',
        unit: 'ratio',
        normalRangeMale: 'N/A',
        normalRangeFemale: '<2',
        normalRangePediatric: 'N/A',
        formula: 'LH/FSH Ratio = LH / FSH',
        dependsOn: ['LH', 'FSH'],
      },
      {
        name: 'Insulin (Fasting)',
        unit: 'µIU/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: '2.6-24.9',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  // Menopause Profile
  {
    name: 'Menopause Profile',
    price: 1500,
    parameters: [
      {
        name: 'FSH',
        unit: 'mIU/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Postmenopausal: >25',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'LH',
        unit: 'mIU/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Postmenopausal: >20',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Estradiol',
        unit: 'pg/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Postmenopausal: <32',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  // Pituitary Hormones
  {
    name: 'Growth Hormone (GH)',
    price: 600,
    parameter: 'GH',
    unit: 'ng/mL',
    normalRangeMale: '<0.5 (basal)',
    normalRangeFemale: '<0.5 (basal)',
    normalRangePediatric: '<10 (basal)',
  },
  {
    name: 'IGF-1 (Insulin-like Growth Factor 1)',
    price: 700,
    parameter: 'IGF-1',
    unit: 'ng/mL',
    normalRangeMale: '87-280 (age dependent)',
    normalRangeFemale: '87-280 (age dependent)',
    normalRangePediatric: 'Age dependent',
  },
  {
    name: 'IGF-BP3 (IGF Binding Protein 3)',
    price: 700,
    parameter: 'IGF-BP3',
    unit: 'µg/mL',
    normalRangeMale: '2.0-5.0',
    normalRangeFemale: '2.0-5.0',
    normalRangePediatric: '1.5-4.5',
  },
  {
    name: 'ADH (Anti-Diuretic Hormone/Vasopressin)',
    price: 800,
    parameter: 'ADH',
    unit: 'pg/mL',
    normalRangeMale: '1.0-13.0',
    normalRangeFemale: '1.0-13.0',
    normalRangePediatric: '1.0-13.0',
  },
  {
    name: 'Osmolality (Serum)',
    price: 400,
    parameter: 'Osmolality',
    unit: 'mOsm/kg',
    normalRangeMale: '275-295',
    normalRangeFemale: '275-295',
    normalRangePediatric: '275-295',
    criticalMin: 250,
    criticalMax: 320,
  },
  {
    name: 'Osmolality (Urine)',
    price: 400,
    parameter: 'Urine Osmolality',
    unit: 'mOsm/kg',
    normalRangeMale: '50-1400',
    normalRangeFemale: '50-1400',
    normalRangePediatric: '50-1400',
  },
  {
    name: 'Water Deprivation Test',
    price: 1000,
    parameters: [
      {
        name: 'Serum Osmolality (Baseline)',
        unit: 'mOsm/kg',
        normalRangeMale: '275-295',
        normalRangeFemale: '275-295',
        normalRangePediatric: '275-295',
      },
      {
        name: 'Urine Osmolality (Baseline)',
        unit: 'mOsm/kg',
        normalRangeMale: '50-1400',
        normalRangeFemale: '50-1400',
        normalRangePediatric: '50-1400',
      },
      {
        name: 'Urine Osmolality (Post-Deprivation)',
        unit: 'mOsm/kg',
        normalRangeMale: '>800',
        normalRangeFemale: '>800',
        normalRangePediatric: '>800',
      },
      {
        name: 'ADH Response',
        unit: 'Report',
        normalRangeMale: 'Normal response',
        normalRangeFemale: 'Normal response',
        normalRangePediatric: 'Normal response',
      },
    ],
  },
  // Growth Hormone Stimulation Tests
  {
    name: 'GH Stimulation Test (Insulin Tolerance)',
    price: 1500,
    parameters: [
      {
        name: 'GH (Baseline)',
        unit: 'ng/mL',
        normalRangeMale: '<0.5',
        normalRangeFemale: '<0.5',
        normalRangePediatric: '<10',
      },
      {
        name: 'GH (Peak)',
        unit: 'ng/mL',
        normalRangeMale: '>7',
        normalRangeFemale: '>7',
        normalRangePediatric: '>10',
      },
      {
        name: 'Cortisol (Peak)',
        unit: 'µg/dL',
        normalRangeMale: '>18',
        normalRangeFemale: '>18',
        normalRangePediatric: '>18',
      },
    ],
  },
  {
    name: 'GH Stimulation Test (Clonidine)',
    price: 1200,
    parameters: [
      {
        name: 'GH (Baseline)',
        unit: 'ng/mL',
        normalRangeMale: '<0.5',
        normalRangeFemale: '<0.5',
        normalRangePediatric: '<10',
      },
      {
        name: 'GH (Peak)',
        unit: 'ng/mL',
        normalRangeMale: '>7',
        normalRangeFemale: '>7',
        normalRangePediatric: '>10',
      },
    ],
  },
  {
    name: 'GH Stimulation Test (Glucagon)',
    price: 1200,
    parameters: [
      {
        name: 'GH (Baseline)',
        unit: 'ng/mL',
        normalRangeMale: '<0.5',
        normalRangeFemale: '<0.5',
        normalRangePediatric: '<10',
      },
      {
        name: 'GH (Peak)',
        unit: 'ng/mL',
        normalRangeMale: '>7',
        normalRangeFemale: '>7',
        normalRangePediatric: '>10',
      },
    ],
  },
  // Metabolic Hormones
  {
    name: 'Gastrin',
    price: 600,
    parameter: 'Gastrin',
    unit: 'pg/mL',
    normalRangeMale: '<100',
    normalRangeFemale: '<100',
    normalRangePediatric: '<100',
  },
  {
    name: 'Secretin Stimulation Test',
    price: 1500,
    parameters: [
      {
        name: 'Gastrin (Baseline)',
        unit: 'pg/mL',
        normalRangeMale: '<100',
        normalRangeFemale: '<100',
        normalRangePediatric: '<100',
      },
      {
        name: 'Gastrin (Post-Stimulation)',
        unit: 'pg/mL',
        normalRangeMale: '<200',
        normalRangeFemale: '<200',
        normalRangePediatric: '<200',
      },
    ],
  },
  {
    name: 'Glucagon',
    price: 700,
    parameter: 'Glucagon',
    unit: 'pg/mL',
    normalRangeMale: '40-130',
    normalRangeFemale: '40-130',
    normalRangePediatric: '40-130',
  },
  {
    name: 'Pancreatic Polypeptide',
    price: 700,
    parameter: 'Pancreatic Polypeptide',
    unit: 'pg/mL',
    normalRangeMale: '50-200',
    normalRangeFemale: '50-200',
    normalRangePediatric: '50-200',
  },
  {
    name: 'Somatostatin',
    price: 800,
    parameter: 'Somatostatin',
    unit: 'pg/mL',
    normalRangeMale: '<25',
    normalRangeFemale: '<25',
    normalRangePediatric: '<25',
  },
  {
    name: 'VIP (Vasoactive Intestinal Peptide)',
    price: 800,
    parameter: 'VIP',
    unit: 'pg/mL',
    normalRangeMale: '<75',
    normalRangeFemale: '<75',
    normalRangePediatric: '<75',
  },
  // Calcium Metabolism
  {
    name: 'PTH Intact',
    price: 600,
    parameter: 'PTH Intact',
    unit: 'pg/mL',
    normalRangeMale: '15-65',
    normalRangeFemale: '15-65',
    normalRangePediatric: '15-65',
    criticalMax: 500,
  },
  {
    name: 'PTH (Whole Molecule)',
    price: 600,
    parameter: 'PTH Whole',
    unit: 'pg/mL',
    normalRangeMale: '10-55',
    normalRangeFemale: '10-55',
    normalRangePediatric: '10-55',
  },
  {
    name: 'Calcitonin',
    price: 700,
    parameter: 'Calcitonin',
    unit: 'pg/mL',
    normalRangeMale: '<10',
    normalRangeFemale: '<5',
    normalRangePediatric: '<10',
  },
  {
    name: 'Vitamin D (25-OH)',
    price: 600,
    parameter: '25-OH Vitamin D',
    unit: 'ng/mL',
    normalRangeMale: '30-100',
    normalRangeFemale: '30-100',
    normalRangePediatric: '30-100',
    criticalMin: 10,
  },
  {
    name: 'Vitamin D (1,25-Dihydroxy)',
    price: 800,
    parameter: '1,25-(OH)2 Vitamin D',
    unit: 'pg/mL',
    normalRangeMale: '18-64',
    normalRangeFemale: '18-64',
    normalRangePediatric: '18-64',
  },
  // Pregnancy Hormones
  {
    name: 'Beta HCG (Qualitative)',
    price: 300,
    parameter: 'Beta HCG',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Positive in pregnancy',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Beta HCG (Quantitative)',
    price: 500,
    parameter: 'Beta HCG',
    unit: 'mIU/mL',
    normalRangeMale: '<5',
    normalRangeFemale: 'Pregnancy dependent',
    normalRangePediatric: '<5',
  },
  {
    name: 'Double Marker Test (First Trimester Screening)',
    price: 1500,
    parameters: [
      {
        name: 'Beta HCG (Free)',
        unit: 'ng/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Pregnancy dependent',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'PAPP-A',
        unit: 'mIU/L',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Pregnancy dependent',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Risk Assessment',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Low risk',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Triple Marker Test',
    price: 2000,
    parameters: [
      {
        name: 'AFP (Alpha Feto Protein)',
        unit: 'ng/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Pregnancy dependent',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Beta HCG (Free)',
        unit: 'ng/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Pregnancy dependent',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Estriol (Unconjugated)',
        unit: 'ng/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Pregnancy dependent',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Risk Assessment',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Low risk',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'Quadruple Marker Test',
    price: 2500,
    parameters: [
      {
        name: 'AFP (Alpha Feto Protein)',
        unit: 'ng/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Pregnancy dependent',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Beta HCG (Total)',
        unit: 'mIU/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Pregnancy dependent',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Estriol (Unconjugated)',
        unit: 'ng/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Pregnancy dependent',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Inhibin A',
        unit: 'pg/mL',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Pregnancy dependent',
        normalRangePediatric: 'N/A',
      },
      {
        name: 'Risk Assessment',
        unit: 'Report',
        normalRangeMale: 'N/A',
        normalRangeFemale: 'Low risk',
        normalRangePediatric: 'N/A',
      },
    ],
  },
  {
    name: 'PAPP-A (Pregnancy Associated Plasma Protein A)',
    price: 800,
    parameter: 'PAPP-A',
    unit: 'mIU/L',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'Pregnancy dependent',
    normalRangePediatric: 'N/A',
  },
  // Tumor Markers (Endocrine)
  {
    name: 'Chromogranin A',
    price: 800,
    parameter: 'Chromogranin A',
    unit: 'ng/mL',
    normalRangeMale: '<95',
    normalRangeFemale: '<95',
    normalRangePediatric: '<95',
  },
  {
    name: 'Neuron Specific Enolase (NSE)',
    price: 600,
    parameter: 'NSE',
    unit: 'ng/mL',
    normalRangeMale: '<12.5',
    normalRangeFemale: '<12.5',
    normalRangePediatric: '<12.5',
  },
  // Other Hormones
  {
    name: 'Erythropoietin (EPO)',
    price: 700,
    parameter: 'Erythropoietin',
    unit: 'mU/mL',
    normalRangeMale: '2.6-18.5',
    normalRangeFemale: '2.6-18.5',
    normalRangePediatric: '2.6-18.5',
  },
  {
    name: 'Renin (Direct)',
    price: 800,
    parameter: 'Direct Renin',
    unit: 'µIU/mL',
    normalRangeMale: '4.4-46',
    normalRangeFemale: '4.4-46',
    normalRangePediatric: 'Varies',
  },
  {
    name: 'Brain Natriuretic Peptide (BNP)',
    price: 800,
    parameter: 'BNP',
    unit: 'pg/mL',
    normalRangeMale: '<100',
    normalRangeFemale: '<100',
    normalRangePediatric: '<100',
  },
  {
    name: 'NT-proBNP',
    price: 800,
    parameter: 'NT-proBNP',
    unit: 'pg/mL',
    normalRangeMale: '<125',
    normalRangeFemale: '<125',
    normalRangePediatric: '<125',
  },
  {
    name: 'Atrial Natriuretic Peptide (ANP)',
    price: 800,
    parameter: 'ANP',
    unit: 'pg/mL',
    normalRangeMale: '20-80',
    normalRangeFemale: '20-80',
    normalRangePediatric: '20-80',
  },
  {
    name: 'C-Peptide (Fasting)',
    price: 600,
    parameter: 'C-Peptide',
    unit: 'ng/mL',
    normalRangeMale: '0.8-3.1',
    normalRangeFemale: '0.8-3.1',
    normalRangePediatric: '0.8-3.1',
  },
  {
    name: 'C-Peptide (Stimulated)',
    price: 700,
    parameter: 'C-Peptide (Stimulated)',
    unit: 'ng/mL',
    normalRangeMale: '1.5-5.0',
    normalRangeFemale: '1.5-5.0',
    normalRangePediatric: '1.5-5.0',
  },
  {
    name: 'Proinsulin',
    price: 800,
    parameter: 'Proinsulin',
    unit: 'pmol/L',
    normalRangeMale: '2-25',
    normalRangeFemale: '2-25',
    normalRangePediatric: '2-25',
  },
  {
    name: 'Ghrelin',
    price: 800,
    parameter: 'Ghrelin',
    unit: 'pg/mL',
    normalRangeMale: '600-1000',
    normalRangeFemale: '600-1000',
    normalRangePediatric: '600-1000',
  },
  {
    name: 'Leptin',
    price: 700,
    parameter: 'Leptin',
    unit: 'ng/mL',
    normalRangeMale: '1.2-15.0',
    normalRangeFemale: '4.1-25.0',
    normalRangePediatric: 'Varies',
  },
  {
    name: 'Adiponectin',
    price: 700,
    parameter: 'Adiponectin',
    unit: 'µg/mL',
    normalRangeMale: '2-30',
    normalRangeFemale: '4-25',
    normalRangePediatric: '5-30',
  },
  {
    name: 'Resistin',
    price: 700,
    parameter: 'Resistin',
    unit: 'ng/mL',
    normalRangeMale: '3-20',
    normalRangeFemale: '3-20',
    normalRangePediatric: '3-20',
  },
  // Catecholamines and Metabolites
  {
    name: 'Plasma Free Metanephrines',
    price: 1200,
    parameters: [
      {
        name: 'Plasma Free Metanephrine',
        unit: 'pg/mL',
        normalRangeMale: '<90',
        normalRangeFemale: '<90',
        normalRangePediatric: '<90',
      },
      {
        name: 'Plasma Free Normetanephrine',
        unit: 'pg/mL',
        normalRangeMale: '<200',
        normalRangeFemale: '<200',
        normalRangePediatric: '<200',
      },
    ],
  },
  {
    name: 'Plasma Catecholamines',
    price: 1000,
    parameters: [
      {
        name: 'Norepinephrine',
        unit: 'pg/mL',
        normalRangeMale: '80-520',
        normalRangeFemale: '80-520',
        normalRangePediatric: '80-400',
      },
      {
        name: 'Epinephrine',
        unit: 'pg/mL',
        normalRangeMale: '<50',
        normalRangeFemale: '<50',
        normalRangePediatric: '<50',
      },
      {
        name: 'Dopamine',
        unit: 'pg/mL',
        normalRangeMale: '<30',
        normalRangeFemale: '<30',
        normalRangePediatric: '<30',
      },
    ],
  },
  // Bone Markers
  {
    name: 'Osteocalcin',
    price: 600,
    parameter: 'Osteocalcin',
    unit: 'ng/mL',
    normalRangeMale: '3-15',
    normalRangeFemale: '3-15',
    normalRangePediatric: '3-15',
  },
  {
    name: 'Beta-CTx (C-Terminal Telopeptide)',
    price: 800,
    parameter: 'Beta-CTx',
    unit: 'ng/mL',
    normalRangeMale: '0.1-1.0',
    normalRangeFemale: '0.1-1.0',
    normalRangePediatric: '0.1-1.0',
  },
  {
    name: 'P1NP (Procollagen Type 1 N-Terminal Propeptide)',
    price: 800,
    parameter: 'P1NP',
    unit: 'ng/mL',
    normalRangeMale: '22-85',
    normalRangeFemale: '22-85',
    normalRangePediatric: '50-150',
  },
  {
    name: 'NTx (N-Terminal Telopeptide)',
    price: 700,
    parameter: 'NTx',
    unit: 'nmol BCE/mmol Creatinine',
    normalRangeMale: '21-83',
    normalRangeFemale: '21-83',
    normalRangePediatric: '30-150',
  },
]

export async function seedEndocrinologyTests() {
  let created = 0
  let updated = 0
  
  for (const test of endocrinologyTests) {
    const res = await LabTest.updateOne(
      { name: test.name },
      { $set: test },
      { upsert: true }
    )
    if ((res as any).upsertedId || (res as any).upsertedCount) created++
    else if ((res as any).modifiedCount) updated++
  }
  
  return { total: endocrinologyTests.length, created, updated }
}
