import { LabTest } from '../modules/lab/models/Test'

export const immunologyTests = [
  // Immunoglobulins
  {
    name: 'Immunoglobulin Profile (IgG, IgA, IgM)',
    price: 1200,
    parameters: [
      {
        name: 'IgG',
        unit: 'mg/dL',
        normalRangeMale: '700-1600',
        normalRangeFemale: '700-1600',
        normalRangePediatric: '300-1500 (varies by age)',
        criticalMin: 200,
      },
      {
        name: 'IgA',
        unit: 'mg/dL',
        normalRangeMale: '70-400',
        normalRangeFemale: '70-400',
        normalRangePediatric: '20-300 (varies by age)',
      },
      {
        name: 'IgM',
        unit: 'mg/dL',
        normalRangeMale: '40-230',
        normalRangeFemale: '40-230',
        normalRangePediatric: '20-200 (varies by age)',
      },
    ],
  },
  {
    name: 'Immunoglobulin G (IgG)',
    price: 400,
    parameter: 'IgG',
    unit: 'mg/dL',
    normalRangeMale: '700-1600',
    normalRangeFemale: '700-1600',
    normalRangePediatric: '300-1500 (varies by age)',
  },
  {
    name: 'Immunoglobulin A (IgA)',
    price: 400,
    parameter: 'IgA',
    unit: 'mg/dL',
    normalRangeMale: '70-400',
    normalRangeFemale: '70-400',
    normalRangePediatric: '20-300 (varies by age)',
  },
  {
    name: 'Immunoglobulin M (IgM)',
    price: 400,
    parameter: 'IgM',
    unit: 'mg/dL',
    normalRangeMale: '40-230',
    normalRangeFemale: '40-230',
    normalRangePediatric: '20-200 (varies by age)',
  },
  {
    name: 'Immunoglobulin D (IgD)',
    price: 500,
    parameter: 'IgD',
    unit: 'mg/dL',
    normalRangeMale: '0-14',
    normalRangeFemale: '0-14',
    normalRangePediatric: '0-14',
  },
  {
    name: 'Immunoglobulin E (IgE)',
    price: 500,
    parameter: 'IgE',
    unit: 'IU/mL',
    normalRangeMale: '<100',
    normalRangeFemale: '<100',
    normalRangePediatric: '<50',
  },
  {
    name: 'Total IgE',
    price: 500,
    parameter: 'Total IgE',
    unit: 'IU/mL',
    normalRangeMale: '<100',
    normalRangeFemale: '<100',
    normalRangePediatric: '<50',
  },
  {
    name: 'IgG Subclasses',
    price: 1500,
    parameters: [
      {
        name: 'IgG1',
        unit: 'mg/dL',
        normalRangeMale: '380-900',
        normalRangeFemale: '380-900',
        normalRangePediatric: '200-700',
      },
      {
        name: 'IgG2',
        unit: 'mg/dL',
        normalRangeMale: '200-600',
        normalRangeFemale: '200-600',
        normalRangePediatric: '100-400',
      },
      {
        name: 'IgG3',
        unit: 'mg/dL',
        normalRangeMale: '20-100',
        normalRangeFemale: '20-100',
        normalRangePediatric: '15-80',
      },
      {
        name: 'IgG4',
        unit: 'mg/dL',
        normalRangeMale: '5-60',
        normalRangeFemale: '5-60',
        normalRangePediatric: '5-50',
      },
    ],
  },
  // Complement System
  {
    name: 'Complement C3',
    price: 500,
    parameter: 'C3',
    unit: 'mg/dL',
    normalRangeMale: '75-175',
    normalRangeFemale: '75-175',
    normalRangePediatric: '75-175',
  },
  {
    name: 'Complement C4',
    price: 500,
    parameter: 'C4',
    unit: 'mg/dL',
    normalRangeMale: '14-44',
    normalRangeFemale: '14-44',
    normalRangePediatric: '14-44',
  },
  {
    name: 'Total Complement (CH50)',
    price: 600,
    parameter: 'CH50',
    unit: 'U/mL',
    normalRangeMale: '30-75',
    normalRangeFemale: '30-75',
    normalRangePediatric: '30-75',
  },
  {
    name: 'Complement Profile',
    price: 1200,
    parameters: [
      {
        name: 'C3',
        unit: 'mg/dL',
        normalRangeMale: '75-175',
        normalRangeFemale: '75-175',
        normalRangePediatric: '75-175',
      },
      {
        name: 'C4',
        unit: 'mg/dL',
        normalRangeMale: '14-44',
        normalRangeFemale: '14-44',
        normalRangePediatric: '14-44',
      },
      {
        name: 'CH50',
        unit: 'U/mL',
        normalRangeMale: '30-75',
        normalRangeFemale: '30-75',
        normalRangePediatric: '30-75',
      },
    ],
  },
  // Autoimmune Markers
  {
    name: 'ANA (Antinuclear Antibody)',
    price: 500,
    parameter: 'ANA',
    unit: 'Titre',
    normalRangeMale: '<1:80',
    normalRangeFemale: '<1:80',
    normalRangePediatric: '<1:80',
  },
  {
    name: 'ANA Profile',
    price: 2000,
    parameters: [
      {
        name: 'ANA Screen',
        unit: 'Titre',
        normalRangeMale: '<1:80',
        normalRangeFemale: '<1:80',
        normalRangePediatric: '<1:80',
      },
      {
        name: 'Anti-dsDNA',
        unit: 'IU/mL',
        normalRangeMale: '<25',
        normalRangeFemale: '<25',
        normalRangePediatric: '<25',
      },
      {
        name: 'Anti-Sm',
        unit: 'Index',
        normalRangeMale: '<1.0',
        normalRangeFemale: '<1.0',
        normalRangePediatric: '<1.0',
      },
      {
        name: 'Anti-RNP',
        unit: 'Index',
        normalRangeMale: '<1.0',
        normalRangeFemale: '<1.0',
        normalRangePediatric: '<1.0',
      },
      {
        name: 'Anti-SS-A (Ro)',
        unit: 'Index',
        normalRangeMale: '<1.0',
        normalRangeFemale: '<1.0',
        normalRangePediatric: '<1.0',
      },
      {
        name: 'Anti-SS-B (La)',
        unit: 'Index',
        normalRangeMale: '<1.0',
        normalRangeFemale: '<1.0',
        normalRangePediatric: '<1.0',
      },
      {
        name: 'Anti-Scl-70',
        unit: 'Index',
        normalRangeMale: '<1.0',
        normalRangeFemale: '<1.0',
        normalRangePediatric: '<1.0',
      },
      {
        name: 'Anti-Jo-1',
        unit: 'Index',
        normalRangeMale: '<1.0',
        normalRangeFemale: '<1.0',
        normalRangePediatric: '<1.0',
      },
      {
        name: 'Anti-Centromere',
        unit: 'Index',
        normalRangeMale: '<1.0',
        normalRangeFemale: '<1.0',
        normalRangePediatric: '<1.0',
      },
      {
        name: 'Anti-Histone',
        unit: 'Index',
        normalRangeMale: '<1.0',
        normalRangeFemale: '<1.0',
        normalRangePediatric: '<1.0',
      },
    ],
  },
  {
    name: 'Anti-dsDNA',
    price: 600,
    parameter: 'Anti-dsDNA',
    unit: 'IU/mL',
    normalRangeMale: '<25',
    normalRangeFemale: '<25',
    normalRangePediatric: '<25',
  },
  {
    name: 'Anti-Sm Antibody',
    price: 600,
    parameter: 'Anti-Sm',
    unit: 'Index',
    normalRangeMale: '<1.0',
    normalRangeFemale: '<1.0',
    normalRangePediatric: '<1.0',
  },
  {
    name: 'Anti-SS-A (Ro)',
    price: 600,
    parameter: 'Anti-SS-A',
    unit: 'Index',
    normalRangeMale: '<1.0',
    normalRangeFemale: '<1.0',
    normalRangePediatric: '<1.0',
  },
  {
    name: 'Anti-SS-B (La)',
    price: 600,
    parameter: 'Anti-SS-B',
    unit: 'Index',
    normalRangeMale: '<1.0',
    normalRangeFemale: '<1.0',
    normalRangePediatric: '<1.0',
  },
  {
    name: 'Anti-Scl-70',
    price: 600,
    parameter: 'Anti-Scl-70',
    unit: 'Index',
    normalRangeMale: '<1.0',
    normalRangeFemale: '<1.0',
    normalRangePediatric: '<1.0',
  },
  {
    name: 'Anti-Jo-1',
    price: 600,
    parameter: 'Anti-Jo-1',
    unit: 'Index',
    normalRangeMale: '<1.0',
    normalRangeFemale: '<1.0',
    normalRangePediatric: '<1.0',
  },
  {
    name: 'Anti-Centromere Antibody',
    price: 600,
    parameter: 'Anti-Centromere',
    unit: 'Index',
    normalRangeMale: '<1.0',
    normalRangeFemale: '<1.0',
    normalRangePediatric: '<1.0',
  },
  {
    name: 'Anti-CCP (Cyclic Citrullinated Peptide)',
    price: 800,
    parameter: 'Anti-CCP',
    unit: 'U/mL',
    normalRangeMale: '<20',
    normalRangeFemale: '<20',
    normalRangePediatric: '<20',
  },
  {
    name: 'Rheumatoid Factor (RF)',
    price: 300,
    parameter: 'RF',
    unit: 'IU/mL',
    normalRangeMale: '<20',
    normalRangeFemale: '<20',
    normalRangePediatric: '<20',
  },
  {
    name: 'Rheumatoid Arthritis Profile',
    price: 1000,
    parameters: [
      {
        name: 'Rheumatoid Factor (RF)',
        unit: 'IU/mL',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
      {
        name: 'Anti-CCP',
        unit: 'U/mL',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
      {
        name: 'CRP',
        unit: 'mg/L',
        normalRangeMale: '<5',
        normalRangeFemale: '<5',
        normalRangePediatric: '<5',
      },
      {
        name: 'ESR',
        unit: 'mm/hr',
        normalRangeMale: '0-15',
        normalRangeFemale: '0-20',
        normalRangePediatric: '0-10',
      },
    ],
  },
  {
    name: 'Anti-GBM (Glomerular Basement Membrane)',
    price: 800,
    parameter: 'Anti-GBM',
    unit: 'U/mL',
    normalRangeMale: '<5',
    normalRangeFemale: '<5',
    normalRangePediatric: '<5',
  },
  {
    name: 'ANCA (Anti-Neutrophil Cytoplasmic Antibodies)',
    price: 1000,
    parameters: [
      {
        name: 'c-ANCA (PR3)',
        unit: 'U/mL',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
      {
        name: 'p-ANCA (MPO)',
        unit: 'U/mL',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
    ],
  },
  {
    name: 'Anti-Phospholipid Antibody Panel',
    price: 1500,
    parameters: [
      {
        name: 'Anti-Cardiolipin IgG',
        unit: 'GPL U/mL',
        normalRangeMale: '<10',
        normalRangeFemale: '<10',
        normalRangePediatric: '<10',
      },
      {
        name: 'Anti-Cardiolipin IgM',
        unit: 'MPL U/mL',
        normalRangeMale: '<10',
        normalRangeFemale: '<10',
        normalRangePediatric: '<10',
      },
      {
        name: 'Anti-Cardiolipin IgA',
        unit: 'APL U/mL',
        normalRangeMale: '<10',
        normalRangeFemale: '<10',
        normalRangePediatric: '<10',
      },
      {
        name: 'Lupus Anticoagulant',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'Anti-Beta-2 Glycoprotein I IgG',
        unit: 'U/mL',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
      {
        name: 'Anti-Beta-2 Glycoprotein I IgM',
        unit: 'U/mL',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
    ],
  },
  {
    name: 'Anti-Cardiolipin Antibody',
    price: 600,
    parameters: [
      {
        name: 'Anti-Cardiolipin IgG',
        unit: 'GPL U/mL',
        normalRangeMale: '<10',
        normalRangeFemale: '<10',
        normalRangePediatric: '<10',
      },
      {
        name: 'Anti-Cardiolipin IgM',
        unit: 'MPL U/mL',
        normalRangeMale: '<10',
        normalRangeFemale: '<10',
        normalRangePediatric: '<10',
      },
    ],
  },
  {
    name: 'Anti-Mitochondrial Antibody (AMA)',
    price: 600,
    parameter: 'AMA',
    unit: 'Titre',
    normalRangeMale: '<1:20',
    normalRangeFemale: '<1:20',
    normalRangePediatric: '<1:20',
  },
  {
    name: 'Anti-Smooth Muscle Antibody (ASMA)',
    price: 600,
    parameter: 'ASMA',
    unit: 'Titre',
    normalRangeMale: '<1:20',
    normalRangeFemale: '<1:20',
    normalRangePediatric: '<1:20',
  },
  {
    name: 'Anti-Liver Kidney Microsomal (Anti-LKM)',
    price: 700,
    parameter: 'Anti-LKM',
    unit: 'Index',
    normalRangeMale: '<1.0',
    normalRangeFemale: '<1.0',
    normalRangePediatric: '<1.0',
  },
  {
    name: 'Anti-Nuclear Cytoplasmic Antibody (ANCA)',
    price: 800,
    parameters: [
      {
        name: 'c-ANCA',
        unit: 'U/mL',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
      {
        name: 'p-ANCA',
        unit: 'U/mL',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
    ],
  },
  // Inflammatory Markers
  {
    name: 'C-Reactive Protein (CRP)',
    price: 300,
    parameter: 'CRP',
    unit: 'mg/L',
    normalRangeMale: '<5',
    normalRangeFemale: '<5',
    normalRangePediatric: '<5',
    criticalMax: 100,
  },
  {
    name: 'High Sensitivity CRP (hs-CRP)',
    price: 400,
    parameter: 'hs-CRP',
    unit: 'mg/L',
    normalRangeMale: '<1.0',
    normalRangeFemale: '<1.0',
    normalRangePediatric: '<1.0',
  },
  {
    name: 'ESR (Erythrocyte Sedimentation Rate)',
    price: 150,
    parameter: 'ESR',
    unit: 'mm/hr',
    normalRangeMale: '0-15',
    normalRangeFemale: '0-20',
    normalRangePediatric: '0-10',
  },
  {
    name: 'Ferritin',
    price: 400,
    parameter: 'Ferritin',
    unit: 'ng/mL',
    normalRangeMale: '30-400',
    normalRangeFemale: '13-150',
    normalRangePediatric: '7-140',
  },
  {
    name: 'Procalcitonin',
    price: 800,
    parameter: 'Procalcitonin',
    unit: 'ng/mL',
    normalRangeMale: '<0.5',
    normalRangeFemale: '<0.5',
    normalRangePediatric: '<0.5',
  },
  {
    name: 'Serum Amyloid A (SAA)',
    price: 600,
    parameter: 'SAA',
    unit: 'mg/L',
    normalRangeMale: '<3',
    normalRangeFemale: '<3',
    normalRangePediatric: '<3',
  },
  {
    name: 'Interleukin-6 (IL-6)',
    price: 800,
    parameter: 'IL-6',
    unit: 'pg/mL',
    normalRangeMale: '<7',
    normalRangeFemale: '<7',
    normalRangePediatric: '<7',
  },
  {
    name: 'TNF-Alpha',
    price: 800,
    parameter: 'TNF-Alpha',
    unit: 'pg/mL',
    normalRangeMale: '<8',
    normalRangeFemale: '<8',
    normalRangePediatric: '<8',
  },
  // Viral Hepatitis Markers
  {
    name: 'Hepatitis A - Anti HAV IgM',
    price: 500,
    parameter: 'Anti-HAV IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Hepatitis A - Anti HAV Total',
    price: 500,
    parameter: 'Anti-HAV Total',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Hepatitis B Profile',
    price: 2000,
    parameters: [
      {
        name: 'HBsAg',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
      {
        name: 'Anti-HBs',
        unit: 'mIU/mL',
        normalRangeMale: '<10 (Negative)',
        normalRangeFemale: '<10 (Negative)',
        normalRangePediatric: '<10 (Negative)',
      },
      {
        name: 'Anti-HBc Total',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
      {
        name: 'Anti-HBc IgM',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
      {
        name: 'HBeAg',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
      {
        name: 'Anti-HBe',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
    ],
  },
  {
    name: 'HBsAg (Hepatitis B Surface Antigen)',
    price: 300,
    parameter: 'HBsAg',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Anti-HBs (Hepatitis B Surface Antibody)',
    price: 400,
    parameter: 'Anti-HBs',
    unit: 'mIU/mL',
    normalRangeMale: '<10 (Negative)',
    normalRangeFemale: '<10 (Negative)',
    normalRangePediatric: '<10 (Negative)',
  },
  {
    name: 'Anti-HBc Total',
    price: 400,
    parameter: 'Anti-HBc Total',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Anti-HBc IgM',
    price: 500,
    parameter: 'Anti-HBc IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'HBeAg',
    price: 400,
    parameter: 'HBeAg',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Anti-HBe',
    price: 400,
    parameter: 'Anti-HBe',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'HBV DNA Quantitative (Viral Load)',
    price: 2500,
    parameter: 'HBV DNA',
    unit: 'IU/mL',
    normalRangeMale: '<20 (Undetected)',
    normalRangeFemale: '<20 (Undetected)',
    normalRangePediatric: '<20 (Undetected)',
  },
  {
    name: 'Hepatitis C - Anti-HCV',
    price: 400,
    parameter: 'Anti-HCV',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'HCV RNA Quantitative (Viral Load)',
    price: 2500,
    parameter: 'HCV RNA',
    unit: 'IU/mL',
    normalRangeMale: '<15 (Undetected)',
    normalRangeFemale: '<15 (Undetected)',
    normalRangePediatric: '<15 (Undetected)',
  },
  {
    name: 'HCV Genotyping',
    price: 3000,
    parameter: 'HCV Genotype',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'N/A',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Hepatitis D - Anti-HDV',
    price: 600,
    parameter: 'Anti-HDV',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'HDV RNA Quantitative',
    price: 2500,
    parameter: 'HDV RNA',
    unit: 'copies/mL',
    normalRangeMale: '<100 (Undetected)',
    normalRangeFemale: '<100 (Undetected)',
    normalRangePediatric: '<100 (Undetected)',
  },
  {
    name: 'Hepatitis E - Anti-HEV IgM',
    price: 600,
    parameter: 'Anti-HEV IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Hepatitis E - Anti-HEV IgG',
    price: 600,
    parameter: 'Anti-HEV IgG',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  // HIV Testing
  {
    name: 'HIV 1 & 2 Antibodies',
    price: 400,
    parameter: 'HIV 1/2 Ab',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'HIV 1 & 2 Antibodies + p24 Antigen (4th Gen)',
    price: 600,
    parameter: 'HIV Ag/Ab Combo',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'HIV-1 RNA Quantitative (Viral Load)',
    price: 2500,
    parameter: 'HIV-1 RNA',
    unit: 'copies/mL',
    normalRangeMale: '<20 (Undetected)',
    normalRangeFemale: '<20 (Undetected)',
    normalRangePediatric: '<20 (Undetected)',
  },
  {
    name: 'CD4/CD8 Count',
    price: 800,
    parameters: [
      {
        name: 'CD4+ T Cells',
        unit: 'cells/µL',
        normalRangeMale: '500-1500',
        normalRangeFemale: '500-1500',
        normalRangePediatric: '500-1500',
      },
      {
        name: 'CD8+ T Cells',
        unit: 'cells/µL',
        normalRangeMale: '300-900',
        normalRangeFemale: '300-900',
        normalRangePediatric: '300-900',
      },
      {
        name: 'CD4/CD8 Ratio',
        unit: 'ratio',
        normalRangeMale: '1.0-3.0',
        normalRangeFemale: '1.0-3.0',
        normalRangePediatric: '1.0-3.0',
        formula: 'CD4/CD8 Ratio = CD4 Count / CD8 Count',
        dependsOn: ['CD4+ T Cells', 'CD8+ T Cells'],
      },
    ],
  },
  {
    name: 'CD4 Count',
    price: 500,
    parameter: 'CD4+ Count',
    unit: 'cells/µL',
    normalRangeMale: '500-1500',
    normalRangeFemale: '500-1500',
    normalRangePediatric: '500-1500',
  },
  {
    name: 'CD8 Count',
    price: 500,
    parameter: 'CD8+ Count',
    unit: 'cells/µL',
    normalRangeMale: '300-900',
    normalRangeFemale: '300-900',
    normalRangePediatric: '300-900',
  },
  // TORCH Panel
  {
    name: 'TORCH Panel',
    price: 2500,
    parameters: [
      {
        name: 'Toxoplasma IgG',
        unit: 'IU/mL',
        normalRangeMale: '<10 (Negative)',
        normalRangeFemale: '<10 (Negative)',
        normalRangePediatric: '<10 (Negative)',
      },
      {
        name: 'Toxoplasma IgM',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
      {
        name: 'Rubella IgG',
        unit: 'IU/mL',
        normalRangeMale: '<10 (Negative)',
        normalRangeFemale: '<10 (Negative)',
        normalRangePediatric: '<10 (Negative)',
      },
      {
        name: 'Rubella IgM',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
      {
        name: 'CMV IgG',
        unit: 'AU/mL',
        normalRangeMale: '<6 (Negative)',
        normalRangeFemale: '<6 (Negative)',
        normalRangePediatric: '<6 (Negative)',
      },
      {
        name: 'CMV IgM',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
      {
        name: 'HSV-1 IgG',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
      {
        name: 'HSV-1 IgM',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
      {
        name: 'HSV-2 IgG',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
      {
        name: 'HSV-2 IgM',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
    ],
  },
  {
    name: 'Toxoplasma IgG',
    price: 500,
    parameter: 'Toxoplasma IgG',
    unit: 'IU/mL',
    normalRangeMale: '<10 (Negative)',
    normalRangeFemale: '<10 (Negative)',
    normalRangePediatric: '<10 (Negative)',
  },
  {
    name: 'Toxoplasma IgM',
    price: 500,
    parameter: 'Toxoplasma IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Rubella IgG',
    price: 500,
    parameter: 'Rubella IgG',
    unit: 'IU/mL',
    normalRangeMale: '<10 (Negative)',
    normalRangeFemale: '<10 (Negative)',
    normalRangePediatric: '<10 (Negative)',
  },
  {
    name: 'Rubella IgM',
    price: 500,
    parameter: 'Rubella IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'CMV IgG',
    price: 500,
    parameter: 'CMV IgG',
    unit: 'AU/mL',
    normalRangeMale: '<6 (Negative)',
    normalRangeFemale: '<6 (Negative)',
    normalRangePediatric: '<6 (Negative)',
  },
  {
    name: 'CMV IgM',
    price: 500,
    parameter: 'CMV IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Herpes Simplex Virus (HSV) IgG',
    price: 600,
    parameters: [
      {
        name: 'HSV-1 IgG',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
      {
        name: 'HSV-2 IgG',
        unit: 'Index',
        normalRangeMale: '<1.0 (Negative)',
        normalRangeFemale: '<1.0 (Negative)',
        normalRangePediatric: '<1.0 (Negative)',
      },
    ],
  },
  {
    name: 'HSV-1 IgG',
    price: 400,
    parameter: 'HSV-1 IgG',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'HSV-2 IgG',
    price: 400,
    parameter: 'HSV-2 IgG',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  // Other Viral Serology
  {
    name: 'Epstein-Barr Virus (EBV) Profile',
    price: 1500,
    parameters: [
      {
        name: 'VCA IgG',
        unit: 'U/mL',
        normalRangeMale: '<20 (Negative)',
        normalRangeFemale: '<20 (Negative)',
        normalRangePediatric: '<20 (Negative)',
      },
      {
        name: 'VCA IgM',
        unit: 'U/mL',
        normalRangeMale: '<20 (Negative)',
        normalRangeFemale: '<20 (Negative)',
        normalRangePediatric: '<20 (Negative)',
      },
      {
        name: 'EBNA IgG',
        unit: 'U/mL',
        normalRangeMale: '<20 (Negative)',
        normalRangeFemale: '<20 (Negative)',
        normalRangePediatric: '<20 (Negative)',
      },
      {
        name: 'EA IgG',
        unit: 'U/mL',
        normalRangeMale: '<20 (Negative)',
        normalRangeFemale: '<20 (Negative)',
        normalRangePediatric: '<20 (Negative)',
      },
    ],
  },
  {
    name: 'EBV VCA IgG',
    price: 500,
    parameter: 'VCA IgG',
    unit: 'U/mL',
    normalRangeMale: '<20 (Negative)',
    normalRangeFemale: '<20 (Negative)',
    normalRangePediatric: '<20 (Negative)',
  },
  {
    name: 'EBV VCA IgM',
    price: 500,
    parameter: 'VCA IgM',
    unit: 'U/mL',
    normalRangeMale: '<20 (Negative)',
    normalRangeFemale: '<20 (Negative)',
    normalRangePediatric: '<20 (Negative)',
  },
  {
    name: 'EBV EBNA IgG',
    price: 500,
    parameter: 'EBNA IgG',
    unit: 'U/mL',
    normalRangeMale: '<20 (Negative)',
    normalRangeFemale: '<20 (Negative)',
    normalRangePediatric: '<20 (Negative)',
  },
  {
    name: 'Parvovirus B19 IgG',
    price: 600,
    parameter: 'Parvovirus B19 IgG',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Parvovirus B19 IgM',
    price: 600,
    parameter: 'Parvovirus B19 IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Varicella Zoster Virus (VZV) IgG',
    price: 500,
    parameter: 'VZV IgG',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Varicella Zoster Virus (VZV) IgM',
    price: 500,
    parameter: 'VZV IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Measles IgG',
    price: 500,
    parameter: 'Measles IgG',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Mumps IgG',
    price: 500,
    parameter: 'Mumps IgG',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Dengue IgG',
    price: 500,
    parameter: 'Dengue IgG',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Dengue IgM',
    price: 500,
    parameter: 'Dengue IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Dengue NS1 Antigen',
    price: 600,
    parameter: 'Dengue NS1',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Chikungunya IgG',
    price: 500,
    parameter: 'Chikungunya IgG',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Chikungunya IgM',
    price: 500,
    parameter: 'Chikungunya IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'SARS-CoV-2 IgG',
    price: 500,
    parameter: 'COVID-19 IgG',
    unit: 'AU/mL',
    normalRangeMale: '<1.4 (Negative)',
    normalRangeFemale: '<1.4 (Negative)',
    normalRangePediatric: '<1.4 (Negative)',
  },
  {
    name: 'SARS-CoV-2 IgM',
    price: 500,
    parameter: 'COVID-19 IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'COVID-19 RT-PCR',
    price: 800,
    parameter: 'SARS-CoV-2 RNA',
    unit: 'Report',
    normalRangeMale: 'Not Detected',
    normalRangeFemale: 'Not Detected',
    normalRangePediatric: 'Not Detected',
  },
  // Bacterial Serology
  {
    name: 'Widal Test',
    price: 300,
    parameters: [
      {
        name: 'Salmonella Typhi O',
        unit: 'Titre',
        normalRangeMale: '<1:80',
        normalRangeFemale: '<1:80',
        normalRangePediatric: '<1:80',
      },
      {
        name: 'Salmonella Typhi H',
        unit: 'Titre',
        normalRangeMale: '<1:80',
        normalRangeFemale: '<1:80',
        normalRangePediatric: '<1:80',
      },
      {
        name: 'Salmonella Paratyphi A H',
        unit: 'Titre',
        normalRangeMale: '<1:80',
        normalRangeFemale: '<1:80',
        normalRangePediatric: '<1:80',
      },
      {
        name: 'Salmonella Paratyphi B H',
        unit: 'Titre',
        normalRangeMale: '<1:80',
        normalRangeFemale: '<1:80',
        normalRangePediatric: '<1:80',
      },
    ],
  },
  {
    name: 'Typhoid IgM',
    price: 400,
    parameter: 'Typhoid IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Brucella IgG',
    price: 500,
    parameter: 'Brucella IgG',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Brucella IgM',
    price: 500,
    parameter: 'Brucella IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Brucella Agglutination Test',
    price: 400,
    parameter: 'Brucella Titre',
    unit: 'Titre',
    normalRangeMale: '<1:80',
    normalRangeFemale: '<1:80',
    normalRangePediatric: '<1:80',
  },
  {
    name: 'Weil-Felix Test',
    price: 300,
    parameters: [
      {
        name: 'OX-19',
        unit: 'Titre',
        normalRangeMale: '<1:80',
        normalRangeFemale: '<1:80',
        normalRangePediatric: '<1:80',
      },
      {
        name: 'OX-2',
        unit: 'Titre',
        normalRangeMale: '<1:80',
        normalRangeFemale: '<1:80',
        normalRangePediatric: '<1:80',
      },
      {
        name: 'OX-K',
        unit: 'Titre',
        normalRangeMale: '<1:80',
        normalRangeFemale: '<1:80',
        normalRangePediatric: '<1:80',
      },
    ],
  },
  {
    name: 'Leptospira IgM',
    price: 600,
    parameter: 'Leptospira IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Leptospira IgG',
    price: 600,
    parameter: 'Leptospira IgG',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'ASO Titre (Anti-Streptolysin O)',
    price: 300,
    parameter: 'ASO',
    unit: 'IU/mL',
    normalRangeMale: '<200',
    normalRangeFemale: '<200',
    normalRangePediatric: '<200',
  },
  {
    name: 'Anti-DNase B',
    price: 500,
    parameter: 'Anti-DNase B',
    unit: 'U/mL',
    normalRangeMale: '<170',
    normalRangeFemale: '<170',
    normalRangePediatric: '<170',
  },
  {
    name: 'Syphilis (VDRL)',
    price: 200,
    parameter: 'VDRL',
    unit: 'Titre',
    normalRangeMale: 'Non-Reactive',
    normalRangeFemale: 'Non-Reactive',
    normalRangePediatric: 'Non-Reactive',
  },
  {
    name: 'Syphilis (RPR)',
    price: 200,
    parameter: 'RPR',
    unit: 'Titre',
    normalRangeMale: 'Non-Reactive',
    normalRangeFemale: 'Non-Reactive',
    normalRangePediatric: 'Non-Reactive',
  },
  {
    name: 'TPPA (Treponema Pallidum Particle Agglutination)',
    price: 500,
    parameter: 'TPPA',
    unit: 'Titre',
    normalRangeMale: 'Non-Reactive',
    normalRangeFemale: 'Non-Reactive',
    normalRangePediatric: 'Non-Reactive',
  },
  {
    name: 'TPHA (Treponema Pallidum Hemagglutination)',
    price: 500,
    parameter: 'TPHA',
    unit: 'Titre',
    normalRangeMale: 'Non-Reactive',
    normalRangeFemale: 'Non-Reactive',
    normalRangePediatric: 'Non-Reactive',
  },
  {
    name: 'FTA-ABS',
    price: 600,
    parameter: 'FTA-ABS',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Helicobacter Pylori IgG',
    price: 500,
    parameter: 'H. pylori IgG',
    unit: 'U/mL',
    normalRangeMale: '<0.9 (Negative)',
    normalRangeFemale: '<0.9 (Negative)',
    normalRangePediatric: '<0.9 (Negative)',
  },
  {
    name: 'Helicobacter Pylori IgA',
    price: 500,
    parameter: 'H. pylori IgA',
    unit: 'U/mL',
    normalRangeMale: '<0.9 (Negative)',
    normalRangeFemale: '<0.9 (Negative)',
    normalRangePediatric: '<0.9 (Negative)',
  },
  {
    name: 'H. pylori Stool Antigen',
    price: 500,
    parameter: 'H. pylori Antigen',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Chlamydia trachomatis IgG',
    price: 600,
    parameter: 'C. trachomatis IgG',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Chlamydia trachomatis IgM',
    price: 600,
    parameter: 'C. trachomatis IgM',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Mycoplasma pneumoniae IgG',
    price: 600,
    parameter: 'M. pneumoniae IgG',
    unit: 'U/mL',
    normalRangeMale: '<20 (Negative)',
    normalRangeFemale: '<20 (Negative)',
    normalRangePediatric: '<20 (Negative)',
  },
  {
    name: 'Mycoplasma pneumoniae IgM',
    price: 600,
    parameter: 'M. pneumoniae IgM',
    unit: 'U/mL',
    normalRangeMale: '<20 (Negative)',
    normalRangeFemale: '<20 (Negative)',
    normalRangePediatric: '<20 (Negative)',
  },
  {
    name: 'Legionella Urinary Antigen',
    price: 800,
    parameter: 'Legionella Antigen',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Streptococcus pneumoniae Urinary Antigen',
    price: 800,
    parameter: 'S. pneumoniae Antigen',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  // Fungal Serology
  {
    name: 'Aspergillus IgG',
    price: 600,
    parameter: 'Aspergillus IgG',
    unit: 'mg/L',
    normalRangeMale: '<50',
    normalRangeFemale: '<50',
    normalRangePediatric: '<50',
  },
  {
    name: 'Aspergillus IgE',
    price: 600,
    parameter: 'Aspergillus IgE',
    unit: 'kU/L',
    normalRangeMale: '<0.35',
    normalRangeFemale: '<0.35',
    normalRangePediatric: '<0.35',
  },
  {
    name: 'Galactomannan Antigen',
    price: 1000,
    parameter: 'Galactomannan',
    unit: 'Index',
    normalRangeMale: '<0.5',
    normalRangeFemale: '<0.5',
    normalRangePediatric: '<0.5',
  },
  {
    name: 'Cryptococcal Antigen (CrAg)',
    price: 600,
    parameter: 'Cryptococcal Antigen',
    unit: 'Titre',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: '1,3-Beta-D-Glucan',
    price: 1000,
    parameter: 'BDG',
    unit: 'pg/mL',
    normalRangeMale: '<80',
    normalRangeFemale: '<80',
    normalRangePediatric: '<80',
  },
  // Parasitic Serology
  {
    name: 'Malaria Antigen (Rapid)',
    price: 300,
    parameters: [
      {
        name: 'P. falciparum',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
      {
        name: 'P. vivax',
        unit: 'Report',
        normalRangeMale: 'Negative',
        normalRangeFemale: 'Negative',
        normalRangePediatric: 'Negative',
      },
    ],
  },
  {
    name: 'Malaria Parasite (Microscopy)',
    price: 200,
    parameter: 'Malaria Parasite',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Leishmania Antibody',
    price: 600,
    parameter: 'Leishmania Ab',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Entamoeba histolytica Antibody',
    price: 500,
    parameter: 'E. histolytica Ab',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Echinococcus Antibody',
    price: 600,
    parameter: 'Echinococcus Ab',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Cysticercosis Antibody',
    price: 600,
    parameter: 'Cysticercosis Ab',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  {
    name: 'Schistosoma Antibody',
    price: 600,
    parameter: 'Schistosoma Ab',
    unit: 'Index',
    normalRangeMale: '<1.0 (Negative)',
    normalRangeFemale: '<1.0 (Negative)',
    normalRangePediatric: '<1.0 (Negative)',
  },
  // Allergy Testing
  {
    name: 'Allergy Profile (Inhalant)',
    price: 3000,
    parameters: [
      {
        name: 'Dust Mite (D. pteronyssinus)',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Dust Mite (D. farinae)',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Cat Dander',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Dog Dander',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Grass Pollen Mix',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Tree Pollen Mix',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Weed Pollen Mix',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Mold Mix',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Cockroach',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
    ],
  },
  {
    name: 'Allergy Profile (Food)',
    price: 3000,
    parameters: [
      {
        name: 'Milk',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Egg White',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Egg Yolk',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Wheat',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Peanut',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Soybean',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Fish Mix',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Shellfish Mix',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Shrimp',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
      {
        name: 'Crab',
        unit: 'kU/L',
        normalRangeMale: '<0.35',
        normalRangeFemale: '<0.35',
        normalRangePediatric: '<0.35',
      },
    ],
  },
  {
    name: 'Specific IgE (Single Allergen)',
    price: 400,
    parameter: 'Specific IgE',
    unit: 'kU/L',
    normalRangeMale: '<0.35',
    normalRangeFemale: '<0.35',
    normalRangePediatric: '<0.35',
  },
  // Cryoglobulins and Cold Agglutinins
  {
    name: 'Cryoglobulins',
    price: 600,
    parameter: 'Cryoglobulins',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'Cold Agglutinins',
    price: 500,
    parameter: 'Cold Agglutinins',
    unit: 'Titre',
    normalRangeMale: '<1:32',
    normalRangeFemale: '<1:32',
    normalRangePediatric: '<1:32',
  },
  // Celiac Disease
  {
    name: 'Celiac Disease Panel',
    price: 1500,
    parameters: [
      {
        name: 'Anti-Tissue Transglutaminase IgA',
        unit: 'U/mL',
        normalRangeMale: '<4',
        normalRangeFemale: '<4',
        normalRangePediatric: '<4',
      },
      {
        name: 'Anti-Tissue Transglutaminase IgG',
        unit: 'U/mL',
        normalRangeMale: '<4',
        normalRangeFemale: '<4',
        normalRangePediatric: '<4',
      },
      {
        name: 'Anti-Endomysial IgA',
        unit: 'Titre',
        normalRangeMale: '<1:10',
        normalRangeFemale: '<1:10',
        normalRangePediatric: '<1:10',
      },
      {
        name: 'Anti-Gliadin IgA',
        unit: 'U/mL',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
      {
        name: 'Anti-Gliadin IgG',
        unit: 'U/mL',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
      {
        name: 'Total IgA',
        unit: 'mg/dL',
        normalRangeMale: '70-400',
        normalRangeFemale: '70-400',
        normalRangePediatric: '20-300',
      },
    ],
  },
  {
    name: 'Anti-Tissue Transglutaminase (tTG) IgA',
    price: 600,
    parameter: 'Anti-tTG IgA',
    unit: 'U/mL',
    normalRangeMale: '<4',
    normalRangeFemale: '<4',
    normalRangePediatric: '<4',
  },
  {
    name: 'Anti-Endomysial Antibody (EMA)',
    price: 600,
    parameter: 'EMA IgA',
    unit: 'Titre',
    normalRangeMale: '<1:10',
    normalRangeFemale: '<1:10',
    normalRangePediatric: '<1:10',
  },
  {
    name: 'Anti-Gliadin Antibody',
    price: 500,
    parameters: [
      {
        name: 'Anti-Gliadin IgA',
        unit: 'U/mL',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
      {
        name: 'Anti-Gliadin IgG',
        unit: 'U/mL',
        normalRangeMale: '<20',
        normalRangeFemale: '<20',
        normalRangePediatric: '<20',
      },
    ],
  },
  // Vasculitis Markers
  {
    name: 'Cryofibrinogen',
    price: 500,
    parameter: 'Cryofibrinogen',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  // Immune Status
  {
    name: 'Lymphocyte Subset Panel',
    price: 1500,
    parameters: [
      {
        name: 'Total Lymphocytes',
        unit: 'cells/µL',
        normalRangeMale: '1000-4000',
        normalRangeFemale: '1000-4000',
        normalRangePediatric: '1500-6000',
      },
      {
        name: 'CD3+ T Cells',
        unit: 'cells/µL',
        normalRangeMale: '700-2100',
        normalRangeFemale: '700-2100',
        normalRangePediatric: '700-2100',
      },
      {
        name: 'CD4+ T Cells',
        unit: 'cells/µL',
        normalRangeMale: '500-1500',
        normalRangeFemale: '500-1500',
        normalRangePediatric: '500-1500',
      },
      {
        name: 'CD8+ T Cells',
        unit: 'cells/µL',
        normalRangeMale: '300-900',
        normalRangeFemale: '300-900',
        normalRangePediatric: '300-900',
      },
      {
        name: 'CD19+ B Cells',
        unit: 'cells/µL',
        normalRangeMale: '100-500',
        normalRangeFemale: '100-500',
        normalRangePediatric: '100-500',
      },
      {
        name: 'CD16+CD56+ NK Cells',
        unit: 'cells/µL',
        normalRangeMale: '100-500',
        normalRangeFemale: '100-500',
        normalRangePediatric: '100-500',
      },
    ],
  },
  {
    name: 'B-Cell Count (CD19)',
    price: 500,
    parameter: 'CD19+ B Cells',
    unit: 'cells/µL',
    normalRangeMale: '100-500',
    normalRangeFemale: '100-500',
    normalRangePediatric: '100-500',
  },
  {
    name: 'NK Cell Count (CD16/CD56)',
    price: 500,
    parameter: 'NK Cells',
    unit: 'cells/µL',
    normalRangeMale: '100-500',
    normalRangeFemale: '100-500',
    normalRangePediatric: '100-500',
  },
]

export async function seedImmunologyTests() {
  let created = 0
  let updated = 0
  
  for (const test of immunologyTests) {
    const res = await LabTest.updateOne(
      { name: test.name },
      { $set: test },
      { upsert: true }
    )
    if ((res as any).upsertedId || (res as any).upsertedCount) created++
    else if ((res as any).modifiedCount) updated++
  }
  
  return { total: immunologyTests.length, created, updated }
}
