import { LabTest } from '../modules/lab/models/Test'

export const specialTests = [
  // Histopathology
  {
    name: 'Histopathology (Small Biopsy)',
    price: 800,
    parameter: 'Histopathology Report',
    unit: 'Report',
    normalRangeMale: 'No malignancy',
    normalRangeFemale: 'No malignancy',
    normalRangePediatric: 'No malignancy',
  },
  {
    name: 'Histopathology (Large Biopsy)',
    price: 1500,
    parameter: 'Histopathology Report',
    unit: 'Report',
    normalRangeMale: 'No malignancy',
    normalRangeFemale: 'No malignancy',
    normalRangePediatric: 'No malignancy',
  },
  {
    name: 'Histopathology (Whole Organ)',
    price: 2500,
    parameter: 'Histopathology Report',
    unit: 'Report',
    normalRangeMale: 'No malignancy',
    normalRangeFemale: 'No malignancy',
    normalRangePediatric: 'No malignancy',
  },
  {
    name: 'Skin Biopsy',
    price: 1000,
    parameter: 'Skin Histopathology',
    unit: 'Report',
    normalRangeMale: 'Normal histology',
    normalRangeFemale: 'Normal histology',
    normalRangePediatric: 'Normal histology',
  },
  {
    name: 'Liver Biopsy',
    price: 2000,
    parameter: 'Liver Histopathology',
    unit: 'Report',
    normalRangeMale: 'Normal histology',
    normalRangeFemale: 'Normal histology',
    normalRangePediatric: 'Normal histology',
  },
  {
    name: 'Kidney Biopsy',
    price: 2000,
    parameter: 'Kidney Histopathology',
    unit: 'Report',
    normalRangeMale: 'Normal histology',
    normalRangeFemale: 'Normal histology',
    normalRangePediatric: 'Normal histology',
  },
  {
    name: 'Endometrial Biopsy',
    price: 1000,
    parameter: 'Endometrial Histopathology',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'Proliferative/Secretory pattern',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Cervical Biopsy',
    price: 1000,
    parameter: 'Cervical Histopathology',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'No dysplasia/malignancy',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Prostate Biopsy',
    price: 1500,
    parameter: 'Prostate Histopathology',
    unit: 'Report',
    normalRangeMale: 'No malignancy',
    normalRangeFemale: 'N/A',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Breast Biopsy',
    price: 1500,
    parameter: 'Breast Histopathology',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'No malignancy',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Thyroid Biopsy',
    price: 1200,
    parameter: 'Thyroid Histopathology',
    unit: 'Report',
    normalRangeMale: 'No malignancy',
    normalRangeFemale: 'No malignancy',
    normalRangePediatric: 'No malignancy',
  },
  {
    name: 'Lymph Node Biopsy',
    price: 1500,
    parameter: 'Lymph Node Histopathology',
    unit: 'Report',
    normalRangeMale: 'Reactive/Normal architecture',
    normalRangeFemale: 'Reactive/Normal architecture',
    normalRangePediatric: 'Reactive/Normal architecture',
  },
  {
    name: 'Bone Biopsy',
    price: 2000,
    parameter: 'Bone Histopathology',
    unit: 'Report',
    normalRangeMale: 'Normal bone architecture',
    normalRangeFemale: 'Normal bone architecture',
    normalRangePediatric: 'Normal bone architecture',
  },
  {
    name: 'Muscle Biopsy',
    price: 1500,
    parameter: 'Muscle Histopathology',
    unit: 'Report',
    normalRangeMale: 'Normal muscle fibers',
    normalRangeFemale: 'Normal muscle fibers',
    normalRangePediatric: 'Normal muscle fibers',
  },
  {
    name: 'Nerve Biopsy',
    price: 1500,
    parameter: 'Nerve Histopathology',
    unit: 'Report',
    normalRangeMale: 'Normal nerve architecture',
    normalRangeFemale: 'Normal nerve architecture',
    normalRangePediatric: 'Normal nerve architecture',
  },
  {
    name: 'Lung Biopsy',
    price: 2000,
    parameter: 'Lung Histopathology',
    unit: 'Report',
    normalRangeMale: 'No malignancy',
    normalRangeFemale: 'No malignancy',
    normalRangePediatric: 'No malignancy',
  },
  {
    name: 'Gastrointestinal Biopsy',
    price: 1000,
    parameter: 'GI Histopathology',
    unit: 'Report',
    normalRangeMale: 'Normal mucosa',
    normalRangeFemale: 'Normal mucosa',
    normalRangePediatric: 'Normal mucosa',
  },
  {
    name: 'Colon Biopsy',
    price: 1000,
    parameter: 'Colon Histopathology',
    unit: 'Report',
    normalRangeMale: 'Normal colonic mucosa',
    normalRangeFemale: 'Normal colonic mucosa',
    normalRangePediatric: 'Normal colonic mucosa',
  },
  {
    name: 'Gastric Biopsy',
    price: 1000,
    parameter: 'Gastric Histopathology',
    unit: 'Report',
    normalRangeMale: 'Normal gastric mucosa',
    normalRangeFemale: 'Normal gastric mucosa',
    normalRangePediatric: 'Normal gastric mucosa',
  },
  {
    name: 'Oral Biopsy',
    price: 800,
    parameter: 'Oral Histopathology',
    unit: 'Report',
    normalRangeMale: 'Normal oral mucosa',
    normalRangeFemale: 'Normal oral mucosa',
    normalRangePediatric: 'Normal oral mucosa',
  },
  // Cytology
  {
    name: 'Fine Needle Aspiration Cytology (FNAC)',
    price: 500,
    parameter: 'FNAC Report',
    unit: 'Report',
    normalRangeMale: 'No malignant cells',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'No malignant cells',
  },
  {
    name: 'FNAC Thyroid',
    price: 600,
    parameter: 'Thyroid FNAC',
    unit: 'Report',
    normalRangeMale: 'Benign colloid nodule',
    normalRangeFemale: 'Benign colloid nodule',
    normalRangePediatric: 'Benign colloid nodule',
  },
  {
    name: 'FNAC Breast',
    price: 600,
    parameter: 'Breast FNAC',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'Benign breast tissue',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'FNAC Lymph Node',
    price: 600,
    parameter: 'Lymph Node FNAC',
    unit: 'Report',
    normalRangeMale: 'Reactive lymphoid cells',
    normalRangeFemale: 'Reactive lymphoid cells',
    normalRangePediatric: 'Reactive lymphoid cells',
  },
  {
    name: 'FNAC Salivary Gland',
    price: 600,
    parameter: 'Salivary Gland FNAC',
    unit: 'Report',
    normalRangeMale: 'Normal salivary gland cells',
    normalRangeFemale: 'Normal salivary gland cells',
    normalRangePediatric: 'Normal salivary gland cells',
  },
  {
    name: 'Pap Smear (Conventional)',
    price: 400,
    parameter: 'Pap Smear',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'Negative for intraepithelial lesion',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Pap Smear (Liquid Based Cytology)',
    price: 600,
    parameter: 'LBC Pap Smear',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'Negative for intraepithelial lesion',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Urine Cytology',
    price: 400,
    parameter: 'Urine Cytology',
    unit: 'Report',
    normalRangeMale: 'No malignant cells',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'No malignant cells',
  },
  {
    name: 'Pleural Fluid Cytology',
    price: 500,
    parameter: 'Pleural Fluid Cytology',
    unit: 'Report',
    normalRangeMale: 'No malignant cells',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'No malignant cells',
  },
  {
    name: 'Peritoneal Fluid Cytology',
    price: 500,
    parameter: 'Peritoneal Fluid Cytology',
    unit: 'Report',
    normalRangeMale: 'No malignant cells',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'No malignant cells',
  },
  {
    name: 'CSF Cytology',
    price: 500,
    parameter: 'CSF Cytology',
    unit: 'Report',
    normalRangeMale: 'No malignant cells',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'No malignant cells',
  },
  {
    name: 'Sputum Cytology',
    price: 400,
    parameter: 'Sputum Cytology',
    unit: 'Report',
    normalRangeMale: 'No malignant cells',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'No malignant cells',
  },
  {
    name: 'Bronchial Washing Cytology',
    price: 500,
    parameter: 'Bronchial Washing Cytology',
    unit: 'Report',
    normalRangeMale: 'No malignant cells',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'No malignant cells',
  },
  {
    name: 'Bronchial Brushing Cytology',
    price: 500,
    parameter: 'Bronchial Brushing Cytology',
    unit: 'Report',
    normalRangeMale: 'No malignant cells',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'No malignant cells',
  },
  {
    name: 'Nipple Discharge Cytology',
    price: 400,
    parameter: 'Nipple Discharge Cytology',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'Ascitic Fluid Cytology',
    price: 500,
    parameter: 'Ascitic Fluid Cytology',
    unit: 'Report',
    normalRangeMale: 'No malignant cells',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'No malignant cells',
  },
  {
    name: 'Pericardial Fluid Cytology',
    price: 500,
    parameter: 'Pericardial Fluid Cytology',
    unit: 'Report',
    normalRangeMale: 'No malignant cells',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'No malignant cells',
  },
  {
    name: 'Synovial Fluid Cytology',
    price: 400,
    parameter: 'Synovial Fluid Cytology',
    unit: 'Report',
    normalRangeMale: 'No malignant cells',
    normalRangeFemale: 'No malignant cells',
    normalRangePediatric: 'No malignant cells',
  },
  // Immunohistochemistry (IHC)
  {
    name: 'IHC - ER (Estrogen Receptor)',
    price: 1500,
    parameter: 'ER Status',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'Positive/Negative',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'IHC - PR (Progesterone Receptor)',
    price: 1500,
    parameter: 'PR Status',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'Positive/Negative',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'IHC - HER2/neu',
    price: 2000,
    parameter: 'HER2 Status',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'Score 0, 1+, 2+, 3+',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'IHC - Ki-67',
    price: 1500,
    parameter: 'Ki-67 Index',
    unit: '%',
    normalRangeMale: '<5%',
    normalRangeFemale: '<5%',
    normalRangePediatric: '<5%',
  },
  {
    name: 'IHC - p53',
    price: 1500,
    parameter: 'p53 Status',
    unit: 'Report',
    normalRangeMale: 'Wild type pattern',
    normalRangeFemale: 'Wild type pattern',
    normalRangePediatric: 'Wild type pattern',
  },
  {
    name: 'IHC - CD45 (LCA)',
    price: 1500,
    parameter: 'CD45',
    unit: 'Report',
    normalRangeMale: 'Positive in lymphoid cells',
    normalRangeFemale: 'Positive in lymphoid cells',
    normalRangePediatric: 'Positive in lymphoid cells',
  },
  {
    name: 'IHC - CD20',
    price: 1500,
    parameter: 'CD20',
    unit: 'Report',
    normalRangeMale: 'B-cell marker',
    normalRangeFemale: 'B-cell marker',
    normalRangePediatric: 'B-cell marker',
  },
  {
    name: 'IHC - CD3',
    price: 1500,
    parameter: 'CD3',
    unit: 'Report',
    normalRangeMale: 'T-cell marker',
    normalRangeFemale: 'T-cell marker',
    normalRangePediatric: 'T-cell marker',
  },
  {
    name: 'IHC - CD4',
    price: 1500,
    parameter: 'CD4',
    unit: 'Report',
    normalRangeMale: 'Helper T-cell marker',
    normalRangeFemale: 'Helper T-cell marker',
    normalRangePediatric: 'Helper T-cell marker',
  },
  {
    name: 'IHC - CD8',
    price: 1500,
    parameter: 'CD8',
    unit: 'Report',
    normalRangeMale: 'Cytotoxic T-cell marker',
    normalRangeFemale: 'Cytotoxic T-cell marker',
    normalRangePediatric: 'Cytotoxic T-cell marker',
  },
  {
    name: 'IHC - CD5',
    price: 1500,
    parameter: 'CD5',
    unit: 'Report',
    normalRangeMale: 'T-cell marker',
    normalRangeFemale: 'T-cell marker',
    normalRangePediatric: 'T-cell marker',
  },
  {
    name: 'IHC - CD10',
    price: 1500,
    parameter: 'CD10',
    unit: 'Report',
    normalRangeMale: 'CALLA',
    normalRangeFemale: 'CALLA',
    normalRangePediatric: 'CALLA',
  },
  {
    name: 'IHC - CD30',
    price: 1500,
    parameter: 'CD30',
    unit: 'Report',
    normalRangeMale: 'Activated lymphocytes',
    normalRangeFemale: 'Activated lymphocytes',
    normalRangePediatric: 'Activated lymphocytes',
  },
  {
    name: 'IHC - CD56',
    price: 1500,
    parameter: 'CD56',
    unit: 'Report',
    normalRangeMale: 'NK cell marker',
    normalRangeFemale: 'NK cell marker',
    normalRangePediatric: 'NK cell marker',
  },
  {
    name: 'IHC - CD34',
    price: 1500,
    parameter: 'CD34',
    unit: 'Report',
    normalRangeMale: 'Vascular/progenitor cell marker',
    normalRangeFemale: 'Vascular/progenitor cell marker',
    normalRangePediatric: 'Vascular/progenitor cell marker',
  },
  {
    name: 'IHC - CD31',
    price: 1500,
    parameter: 'CD31',
    unit: 'Report',
    normalRangeMale: 'Vascular marker',
    normalRangeFemale: 'Vascular marker',
    normalRangePediatric: 'Vascular marker',
  },
  {
    name: 'IHC - Cytokeratin (AE1/AE3)',
    price: 1500,
    parameter: 'Cytokeratin',
    unit: 'Report',
    normalRangeMale: 'Epithelial marker',
    normalRangeFemale: 'Epithelial marker',
    normalRangePediatric: 'Epithelial marker',
  },
  {
    name: 'IHC - CK7',
    price: 1500,
    parameter: 'CK7',
    unit: 'Report',
    normalRangeMale: 'Epithelial marker',
    normalRangeFemale: 'Epithelial marker',
    normalRangePediatric: 'Epithelial marker',
  },
  {
    name: 'IHC - CK20',
    price: 1500,
    parameter: 'CK20',
    unit: 'Report',
    normalRangeMale: 'Epithelial marker',
    normalRangeFemale: 'Epithelial marker',
    normalRangePediatric: 'Epithelial marker',
  },
  {
    name: 'IHC - EMA (Epithelial Membrane Antigen)',
    price: 1500,
    parameter: 'EMA',
    unit: 'Report',
    normalRangeMale: 'Epithelial marker',
    normalRangeFemale: 'Epithelial marker',
    normalRangePediatric: 'Epithelial marker',
  },
  {
    name: 'IHC - Vimentin',
    price: 1500,
    parameter: 'Vimentin',
    unit: 'Report',
    normalRangeMale: 'Mesenchymal marker',
    normalRangeFemale: 'Mesenchymal marker',
    normalRangePediatric: 'Mesenchymal marker',
  },
  {
    name: 'IHC - S-100',
    price: 1500,
    parameter: 'S-100',
    unit: 'Report',
    normalRangeMale: 'Neural/melanocytic marker',
    normalRangeFemale: 'Neural/melanocytic marker',
    normalRangePediatric: 'Neural/melanocytic marker',
  },
  {
    name: 'IHC - HMB-45',
    price: 1500,
    parameter: 'HMB-45',
    unit: 'Report',
    normalRangeMale: 'Melanocytic marker',
    normalRangeFemale: 'Melanocytic marker',
    normalRangePediatric: 'Melanocytic marker',
  },
  {
    name: 'IHC - Melan-A',
    price: 1500,
    parameter: 'Melan-A',
    unit: 'Report',
    normalRangeMale: 'Melanocytic marker',
    normalRangeFemale: 'Melanocytic marker',
    normalRangePediatric: 'Melanocytic marker',
  },
  {
    name: 'IHC - Synaptophysin',
    price: 1500,
    parameter: 'Synaptophysin',
    unit: 'Report',
    normalRangeMale: 'Neuroendocrine marker',
    normalRangeFemale: 'Neuroendocrine marker',
    normalRangePediatric: 'Neuroendocrine marker',
  },
  {
    name: 'IHC - Chromogranin',
    price: 1500,
    parameter: 'Chromogranin',
    unit: 'Report',
    normalRangeMale: 'Neuroendocrine marker',
    normalRangeFemale: 'Neuroendocrine marker',
    normalRangePediatric: 'Neuroendocrine marker',
  },
  {
    name: 'IHC - PSA',
    price: 1500,
    parameter: 'PSA',
    unit: 'Report',
    normalRangeMale: 'Prostatic marker',
    normalRangeFemale: 'N/A',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'IHC - TTF-1',
    price: 1500,
    parameter: 'TTF-1',
    unit: 'Report',
    normalRangeMale: 'Lung/thyroid marker',
    normalRangeFemale: 'Lung/thyroid marker',
    normalRangePediatric: 'Lung/thyroid marker',
  },
  {
    name: 'IHC - Thyroglobulin',
    price: 1500,
    parameter: 'Thyroglobulin',
    unit: 'Report',
    normalRangeMale: 'Thyroid marker',
    normalRangeFemale: 'Thyroid marker',
    normalRangePediatric: 'Thyroid marker',
  },
  {
    name: 'IHC - Calcitonin',
    price: 1500,
    parameter: 'Calcitonin',
    unit: 'Report',
    normalRangeMale: 'Medullary thyroid carcinoma marker',
    normalRangeFemale: 'Medullary thyroid carcinoma marker',
    normalRangePediatric: 'Medullary thyroid carcinoma marker',
  },
  {
    name: 'IHC - Desmin',
    price: 1500,
    parameter: 'Desmin',
    unit: 'Report',
    normalRangeMale: 'Muscle marker',
    normalRangeFemale: 'Muscle marker',
    normalRangePediatric: 'Muscle marker',
  },
  {
    name: 'IHC - Myogenin',
    price: 1500,
    parameter: 'Myogenin',
    unit: 'Report',
    normalRangeMale: 'Skeletal muscle marker',
    normalRangeFemale: 'Skeletal muscle marker',
    normalRangePediatric: 'Skeletal muscle marker',
  },
  {
    name: 'IHC - SMA (Smooth Muscle Actin)',
    price: 1500,
    parameter: 'SMA',
    unit: 'Report',
    normalRangeMale: 'Smooth muscle marker',
    normalRangeFemale: 'Smooth muscle marker',
    normalRangePediatric: 'Smooth muscle marker',
  },
  {
    name: 'IHC - MyoD1',
    price: 1500,
    parameter: 'MyoD1',
    unit: 'Report',
    normalRangeMale: 'Skeletal muscle marker',
    normalRangeFemale: 'Skeletal muscle marker',
    normalRangePediatric: 'Skeletal muscle marker',
  },
  {
    name: 'IHC - GFAP',
    price: 1500,
    parameter: 'GFAP',
    unit: 'Report',
    normalRangeMale: 'Glial marker',
    normalRangeFemale: 'Glial marker',
    normalRangePediatric: 'Glial marker',
  },
  {
    name: 'IHC - NSE',
    price: 1500,
    parameter: 'NSE',
    unit: 'Report',
    normalRangeMale: 'Neuroendocrine marker',
    normalRangeFemale: 'Neuroendocrine marker',
    normalRangePediatric: 'Neuroendocrine marker',
  },
  // Molecular Diagnostics
  {
    name: 'BRCA1/BRCA2 Mutation Analysis',
    price: 15000,
    parameter: 'BRCA Mutation',
    unit: 'Report',
    normalRangeMale: 'No pathogenic mutation',
    normalRangeFemale: 'No pathogenic mutation',
    normalRangePediatric: 'No pathogenic mutation',
  },
  {
    name: 'KRAS Mutation Analysis',
    price: 5000,
    parameter: 'KRAS Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'NRAS Mutation Analysis',
    price: 5000,
    parameter: 'NRAS Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'EGFR Mutation Analysis',
    price: 6000,
    parameter: 'EGFR Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'BRAF V600E Mutation Analysis',
    price: 5000,
    parameter: 'BRAF Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'ALK Gene Rearrangement',
    price: 6000,
    parameter: 'ALK Rearrangement',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'ROS1 Gene Rearrangement',
    price: 6000,
    parameter: 'ROS1 Rearrangement',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'NTRK Gene Fusion',
    price: 8000,
    parameter: 'NTRK Fusion',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'HER2 Gene Amplification (FISH)',
    price: 8000,
    parameter: 'HER2 FISH',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'Not amplified',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'PDL1 Expression (IHC)',
    price: 6000,
    parameter: 'PDL1',
    unit: 'TPS/CPS Score',
    normalRangeMale: '<1%',
    normalRangeFemale: '<1%',
    normalRangePediatric: '<1%',
  },
  {
    name: 'MSI (Microsatellite Instability) Testing',
    price: 5000,
    parameter: 'MSI Status',
    unit: 'Report',
    normalRangeMale: 'MSS (Stable)',
    normalRangeFemale: 'MSS (Stable)',
    normalRangePediatric: 'MSS (Stable)',
  },
  {
    name: 'MMR (Mismatch Repair) IHC Panel',
    price: 6000,
    parameters: [
      {
        name: 'MLH1',
        unit: 'Report',
        normalRangeMale: 'Intact',
        normalRangeFemale: 'Intact',
        normalRangePediatric: 'Intact',
      },
      {
        name: 'MSH2',
        unit: 'Report',
        normalRangeMale: 'Intact',
        normalRangeFemale: 'Intact',
        normalRangePediatric: 'Intact',
      },
      {
        name: 'MSH6',
        unit: 'Report',
        normalRangeMale: 'Intact',
        normalRangeFemale: 'Intact',
        normalRangePediatric: 'Intact',
      },
      {
        name: 'PMS2',
        unit: 'Report',
        normalRangeMale: 'Intact',
        normalRangeFemale: 'Intact',
        normalRangePediatric: 'Intact',
      },
    ],
  },
  {
    name: 'BCR-ABL (Philadelphia Chromosome)',
    price: 4000,
    parameter: 'BCR-ABL',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'BCR-ABL Quantitative (RT-PCR)',
    price: 5000,
    parameter: 'BCR-ABL %',
    unit: '%',
    normalRangeMale: '<0.01%',
    normalRangeFemale: '<0.01%',
    normalRangePediatric: '<0.01%',
  },
  {
    name: 'JAK2 V617F Mutation',
    price: 4000,
    parameter: 'JAK2 Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'CALR Mutation Analysis',
    price: 4000,
    parameter: 'CALR Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'MPL Mutation Analysis',
    price: 4000,
    parameter: 'MPL Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'FLT3 Mutation Analysis',
    price: 5000,
    parameter: 'FLT3 Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'NPM1 Mutation Analysis',
    price: 4000,
    parameter: 'NPM1 Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'CEBPA Mutation Analysis',
    price: 4000,
    parameter: 'CEBPA Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'IDH1/IDH2 Mutation Analysis',
    price: 5000,
    parameter: 'IDH Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'TP53 Mutation Analysis',
    price: 6000,
    parameter: 'TP53 Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'Cystic Fibrosis Mutation Panel',
    price: 8000,
    parameter: 'CFTR Mutations',
    unit: 'Report',
    normalRangeMale: 'No mutation detected',
    normalRangeFemale: 'No mutation detected',
    normalRangePediatric: 'No mutation detected',
  },
  {
    name: 'Factor V Leiden Mutation',
    price: 3000,
    parameter: 'Factor V Leiden',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'Prothrombin G20210A Mutation',
    price: 3000,
    parameter: 'Prothrombin Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'MTHFR Mutation Analysis',
    price: 3000,
    parameter: 'MTHFR Mutation',
    unit: 'Report',
    normalRangeMale: 'Wild type',
    normalRangeFemale: 'Wild type',
    normalRangePediatric: 'Wild type',
  },
  {
    name: 'HLA-B27',
    price: 2000,
    parameter: 'HLA-B27',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'HLA-B5701',
    price: 2500,
    parameter: 'HLA-B5701',
    unit: 'Report',
    normalRangeMale: 'Negative',
    normalRangeFemale: 'Negative',
    normalRangePediatric: 'Negative',
  },
  {
    name: 'HLA Typing (Low Resolution)',
    price: 5000,
    parameter: 'HLA Typing',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'N/A',
    normalRangePediatric: 'N/A',
  },
  {
    name: 'HLA Typing (High Resolution)',
    price: 10000,
    parameter: 'HLA Typing',
    unit: 'Report',
    normalRangeMale: 'N/A',
    normalRangeFemale: 'N/A',
    normalRangePediatric: 'N/A',
  },
  // Flow Cytometry
  {
    name: 'Flow Cytometry (Leukemia Panel)',
    price: 5000,
    parameter: 'Leukemia Immunophenotyping',
    unit: 'Report',
    normalRangeMale: 'No abnormal population',
    normalRangeFemale: 'No abnormal population',
    normalRangePediatric: 'No abnormal population',
  },
  {
    name: 'Flow Cytometry (Lymphoma Panel)',
    price: 5000,
    parameter: 'Lymphoma Immunophenotyping',
    unit: 'Report',
    normalRangeMale: 'No abnormal population',
    normalRangeFemale: 'No abnormal population',
    normalRangePediatric: 'No abnormal population',
  },
  {
    name: 'Flow Cytometry (CD Markers)',
    price: 3000,
    parameter: 'CD Marker Analysis',
    unit: 'Report',
    normalRangeMale: 'Normal distribution',
    normalRangeFemale: 'Normal distribution',
    normalRangePediatric: 'Normal distribution',
  },
  {
    name: 'Flow Cytometry (Paroxysmal Nocturnal Hemoglobinuria)',
    price: 4000,
    parameters: [
      {
        name: 'CD55',
        unit: '%',
        normalRangeMale: 'Normal expression',
        normalRangeFemale: 'Normal expression',
        normalRangePediatric: 'Normal expression',
      },
      {
        name: 'CD59',
        unit: '%',
        normalRangeMale: 'Normal expression',
        normalRangeFemale: 'Normal expression',
        normalRangePediatric: 'Normal expression',
      },
      {
        name: 'FLAER',
        unit: '%',
        normalRangeMale: 'Normal expression',
        normalRangeFemale: 'Normal expression',
        normalRangePediatric: 'Normal expression',
      },
    ],
  },
  // Special Chemistry
  {
    name: 'Serum Protein Electrophoresis (SPEP)',
    price: 800,
    parameters: [
      {
        name: 'Albumin',
        unit: 'g/dL',
        normalRangeMale: '3.5-5.5',
        normalRangeFemale: '3.5-5.5',
        normalRangePediatric: '3.5-5.5',
      },
      {
        name: 'Alpha-1 Globulin',
        unit: 'g/dL',
        normalRangeMale: '0.1-0.4',
        normalRangeFemale: '0.1-0.4',
        normalRangePediatric: '0.1-0.4',
      },
      {
        name: 'Alpha-2 Globulin',
        unit: 'g/dL',
        normalRangeMale: '0.5-1.0',
        normalRangeFemale: '0.5-1.0',
        normalRangePediatric: '0.5-1.0',
      },
      {
        name: 'Beta Globulin',
        unit: 'g/dL',
        normalRangeMale: '0.6-1.2',
        normalRangeFemale: '0.6-1.2',
        normalRangePediatric: '0.6-1.2',
      },
      {
        name: 'Gamma Globulin',
        unit: 'g/dL',
        normalRangeMale: '0.7-1.6',
        normalRangeFemale: '0.7-1.6',
        normalRangePediatric: '0.7-1.6',
      },
    ],
  },
  {
    name: 'Urine Protein Electrophoresis (UPEP)',
    price: 800,
    parameter: 'Urine Protein Electrophoresis',
    unit: 'Report',
    normalRangeMale: 'No monoclonal band',
    normalRangeFemale: 'No monoclonal band',
    normalRangePediatric: 'No monoclonal band',
  },
  {
    name: 'Serum Immunofixation',
    price: 1000,
    parameter: 'Immunofixation',
    unit: 'Report',
    normalRangeMale: 'No monoclonal band',
    normalRangeFemale: 'No monoclonal band',
    normalRangePediatric: 'No monoclonal band',
  },
  {
    name: 'Serum Free Light Chains',
    price: 1200,
    parameters: [
      {
        name: 'Free Kappa',
        unit: 'mg/L',
        normalRangeMale: '3.3-19.4',
        normalRangeFemale: '3.3-19.4',
        normalRangePediatric: '3.3-19.4',
      },
      {
        name: 'Free Lambda',
        unit: 'mg/L',
        normalRangeMale: '5.7-26.3',
        normalRangeFemale: '5.7-26.3',
        normalRangePediatric: '5.7-26.3',
      },
      {
        name: 'Kappa/Lambda Ratio',
        unit: 'ratio',
        normalRangeMale: '0.26-1.65',
        normalRangeFemale: '0.26-1.65',
        normalRangePediatric: '0.26-1.65',
        formula: 'Ratio = Free Kappa / Free Lambda',
        dependsOn: ['Free Kappa', 'Free Lambda'],
      },
    ],
  },
  {
    name: 'Beta-2 Microglobulin (Serum)',
    price: 600,
    parameter: 'Beta-2 Microglobulin',
    unit: 'mg/L',
    normalRangeMale: '0.7-3.4',
    normalRangeFemale: '0.7-3.4',
    normalRangePediatric: '0.7-3.4',
  },
  // Trace Elements and Vitamins
  {
    name: 'Vitamin A (Retinol)',
    price: 500,
    parameter: 'Vitamin A',
    unit: 'µg/dL',
    normalRangeMale: '20-60',
    normalRangeFemale: '20-60',
    normalRangePediatric: '20-50',
  },
  {
    name: 'Vitamin B1 (Thiamine)',
    price: 600,
    parameter: 'Thiamine',
    unit: 'nmol/L',
    normalRangeMale: '70-180',
    normalRangeFemale: '70-180',
    normalRangePediatric: '70-180',
  },
  {
    name: 'Vitamin B2 (Riboflavin)',
    price: 600,
    parameter: 'Riboflavin',
    unit: 'nmol/L',
    normalRangeMale: '100-400',
    normalRangeFemale: '100-400',
    normalRangePediatric: '100-400',
  },
  {
    name: 'Vitamin B3 (Niacin)',
    price: 600,
    parameter: 'Niacin',
    unit: 'nmol/L',
    normalRangeMale: '20-50',
    normalRangeFemale: '20-50',
    normalRangePediatric: '20-50',
  },
  {
    name: 'Vitamin B5 (Pantothenic Acid)',
    price: 600,
    parameter: 'Pantothenic Acid',
    unit: 'µg/dL',
    normalRangeMale: '50-150',
    normalRangeFemale: '50-150',
    normalRangePediatric: '50-150',
  },
  {
    name: 'Vitamin B6 (Pyridoxine)',
    price: 600,
    parameter: 'Vitamin B6',
    unit: 'nmol/L',
    normalRangeMale: '20-120',
    normalRangeFemale: '20-120',
    normalRangePediatric: '20-120',
  },
  {
    name: 'Vitamin B7 (Biotin)',
    price: 600,
    parameter: 'Biotin',
    unit: 'ng/dL',
    normalRangeMale: '100-400',
    normalRangeFemale: '100-400',
    normalRangePediatric: '100-400',
  },
  {
    name: 'Vitamin B9 (Folate)',
    price: 400,
    parameter: 'Folate',
    unit: 'ng/mL',
    normalRangeMale: '3.1-20.5',
    normalRangeFemale: '3.1-20.5',
    normalRangePediatric: '3.1-20.5',
  },
  {
    name: 'Vitamin B12',
    price: 500,
    parameter: 'Vitamin B12',
    unit: 'pg/mL',
    normalRangeMale: '200-900',
    normalRangeFemale: '200-900',
    normalRangePediatric: '200-900',
  },
  {
    name: 'Vitamin C (Ascorbic Acid)',
    price: 500,
    parameter: 'Vitamin C',
    unit: 'mg/dL',
    normalRangeMale: '0.4-1.5',
    normalRangeFemale: '0.4-1.5',
    normalRangePediatric: '0.4-1.5',
  },
  {
    name: 'Vitamin D (25-OH)',
    price: 600,
    parameter: '25-OH Vitamin D',
    unit: 'ng/mL',
    normalRangeMale: '30-100',
    normalRangeFemale: '30-100',
    normalRangePediatric: '30-100',
  },
  {
    name: 'Vitamin E (Tocopherol)',
    price: 500,
    parameter: 'Vitamin E',
    unit: 'mg/L',
    normalRangeMale: '5-18',
    normalRangeFemale: '5-18',
    normalRangePediatric: '5-15',
  },
  {
    name: 'Vitamin K',
    price: 600,
    parameter: 'Vitamin K',
    unit: 'ng/mL',
    normalRangeMale: '0.15-1.0',
    normalRangeFemale: '0.15-1.0',
    normalRangePediatric: '0.15-1.0',
  },
  {
    name: 'Serum Copper',
    price: 400,
    parameter: 'Copper',
    unit: 'µg/dL',
    normalRangeMale: '70-140',
    normalRangeFemale: '80-155',
    normalRangePediatric: '80-140',
  },
  {
    name: 'Serum Zinc',
    price: 400,
    parameter: 'Zinc',
    unit: 'µg/dL',
    normalRangeMale: '70-120',
    normalRangeFemale: '70-120',
    normalRangePediatric: '70-120',
  },
  {
    name: 'Serum Selenium',
    price: 600,
    parameter: 'Selenium',
    unit: 'µg/L',
    normalRangeMale: '70-150',
    normalRangeFemale: '70-150',
    normalRangePediatric: '70-150',
  },
  {
    name: 'Serum Manganese',
    price: 600,
    parameter: 'Manganese',
    unit: 'µg/L',
    normalRangeMale: '0.4-1.1',
    normalRangeFemale: '0.4-1.1',
    normalRangePediatric: '0.4-1.1',
  },
  {
    name: 'Serum Chromium',
    price: 600,
    parameter: 'Chromium',
    unit: 'µg/L',
    normalRangeMale: '<0.5',
    normalRangeFemale: '<0.5',
    normalRangePediatric: '<0.5',
  },
  {
    name: 'Serum Molybdenum',
    price: 600,
    parameter: 'Molybdenum',
    unit: 'µg/L',
    normalRangeMale: '0.1-3.0',
    normalRangeFemale: '0.1-3.0',
    normalRangePediatric: '0.1-3.0',
  },
  {
    name: 'Serum Iodine',
    price: 600,
    parameter: 'Iodine',
    unit: 'µg/L',
    normalRangeMale: '40-92',
    normalRangeFemale: '40-92',
    normalRangePediatric: '40-92',
  },
  {
    name: 'Red Cell Folate',
    price: 500,
    parameter: 'RBC Folate',
    unit: 'ng/mL RBC',
    normalRangeMale: '140-628',
    normalRangeFemale: '140-628',
    normalRangePediatric: '140-628',
  },
  // Drug Levels
  {
    name: 'Serum Digoxin Level',
    price: 500,
    parameter: 'Digoxin',
    unit: 'ng/mL',
    normalRangeMale: '0.5-2.0',
    normalRangeFemale: '0.5-2.0',
    normalRangePediatric: '0.5-2.0',
    criticalMax: 2.5,
  },
  {
    name: 'Serum Phenytoin Level',
    price: 500,
    parameter: 'Phenytoin',
    unit: 'µg/mL',
    normalRangeMale: '10-20',
    normalRangeFemale: '10-20',
    normalRangePediatric: '10-20',
    criticalMax: 30,
  },
  {
    name: 'Serum Carbamazepine Level',
    price: 500,
    parameter: 'Carbamazepine',
    unit: 'µg/mL',
    normalRangeMale: '4-12',
    normalRangeFemale: '4-12',
    normalRangePediatric: '4-12',
  },
  {
    name: 'Serum Valproic Acid Level',
    price: 500,
    parameter: 'Valproic Acid',
    unit: 'µg/mL',
    normalRangeMale: '50-100',
    normalRangeFemale: '50-100',
    normalRangePediatric: '50-100',
    criticalMax: 150,
  },
  {
    name: 'Serum Phenobarbital Level',
    price: 500,
    parameter: 'Phenobarbital',
    unit: 'µg/mL',
    normalRangeMale: '15-40',
    normalRangeFemale: '15-40',
    normalRangePediatric: '15-40',
  },
  {
    name: 'Serum Lithium Level',
    price: 500,
    parameter: 'Lithium',
    unit: 'mmol/L',
    normalRangeMale: '0.6-1.2',
    normalRangeFemale: '0.6-1.2',
    normalRangePediatric: '0.6-1.2',
    criticalMax: 1.5,
  },
  {
    name: 'Serum Theophylline Level',
    price: 500,
    parameter: 'Theophylline',
    unit: 'µg/mL',
    normalRangeMale: '10-20',
    normalRangeFemale: '10-20',
    normalRangePediatric: '10-20',
  },
  {
    name: 'Serum Vancomycin Level (Trough)',
    price: 600,
    parameter: 'Vancomycin (Trough)',
    unit: 'µg/mL',
    normalRangeMale: '10-20',
    normalRangeFemale: '10-20',
    normalRangePediatric: '10-20',
  },
  {
    name: 'Serum Vancomycin Level (Peak)',
    price: 600,
    parameter: 'Vancomycin (Peak)',
    unit: 'µg/mL',
    normalRangeMale: '20-40',
    normalRangeFemale: '20-40',
    normalRangePediatric: '20-40',
  },
  {
    name: 'Serum Gentamicin Level (Trough)',
    price: 600,
    parameter: 'Gentamicin (Trough)',
    unit: 'µg/mL',
    normalRangeMale: '<2',
    normalRangeFemale: '<2',
    normalRangePediatric: '<2',
  },
  {
    name: 'Serum Gentamicin Level (Peak)',
    price: 600,
    parameter: 'Gentamicin (Peak)',
    unit: 'µg/mL',
    normalRangeMale: '5-10',
    normalRangeFemale: '5-10',
    normalRangePediatric: '5-10',
  },
  {
    name: 'Serum Amikacin Level (Trough)',
    price: 600,
    parameter: 'Amikacin (Trough)',
    unit: 'µg/mL',
    normalRangeMale: '<5',
    normalRangeFemale: '<5',
    normalRangePediatric: '<5',
  },
  {
    name: 'Serum Amikacin Level (Peak)',
    price: 600,
    parameter: 'Amikacin (Peak)',
    unit: 'µg/mL',
    normalRangeMale: '20-35',
    normalRangeFemale: '20-35',
    normalRangePediatric: '20-35',
  },
  {
    name: 'Serum Cyclosporine Level',
    price: 800,
    parameter: 'Cyclosporine',
    unit: 'ng/mL',
    normalRangeMale: '100-400',
    normalRangeFemale: '100-400',
    normalRangePediatric: '100-400',
  },
  {
    name: 'Serum Tacrolimus Level',
    price: 800,
    parameter: 'Tacrolimus',
    unit: 'ng/mL',
    normalRangeMale: '5-20',
    normalRangeFemale: '5-20',
    normalRangePediatric: '5-20',
  },
  {
    name: 'Serum Sirolimus Level',
    price: 800,
    parameter: 'Sirolimus',
    unit: 'ng/mL',
    normalRangeMale: '4-20',
    normalRangeFemale: '4-20',
    normalRangePediatric: '4-20',
  },
  {
    name: 'Serum Methotrexate Level',
    price: 600,
    parameter: 'Methotrexate',
    unit: 'µmol/L',
    normalRangeMale: '<0.1 (at 48hr)',
    normalRangeFemale: '<0.1 (at 48hr)',
    normalRangePediatric: '<0.1 (at 48hr)',
    criticalMax: 1.0,
  },
]

export async function seedSpecialTests() {
  let created = 0
  let updated = 0
  
  for (const test of specialTests) {
    const res = await LabTest.updateOne(
      { name: test.name },
      { $set: test },
      { upsert: true }
    )
    if ((res as any).upsertedId || (res as any).upsertedCount) created++
    else if ((res as any).modifiedCount) updated++
  }
  
  return { total: specialTests.length, created, updated }
}
