import { useEffect, useMemo, useState, useCallback, useRef, type ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'
import Hospital_TokenSlip, { type TokenSlipData } from '../../components/hospital/Hospital_TokenSlip'
import { hospitalApi, corporateApi } from '../../utils/api'
import { previewHospitalRxPdf } from '../../utils/hospitalRxPdf'
import Toast, { type ToastState } from '../../components/ui/Toast'
import { createCacheKey, getCache, setCache, invalidateCache } from '../../utils/apiCache'
import {
  Ticket,
  Clock,
  RefreshCw,
  Filter,
  Search,
  FileSpreadsheet,
  FileDown,
  Wallet,
  CreditCard,
  TrendingUp,
  ShieldCheck,
  ChevronLeft,
  ChevronRight,
  Printer,
  LayoutDashboard,
  UserCheck,
  UserX,
  CalendarDays,
} from 'lucide-react'

function escHtml(v: any){
  return String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' } as any)[c] || c)
}

function buildTokenHistoryPdfHtml({
  title,
  printedAt,
  hospital,
  filters,
  rows,
}: {
  title: string
  printedAt: Date
  hospital: { name: string; address?: string; phone?: string; logoDataUrl?: string }
  filters: string
  rows: Array<{ date?: string; time?: string; tokenNo?: string; mrNo?: string; patient?: string; phone?: string; doctor?: string; department?: string; fee?: any; isCorporate?: boolean; paidMethod?: string; status?: string }>
}){
  const printedDate = printedAt.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
  const printedTime = printedAt.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })
  const head = ['Date','Time','Type','Token #','MR #','Patient','Phone','Doctor','Department','Fee','Status']
  const th = head.map(h => `<th>${escHtml(h)}</th>`).join('')
  const body = (rows || []).map(r => {
    const method = String(r.paidMethod || '').toLowerCase()
    const t = r.isCorporate ? 'Corporate' : (method === 'bank' || method === 'card' ? 'Card' : 'Cash')
    const fee = Number(r.fee || 0)
    return `<tr>
      <td>${escHtml(r.date || '')}</td>
      <td>${escHtml(r.time || '')}</td>
      <td>${escHtml(t)}</td>
      <td>${escHtml(r.tokenNo || '')}</td>
      <td>${escHtml(r.mrNo || '')}</td>
      <td>${escHtml(r.patient || '')}</td>
      <td>${escHtml(r.phone || '')}</td>
      <td>${escHtml(r.doctor || '')}</td>
      <td>${escHtml(r.department || '')}</td>
      <td class="right">${escHtml(`Rs ${fee.toFixed(0)}`)}</td>
      <td>${escHtml(r.status || '')}</td>
    </tr>`
  }).join('')
  const empty = `<tr><td class="empty" colspan="${head.length}">No rows</td></tr>`

  return `<!doctype html>
  <html>
    <head>
      <meta charset="utf-8"/>
      <title>${escHtml(title)}</title>
      <style>
        @page { size: A4 landscape; margin: 10mm }
        *{ box-sizing:border-box }
        body{ font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial; color:#0f172a; line-height:1.35; font-size:11px }
        .header{ border:1px solid #e2e8f0; border-radius:10px; padding:12px; margin-bottom:10px }
        .hdr{ display:grid; grid-template-columns: 70px 1fr 70px; align-items:center; gap:10px }
        .logo{ width:60px; height:60px; object-fit:contain }
        .hname{ font-size:16px; font-weight:800; text-align:center }
        .hmeta{ font-size:11px; text-align:center; color:#475569 }
        .title{ margin-top:8px; font-size:14px; font-weight:800 }
        .meta{ margin-top:4px; display:flex; justify-content:space-between; gap:12px; color:#334155 }
        table{ width:100%; border-collapse:collapse; table-layout:fixed }
        th,td{ border:1px solid #e2e8f0; padding:6px 6px; vertical-align:top; word-wrap:break-word }
        th{ background:#f8fafc; font-weight:800; color:#334155 }
        td.right, th.right{ text-align:right }
        .empty{ text-align:center; color:#64748b; padding:10px }
        .footer{ margin-top:10px; color:#94a3b8; font-size:10px; text-align:center }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="hdr">
          <div>${hospital.logoDataUrl ? `<img class="logo" src="${hospital.logoDataUrl}" />` : ''}</div>
          <div>
            <div class="hname">${escHtml(hospital.name || 'Hospital')}</div>
            <div class="hmeta">${escHtml(hospital.address || '')}${hospital.phone ? ` • Ph: ${escHtml(hospital.phone)}` : ''}</div>
          </div>
          <div></div>
        </div>
        <div class="title">${escHtml(title)}</div>
        <div class="meta">
          <div><b>Filters:</b> ${escHtml(filters || '-')}</div>
          <div><b>Printed:</b> ${escHtml(printedDate)} ${escHtml(printedTime)}</div>
        </div>
      </div>

      <table>
        <thead><tr>${th}</tr></thead>
        <tbody>${body || empty}</tbody>
      </table>

      <div class="footer">Generated by Hospital Management System</div>
    </body>
  </html>`
}

interface TokenRow {
  _id: string
  date: string
  time: string
  tokenNo: string
  mrNo: string
  patient: string
  doctorId?: string
  performedBy?: string
  guardianRel?: string
  guardianName?: string
  cnic?: string
  visitCategory?: 'public' | 'private'
  gender?: string
  phone?: string
  address?: string
  age?: string
  doctor?: string
  department?: string
  fee: number
  discount: number
  status: 'queued'|'in-progress'|'completed'|'returned'|'cancelled'
  paidMethod?: 'Cash'|'Bank'|'AR'|string
  isCorporate?: boolean
  corporateId?: string
  createdAt?: string
}

export default function Hospital_TokenHistory() {
  const navigate = useNavigate()
  const [query, setQuery] = useState('')
  const [rowsPerPage, setRowsPerPage] = useState<number>(10)
  const [page, setPage] = useState(1)
  const [actioningId, setActioningId] = useState<string | null>(null)
  const [revByMethod, setRevByMethod] = useState<{ cash: number; card: number }>({ cash: 0, card: 0 })
  const [backendTotal, setBackendTotal] = useState(0)
  const [isLoading, setIsLoading] = useState(false)
  const [forceRefresh, setForceRefresh] = useState(0)
  const hasLoadedRef = useRef(false)

  const today = new Date().toISOString().slice(0,10)
  const [from, setFrom] = useState(today)
  const [to, setTo] = useState(today)
  const [department, setDepartment] = useState<string>('All')
  const [doctor, setDoctor] = useState<string>('All')
  const [departments, setDepartments] = useState<any[]>([])
  const [doctors, setDoctors] = useState<any[]>([])
  const [companies, setCompanies] = useState<Array<{ id: string; name: string }>>([])
  const [rows, setRows] = useState<TokenRow[]>([])
  const [showSlip, setShowSlip] = useState(false)
  const [slipData, setSlipData] = useState<TokenSlipData | null>(null)
  const [toast, setToast] = useState<ToastState>(null)
  const [tokenType, setTokenType] = useState<'All' | 'Cash' | 'Corporate'>('All')
  const [visitCategory, setVisitCategory] = useState<'All' | 'Public' | 'Private'>('All')

  useEffect(() => { loadFilters() }, [])

  async function loadFilters(){
    try {
      const [deps, docs, comps] = await Promise.all([
        hospitalApi.listDepartments() as any,
        hospitalApi.listDoctors() as any,
        corporateApi.listCompanies() as any,
      ])
      setDepartments(deps.departments || [])
      setDoctors(docs.doctors || [])
      const arr = (comps?.companies || comps?.data || comps || []).map((c:any)=>({ id: String(c._id||c.id), name: c.name }))
      setCompanies(arr)
    } catch {}
  }

  const load = useCallback(async (force: boolean = false) => {
    const isAll = rowsPerPage === -1
    const params: any = { from, to, page, limit: isAll ? 1000 : rowsPerPage }
    if (department !== 'All') params.departmentId = department
    if (doctor !== 'All') params.doctorId = doctor
    
    // Check cache first (unless forcing refresh)
    const cacheKey = createCacheKey('/hospital/tokens', params)
    if (!force) {
      const cached = getCache<{ tokens: any[], total: number }>(cacheKey)
      if (cached) {
        setBackendTotal(cached.total || 0)
        processTokens(cached.tokens)
        hasLoadedRef.current = true
        return
      }
    }
    
    // Only show loading spinner if no existing data
    if (!hasLoadedRef.current) setIsLoading(true)
    try {
      const res = await hospitalApi.listTokens(params) as any
      setBackendTotal(res.total || 0)
      
      // Cache the response
      setCache(cacheKey, { tokens: res.tokens || [], total: res.total || 0 })
      
      processTokens(res.tokens || [])
      hasLoadedRef.current = true
    } finally {
      setIsLoading(false)
    }
  }, [from, to, department, doctor, page, rowsPerPage])
  
  function processTokens(tokens: any[]) {
    const items: TokenRow[] = (tokens || []).map((t: any) => ({
      _id: t._id,
      date: t.dateIso,
      time: t.createdAt ? new Date(t.createdAt).toLocaleTimeString() : '',
      tokenNo: t.tokenNo,
      mrNo: t.patientId?.mrn || t.mrn || '-',
      patient: t.patientId?.fullName || t.patientName || '-',
      doctorId: String(t.doctorId?._id || t.doctorId?.id || t.doctorId || ''),
      performedBy: t.createdByUsername || t.createdBy || '-',
      guardianRel: t.patientId?.guardianRel,
      guardianName: t.patientId?.fatherName,
      cnic: t.patientId?.cnicNormalized || t.patientId?.cnic,
      visitCategory: t.visitCategory,
      gender: t.patientId?.gender,
      phone: t.patientId?.phoneNormalized,
      address: t.patientId?.address,
      age: t.patientId?.age,
      doctor: t.doctorId?.name || '-',
      department: t.departmentId?.name || '-',
      fee: Number(t.fee || 0),
      discount: Number(t.discount || 0),
      status: t.status,
      paidMethod: t.paidMethod || t.paymentMethod || t.method,
      isCorporate: !!t.corporateId,
      corporateId: t.corporateId,
      createdAt: t.createdAt,
    }))
    const rowsClean = items.filter(r => r.status !== 'cancelled')
    setRows(rowsClean)

    // Revenue split from tokens based on selected payment method at token creation
    let cash = 0
    let card = 0
    for (const r of rowsClean){
      if (r.status === 'returned') continue
      if (r.isCorporate) continue
      const amt = Number(r.fee || 0)
      if (!isFinite(amt) || amt <= 0) continue
      const method = String(r.paidMethod || 'Cash').toLowerCase()
      if (method === 'cash') cash += amt
      else if (method === 'bank' || method === 'card') card += amt
      else card += amt
    }
    setRevByMethod({ cash, card })
  }
  
  // Force refresh function
  const refresh = useCallback(() => {
    invalidateCache('/hospital/tokens')
    setForceRefresh(v => v + 1)
  }, [])
  
  // Trigger load when dependencies change
  useEffect(() => { load(forceRefresh > 0) }, [load, forceRefresh])
    
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    const start = new Date(from)
    const end = new Date(to)
    end.setHours(23,59,59,999)

    let result = rows.filter(r => {
      const d = new Date(r.date)
      if (d < start || d > end) return false
      if (department !== 'All' && r.department !== (departments.find(x=>x._id===department)?.name || r.department)) return false
      if (doctor !== 'All' && r.doctor !== (doctors.find(x=>x._id===doctor)?.name || r.doctor)) return false
      
      // Filter by token type (Cash/Corporate)
      if (tokenType === 'Corporate' && !r.isCorporate) return false
      if (tokenType === 'Cash' && r.isCorporate) return false
      
      // Filter by visit category (Public/Private)
      if (visitCategory === 'Public' && r.visitCategory === 'private') return false
      if (visitCategory === 'Private' && r.visitCategory !== 'private') return false
      
      if (!q) return true
      return [r.patient, r.mrNo, r.tokenNo, r.phone, r.doctor, r.department, r.gender, r.cnic, r.guardianName, r.guardianRel, r.time]
        .filter(Boolean)
        .some(v => String(v).toLowerCase().includes(q))
    })

    // Sort by createdAt descending (most recent first)
    result.sort((a, b) => {
      const aTime = a.createdAt ? new Date(a.createdAt).getTime() : 0
      const bTime = b.createdAt ? new Date(b.createdAt).getTime() : 0
      return bTime - aTime
    })

    return result
  }, [query, from, to, department, doctor, rows, departments, doctors, tokenType, visitCategory])

  // Revenue only from cash tokens (exclude corporate)
  const revenueRows = useMemo(() => filtered.filter(r => r.status !== 'returned' && !r.isCorporate), [filtered])

  const totalTokens = rowsPerPage === -1 ? filtered.length : backendTotal
  const totalRevenue = revByMethod.cash
  const cardRevenue = revByMethod.card
  const totalRevenueAll = revByMethod.cash + revByMethod.card
  const totalDiscount = revenueRows.reduce((s, r) => s + (r.discount || 0), 0)

  async function setStatus(row: TokenRow, next: TokenRow['status']){
    try{
      setActioningId(row._id)
      await hospitalApi.updateTokenStatus(row._id, next)
      // Invalidate cache and force refresh after status change
      refresh()
    } catch (e: any){
      setToast({ type: 'error', message: e?.message || 'Failed to update status' })
    } finally {
      setActioningId(null)
    }
  }

  function printSlip(r: TokenRow){
    const panelName = r.corporateId ? (companies.find(c=> c.id === String(r.corporateId))?.name || '') : ''
    const slip: TokenSlipData = {
      tokenNo: r.tokenNo,
      departmentName: r.department || '-',
      doctorName: r.doctor || '-',
      patientName: r.patient || '-',
      phone: r.phone || '',
      mrn: r.mrNo || '',
      age: r.age,
      gender: r.gender,
      guardianRel: r.guardianRel,
      guardianName: r.guardianName,
      cnic: r.cnic,
      address: r.address,
      amount: r.fee + (r.discount || 0),
      discount: r.discount || 0,
      payable: r.fee,
      createdAt: r.createdAt,
      tokenType: r.visitCategory?.toLowerCase() === 'private' ? 'Private' : 'General',
      isReprint: true,
      ...(panelName ? { corporateCompanyName: panelName } : {}),
    }
    setSlipData(slip)
    setShowSlip(true)
  }

  async function printRx(r: TokenRow){
    try{
      const s: any = await hospitalApi.getSettings()
      let docRec = doctors.find((d:any)=> String(d._id||d.id) === String(r.doctorId)) || doctors.find((d:any)=> String(d.name||'').toLowerCase() === String(r.doctor||'').toLowerCase())
      if (!docRec) {
        try {
          const res: any = await hospitalApi.listDoctors({ q: r.doctor || '' })
          docRec = (res?.doctors || res || []).find((d:any)=> String(d.name||'').toLowerCase() === String(r.doctor||'').toLowerCase())
        } catch {}
      }
      const panelName = (r as any)?.corporateId ? (companies.find(c=> c.id === String((r as any).corporateId))?.name || '') : ''
      await previewHospitalRxPdf({
        settings: {
          name: s?.settings?.name || s?.name,
          address: s?.settings?.address || s?.address,
          phone: s?.settings?.phone || s?.phone,
          logoDataUrl: s?.settings?.logoDataUrl || s?.logoDataUrl,
        },
        doctor: { 
          name: (docRec?.name || r.doctor || '-'),
          departmentName: r.department || '-',
          specialization: docRec?.specialization || '',
          qualification: docRec?.qualification || ''
        },
        patient: {
          name: r.patient || '-',
          mrn: r.mrNo || '-',
          fatherName: r.guardianName,
          age: r.age,
          gender: r.gender,
          phone: r.phone,
          address: r.address,
          cnic: r.cnic,
        },
        ...(panelName ? { corporatePanelName: panelName } : {}),
        items: [],
        createdAt: `${r.date}T${r.time}`,
        tokenNo: r.tokenNo,
      } as any)
    } catch (e: any){
      setToast({ type: 'error', message: e?.message || 'Failed to open prescription template' })
    }
  }

  const startIdx = (page - 1) * rowsPerPage
  const pageRows = filtered.slice(startIdx, startIdx + rowsPerPage)
  const totalPages = Math.max(1, Math.ceil(filtered.length / rowsPerPage))

  const exportPdf = async () => {
    try{
      const api = (window as any).electronAPI
      if (!api || typeof api.printPreviewHtml !== 'function'){
        setToast({ type: 'error', message: 'PDF export is only available in the desktop app' })
        return
      }
      const s: any = await hospitalApi.getSettings().catch(()=>({}))
      const hospital = {
        name: s?.settings?.name || s?.name || 'Hospital',
        address: s?.settings?.address || s?.address || '',
        phone: s?.settings?.phone || s?.phone || '',
        logoDataUrl: s?.settings?.logoDataUrl || s?.logoDataUrl || '',
      }

      const depName = department === 'All'
        ? 'All Departments'
        : (departments.find((d:any)=> String(d._id||d.id) === String(department))?.name || 'Department')
      const docName = doctor === 'All'
        ? 'All Doctors'
        : (doctors.find((d:any)=> String(d._id||d.id) === String(doctor))?.name || 'Doctor')

      const filters = `From: ${from}  •  To: ${to}  •  Dept: ${depName}  •  Doctor: ${docName}  •  Type: ${tokenType}  •  Category: ${visitCategory}  •  Search: ${query || '-'}`

      const htmlDoc = buildTokenHistoryPdfHtml({
        title: 'Token History',
        printedAt: new Date(),
        hospital,
        filters,
        rows: filtered.map(r => ({
          date: r.date,
          time: r.time,
          tokenNo: r.tokenNo,
          mrNo: r.mrNo,
          patient: r.patient,
          phone: r.phone,
          doctor: r.doctor,
          department: r.department,
          fee: r.fee,
          isCorporate: r.isCorporate,
          paidMethod: r.paidMethod as any,
          status: r.status,
        })),
      })

      const r = await api.printPreviewHtml(htmlDoc, { printBackground: true, marginsType: 0 })
      if (r && r.ok === false) setToast({ type: 'error', message: r.error || 'Failed to generate PDF' })
    }catch(e: any){
      setToast({ type: 'error', message: e?.message || 'Failed to generate PDF' })
    }
  }

  function openEdit(r: TokenRow){
    // Stay on current portal (reception or hospital)
    const portal = window.location.pathname.startsWith('/reception') ? 'reception' : 'hospital'
    navigate(`/${portal}/token-generator?tokenId=${encodeURIComponent(r._id)}`)
  }

  const exportCSV = () => {
    const cols = ['Date','Time','Type','Token #','MR #','Patient','Phone','Doctor','Department','Fee','Discount','Status']
    const lines = [cols.join(',')]
    for (const r of filtered) {
      const method = String(r.paidMethod || 'Cash').toLowerCase()
      const t = r.isCorporate ? 'Corporate' : (method === 'bank' || method === 'card' ? 'Card' : 'Cash')
      lines.push([
        r.date,
        r.time,
        t,
        r.tokenNo,
        r.mrNo,
        r.patient,
        r.phone ?? '',
        r.doctor ?? '',
        r.department ?? '',
        r.fee,
        r.discount || 0,
        r.status,
      ].map(v => typeof v === 'string' && v.includes(',') ? `"${v.replace(/"/g,'""')}"` : String(v)).join(','))
    }
    const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `token-history-${from}-to-${to}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-slate-50/50 p-4 transition-colors duration-300 dark:bg-slate-950 lg:p-8">
      {/* Header */}
      <div className="mb-6 flex flex-wrap items-end justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-white shadow-lg shadow-blue-500/20">
            <CalendarDays className="h-6 w-6" />
          </div>
          <div>
            <h1 className="text-2xl font-black tracking-tight text-slate-800 dark:text-white">Token History</h1>
            <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">Historical token records &amp; analytics</p>
          </div>
        </div>
        <div className="flex items-center gap-3 text-xs font-bold text-slate-400">
          <Clock className="h-4 w-4" />
          <span className="uppercase tracking-widest">{from === to ? from : `${from} → ${to}`}</span>
          <button onClick={refresh} disabled={isLoading} className="ml-2 flex h-8 w-8 items-center justify-center rounded-lg bg-white shadow-sm hover:bg-slate-50 dark:bg-slate-900 dark:hover:bg-slate-800">
            <RefreshCw className={`h-4 w-4 text-blue-600 ${isLoading ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* Filters & Search */}
      <div className="mb-6 rounded-2xl border border-slate-100 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div className="mb-4 flex flex-wrap items-center justify-between gap-4 border-b border-slate-50 pb-4 dark:border-slate-800">
          <div className="flex items-center gap-2">
            <Filter className="h-4 w-4 text-blue-600" />
            <span className="text-xs font-black uppercase tracking-widest text-slate-800 dark:text-white">Filters &amp; Search</span>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={exportCSV} className="flex items-center gap-2 rounded-lg bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-600 hover:bg-emerald-100 dark:bg-emerald-900/20">
              <FileSpreadsheet className="h-3.5 w-3.5" /> Export CSV
            </button>
            <button onClick={exportPdf} className="flex items-center gap-2 rounded-lg bg-rose-50 px-3 py-1.5 text-xs font-bold text-rose-600 hover:bg-rose-100 dark:bg-rose-900/20">
              <FileDown className="h-3.5 w-3.5" /> Export PDF
            </button>
          </div>
        </div>

        <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6">
          <div className="space-y-1">
            <label className="text-[10px] font-bold uppercase tracking-widest text-slate-400">From Date</label>
            <input type="date" value={from} onChange={e=>{setFrom(e.target.value); setPage(1)}} className="w-full rounded-xl border border-slate-100 bg-slate-50/50 px-3 py-2 text-sm font-semibold outline-none focus:ring-2 focus:ring-blue-500/20 dark:border-slate-800 dark:bg-slate-800/50" />
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold uppercase tracking-widest text-slate-400">To Date</label>
            <input type="date" value={to} onChange={e=>{setTo(e.target.value); setPage(1)}} className="w-full rounded-xl border border-slate-100 bg-slate-50/50 px-3 py-2 text-sm font-semibold outline-none focus:ring-2 focus:ring-blue-500/20 dark:border-slate-800 dark:bg-slate-800/50" />
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Department</label>
            <select value={department} onChange={e=>{setDepartment(e.target.value); setPage(1)}} className="w-full rounded-xl border border-slate-100 bg-slate-50/50 px-3 py-2 text-sm font-semibold outline-none focus:ring-2 focus:ring-blue-500/20 dark:border-slate-800 dark:bg-slate-800/50">
              <option value="All">All Departments</option>
              {departments.map((d:any) => (
                <option key={String(d._id || d.id)} value={String(d._id || d.id)}>{d.name}</option>
              ))}
            </select>
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Doctor</label>
            <select value={doctor} onChange={e=>{setDoctor(e.target.value); setPage(1)}} className="w-full rounded-xl border border-slate-100 bg-slate-50/50 px-3 py-2 text-sm font-semibold outline-none focus:ring-2 focus:ring-blue-500/20 dark:border-slate-800 dark:bg-slate-800/50">
              <option value="All">All Doctors</option>
              {doctors.map((d:any) => (
                <option key={String(d._id || d.id)} value={String(d._id || d.id)}>{d.name}</option>
              ))}
            </select>
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Billing Type</label>
            <select value={tokenType} onChange={e=>{setTokenType(e.target.value as any); setPage(1)}} className="w-full rounded-xl border border-slate-100 bg-slate-50/50 px-3 py-2 text-sm font-semibold outline-none focus:ring-2 focus:ring-blue-500/20 dark:border-slate-800 dark:bg-slate-800/50">
              <option value="All">All Types</option>
              <option value="Cash">Cash</option>
              <option value="Corporate">Corporate</option>
            </select>
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Category</label>
            <select value={visitCategory} onChange={e=>{setVisitCategory(e.target.value as any); setPage(1)}} className="w-full rounded-xl border border-slate-100 bg-slate-50/50 px-3 py-2 text-sm font-semibold outline-none focus:ring-2 focus:ring-blue-500/20 dark:border-slate-800 dark:bg-slate-800/50">
              <option value="All">All Categories</option>
              <option value="Public">General</option>
              <option value="Private">Private</option>
            </select>
          </div>
        </div>

        <div className="mt-4 flex items-center gap-3">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
            <input
              value={query}
              onChange={(e)=>{setQuery(e.target.value); setPage(1)}}
              placeholder="Search by name, token#, MR#, phone, doctor, department, age, gender, address, or time..."
              className="w-full rounded-xl border border-slate-100 bg-slate-50/50 py-2.5 pl-10 pr-4 text-sm font-semibold outline-none focus:ring-2 focus:ring-blue-500/20 dark:border-slate-800 dark:bg-slate-800/50"
            />
          </div>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="mb-6 grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">
        <StatCard title="Total Tokens" value={totalTokens} icon={Ticket} color="bg-blue-600" />
        <StatCard title="Total Revenue" value={`Rs. ${totalRevenueAll.toLocaleString()}`} icon={Wallet} color="bg-emerald-600" />
        <StatCard title="Cash Revenue" value={`Rs. ${totalRevenue.toLocaleString()}`} icon={Wallet} color="bg-violet-600" />
        <StatCard title="Card Revenue" value={`Rs. ${cardRevenue.toLocaleString()}`} icon={CreditCard} color="bg-indigo-600" />
        <StatCard title="Corporate" value={filtered.filter(r => r.isCorporate).length} icon={ShieldCheck} color="bg-blue-800" />
        <StatCard title="Discount" value={`Rs. ${totalDiscount.toLocaleString()}`} icon={TrendingUp} color="bg-amber-600" />
      </div>

      {/* Table Section */}
      <div className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div className="overflow-x-auto">
          <table className="w-full border-collapse text-left text-sm">
            <thead>
              <tr className="bg-slate-50/50 text-[10px] font-black uppercase tracking-widest text-slate-400 dark:bg-slate-800/50">
                <Th>Date / Time</Th>
                <Th>Token / MR #</Th>
                <Th>Patient Info</Th>
                <Th>Type / Category</Th>
                <Th>Doctor / Dept</Th>
                <Th>Financials</Th>
                <Th className="text-right">Actions</Th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50 dark:divide-slate-800">
              {pageRows.length === 0 ? (
                <tr>
                  <td colSpan={7} className="py-20 text-center">
                    <div className="flex flex-col items-center gap-2 text-slate-400">
                      <Search className="h-10 w-10 opacity-20" />
                      <p className="font-bold">No tokens found for selected period</p>
                    </div>
                  </td>
                </tr>
              ) : (
                pageRows.map((r) => (
                  <tr key={r._id} className={`group transition-colors hover:bg-slate-50/50 dark:hover:bg-slate-800/30 ${r.status === 'returned' ? 'bg-amber-50/30' : ''} ${r.isCorporate ? 'bg-violet-50/20' : ''}`}>
                    <Td>
                      <div className="font-bold text-slate-800 dark:text-white">{r.date}</div>
                      <div className="text-[10px] font-bold text-slate-400">{r.time}</div>
                    </Td>
                    <Td>
                      <div className="flex items-center gap-2">
                        <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-blue-50 text-xs font-black text-blue-700 dark:bg-blue-900/30 dark:text-blue-300">
                          {r.tokenNo}
                        </span>
                        <div className="text-xs font-bold text-slate-500">{r.mrNo}</div>
                      </div>
                    </Td>
                    <Td>
                      <div className="font-bold text-slate-800 dark:text-white">{r.patient}</div>
                      <div className="text-[10px] font-bold text-slate-400">{r.phone || '-'}{r.performedBy && r.performedBy !== '-' ? ` • by ${r.performedBy}` : ''}</div>
                    </Td>
                    <Td>
                      <div className="flex flex-col gap-1">
                        <div className="flex gap-1">
                          {r.isCorporate ? (
                            <span className="rounded-md bg-violet-100 px-1.5 py-0.5 text-[9px] font-black uppercase tracking-tighter text-violet-700 dark:bg-violet-900/30 dark:text-violet-300">Corporate</span>
                          ) : (
                            <span className={`rounded-md px-1.5 py-0.5 text-[9px] font-black uppercase tracking-tighter ${
                              String(r.paidMethod || 'Cash').toLowerCase() === 'cash' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300' : 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300'
                            }`}>
                              {r.paidMethod || 'Cash'}
                            </span>
                          )}
                        </div>
                        <span className={`w-fit rounded-md px-1.5 py-0.5 text-[9px] font-black uppercase tracking-tighter ${
                          r.visitCategory === 'private' ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300' : 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300'
                        }`}>
                          {r.visitCategory === 'private' ? 'Private' : 'General'}
                        </span>
                      </div>
                    </Td>
                    <Td>
                      <div className="font-bold text-slate-700 dark:text-slate-200">{r.doctor}</div>
                      <div className="text-[10px] font-bold text-slate-400 uppercase tracking-tighter">{r.department}</div>
                    </Td>
                    <Td>
                      <div className="font-black text-slate-800 dark:text-white">Rs. {r.fee.toLocaleString()}</div>
                      {r.discount > 0 && <div className="text-[10px] font-bold text-rose-500">Disc: Rs. {r.discount.toLocaleString()}</div>}
                    </Td>
                    <Td className="text-right">
                      <div className="flex items-center justify-end gap-1.5">
                        <button onClick={()=>printSlip(r)} className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-50 text-slate-600 transition-colors hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-400 dark:hover:bg-slate-700" title="Print Slip">
                          <Ticket className="h-4 w-4" />
                        </button>
                        <button onClick={()=>printRx(r)} className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-50 text-slate-600 transition-colors hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-400 dark:hover:bg-slate-700" title="Print Rx">
                          <Printer className="h-4 w-4" />
                        </button>
                        <button disabled={actioningId===r._id} onClick={()=>openEdit(r)} className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-50 text-slate-600 transition-colors hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-400 dark:hover:bg-slate-700" title="Edit">
                          <LayoutDashboard className="h-4 w-4" />
                        </button>
                        <button
                          disabled={actioningId===r._id}
                          onClick={()=>setStatus(r, r.status === 'returned' ? 'queued' : 'returned')}
                          className={`flex h-8 w-8 items-center justify-center rounded-lg transition-colors ${
                            r.status === 'returned' ? 'bg-amber-100 text-amber-700' : 'bg-slate-50 text-slate-600 hover:bg-amber-50 hover:text-amber-600 dark:bg-slate-800 dark:text-slate-400 dark:hover:bg-amber-900/30'
                          }`}
                          title={r.status === 'returned' ? 'Undo Return' : 'Mark Return'}
                        >
                          {r.status === 'returned' ? <UserCheck className="h-4 w-4" /> : <UserX className="h-4 w-4" />}
                        </button>
                      </div>
                    </Td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        <div className="flex items-center justify-between border-t border-slate-50 bg-slate-50/30 px-6 py-4 dark:border-slate-800 dark:bg-slate-900/50">
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <span className="text-[11px] font-black uppercase tracking-widest text-slate-400">Show</span>
              <select value={rowsPerPage} onChange={e=>{setRowsPerPage(parseInt(e.target.value)); setPage(1)}} className="rounded-xl border border-slate-200 bg-white px-3 py-1 text-xs font-bold outline-none focus:ring-2 focus:ring-blue-500/20 dark:border-slate-700 dark:bg-slate-800">
                {[10,20,50,100,200].map(n => <option key={n} value={n}>{n}</option>)}
                <option value={-1}>All</option>
              </select>
            </div>
            <p className="text-[11px] font-black uppercase tracking-widest text-slate-400">
              Page {page} of {totalPages}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="flex h-9 w-9 items-center justify-center rounded-xl bg-white text-slate-400 shadow-sm transition-all hover:bg-slate-50 hover:text-slate-600 disabled:opacity-30 dark:bg-slate-800">
              <ChevronLeft className="h-5 w-5" />
            </button>
            <button disabled={page>=totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))} className="flex h-9 w-9 items-center justify-center rounded-xl bg-white text-slate-400 shadow-sm transition-all hover:bg-slate-50 hover:text-slate-600 disabled:opacity-30 dark:bg-slate-800">
              <ChevronRight className="h-5 w-5" />
            </button>
          </div>
        </div>
      </div>

      {showSlip && slipData && (
        <Hospital_TokenSlip open={showSlip} onClose={()=>setShowSlip(false)} data={slipData as TokenSlipData} autoPrint={false} />
      )}
      <Toast toast={toast} onClose={()=>setToast(null)} />
    </div>
  )
}

function Th({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <th className={`px-4 py-3 text-[10px] font-black uppercase tracking-widest text-slate-400 ${className}`}>{children}</th>
}
function Td({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <td className={`px-4 py-4 ${className}`}>{children}</td>
}

function StatCard({ title, value, icon: Icon, color }: { title: string; value: ReactNode; icon: any; color: string }) {
  return (
    <div className="relative overflow-hidden rounded-2xl border border-slate-100 bg-white p-4 shadow-sm transition-all duration-200 hover:shadow-md dark:border-slate-800 dark:bg-slate-900">
      <div className={`absolute -right-3 -top-3 h-16 w-16 rounded-full opacity-[0.07] ${color}`} />
      <div className="flex items-center gap-3">
        <div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${color} bg-opacity-10`}>
          <Icon className={`h-5 w-5 ${color.replace('bg-', 'text-')}`} />
        </div>
        <div className="min-w-0 flex-1">
          <p className="truncate text-[10px] font-bold uppercase tracking-wider text-slate-400">{title}</p>
          <p className="text-lg font-black text-slate-800 dark:text-white">{value}</p>
        </div>
      </div>
    </div>
  )
}
